# View All Subjects' Training Data

This notebook loads the latest subject-specific training datasets, shows each subject’s selected four activities and label mapping, displays all window metadata, and previews a complete 128-timestep sensor window for every subject. A final cell exports every training timestep and feature value to a separate long-format CSV per subject.

Run from the workspace root or from inside `DATA_PREP`. The notebook reads the latest selection folder under `DATA_PREP/processed_datasets_from_activity_config/`. Values in `X_train.npy` are standardized sensor values. Only original `_1_extracted` recordings are used for training.

S4 is included with its four available training activities. It has no `_2_extracted` folders, so its test array is intentionally empty; `_extracted_r` training variants are not treated as test data.

In [12]:
from pathlib import Path
from collections import Counter
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

current_directory = Path.cwd().resolve()
OUTPUT_PARENT_NAME = 'processed_datasets_from_activity_config'
DATA_PREP_DIR = None
for candidate in (current_directory, *current_directory.parents):
    if candidate.name.lower() == 'data_prep' and (candidate / OUTPUT_PARENT_NAME).is_dir():
        DATA_PREP_DIR = candidate
        break
    nested_data_prep = candidate / 'DATA_PREP'
    if (nested_data_prep / OUTPUT_PARENT_NAME).is_dir():
        DATA_PREP_DIR = nested_data_prep
        break
if DATA_PREP_DIR is None:
    raise FileNotFoundError(f'Could not locate DATA_PREP/{OUTPUT_PARENT_NAME} above {current_directory}')

OUTPUT_PARENT = DATA_PREP_DIR / OUTPUT_PARENT_NAME
prepared_roots = sorted(
    (path for path in OUTPUT_PARENT.glob('selection_*') if (path / 'subject_preparation_summary.csv').is_file()),
    key=lambda path: path.stat().st_mtime,
    reverse=True,
)
if not prepared_roots:
    raise FileNotFoundError(f'No completed selection_* dataset found under {OUTPUT_PARENT}')
PREPARED_ROOT = prepared_roots[0]
SUBJECT_SUMMARY = pd.read_csv(PREPARED_ROOT / 'subject_preparation_summary.csv')
CLASS_MAPPINGS = json.loads((PREPARED_ROOT / 'class_mappings_by_subject.json').read_text(encoding='utf-8'))
SUBJECT_TRAINING = {}

print(f'Prepared data root: {PREPARED_ROOT}')
print('Subject preparation status:')
display(SUBJECT_SUMMARY)

for _, row in SUBJECT_SUMMARY.iterrows():
    if not str(row['status']).startswith('prepared'):
        continue
    subject = row['subject']
    subject_dir = PREPARED_ROOT / subject
    X = np.load(subject_dir / 'X_train.npy')
    y = np.load(subject_dir / 'y_train.npy')
    metadata = pd.read_csv(subject_dir / 'train_metadata.csv')
    feature_names = json.loads((subject_dir / 'feature_names.json').read_text(encoding='utf-8'))
    class_mapping = CLASS_MAPPINGS[subject]
    class_names = {label: activity for activity, label in class_mapping.items()}

    if not metadata['original_folder'].str.endswith('_1_extracted').all():
        raise ValueError(f'{subject} training metadata contains a non-training source folder.')
    if len(X) != len(y) or len(X) != len(metadata):
        raise ValueError(f'{subject} X_train, y_train, and metadata lengths do not match.')
    if set(np.unique(y).tolist()) != set(class_mapping.values()):
        raise ValueError(f'{subject} y_train labels do not match its subject-specific class mapping.')

    SUBJECT_TRAINING[subject] = {
        'X': X,
        'y': y,
        'metadata': metadata,
        'feature_names': feature_names,
        'class_mapping': class_mapping,
        'class_names': class_names,
        'directory': subject_dir,
        'status': row['status'],
    }

summary_rows = []
for subject, data in SUBJECT_TRAINING.items():
    counts = Counter(data['y'].tolist())
    summary_rows.append({
        'subject': subject,
        'status': data['status'],
        'class_mapping': data['class_mapping'],
        'X_train_shape': str(data['X'].shape),
        'y_train_shape': str(data['y'].shape),
        'feature_count': len(data['feature_names']),
        'training_windows': len(data['X']),
        'label_counts': {data['class_names'][label]: counts[label] for label in sorted(data['class_names'])},
        'source_folders': ', '.join(sorted(data['metadata']['original_folder'].unique())),
    })
print('Training dataset overview, including S4 training-only data:')
display(pd.DataFrame(summary_rows))

Prepared data root: D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\DATA_PREP\processed_datasets_from_activity_config\selection_14b5013a3e02
Subject preparation status:

,subject,status,selected_activities,missing_test_activities,train_windows,test_windows,output_dir
0,S1,prepared,"Bending,Bring,CleanFloor,CleanSurface",NaN,38,37,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
1,S2,prepared,"CloseBigBox,CloseDoor,CloseDrawer,CloseLidByRo...",NaN,25,25,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
2,S3,prepared,"closeotherlid,closesmallbox,drink,dryoffhand",NaN,28,29,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
3,S4,prepared_training_only_no_test_data,"DryOffHandByShake,eatsmallthing,Gargle,GetUp","DryOffHandByShake,Gargle,GetUp,eatsmallthing",36,0,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
4,S5,prepared,"Hang,LieDown,Lying,OpenBag",NaN,37,40,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
5,S6,prepared,"OpenBigBox,OpenDoor,OpenDrawer,OpenLidByRotate",NaN,31,31,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
6,S7,prepared,"Dryoffhands,Openotherlid,Opensmallbox,Plugin",NaN,30,31,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
7,S8,prepared,"PressByGrasp,Pressfromtop,PressSwitch,PutFromB...",NaN,29,27,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...

Training dataset overview, including S4 training-only data:

,subject,status,class_mapping,X_train_shape,y_train_shape,feature_count,training_windows,label_counts,source_folders
0,S1,prepared,"{'Bending': 0, 'Bring': 1, 'CleanFloor': 2, 'C...","(38, 128, 33)","(38,)",33,38,"{'Bending': 10, 'Bring': 10, 'CleanFloor': 11,...","S1_Bending_1_extracted, S1_Bring_1_extracted, ..."
1,S2,prepared,"{'CloseBigBox': 0, 'CloseDoor': 1, 'CloseDrawe...","(25, 128, 33)","(25,)",33,25,"{'CloseBigBox': 10, 'CloseDoor': 5, 'CloseDraw...","S2_CloseBigBox_1_extracted, S2_CloseDoor_1_ext..."
2,S3,prepared,"{'closeotherlid': 0, 'closesmallbox': 1, 'drin...","(28, 128, 33)","(28,)",33,28,"{'closeotherlid': 7, 'closesmallbox': 7, 'drin...","S3_closeotherlid_1_extracted, S3_closesmallbox..."
3,S4,prepared_training_only_no_test_data,"{'DryOffHandByShake': 0, 'eatsmallthing': 1, '...","(36, 128, 33)","(36,)",33,36,"{'DryOffHandByShake': 10, 'eatsmallthing': 7, ...","S4_DryOffHandByShake_1_extracted, S4_Gargle_1_..."
4,S5,prepared,"{'Hang': 0, 'LieDown': 1, 'Lying': 2, 'OpenBag...","(37, 128, 33)","(37,)",33,37,"{'Hang': 10, 'LieDown': 10, 'Lying': 7, 'OpenB...","S5_Hang_1_extracted, S5_LieDown_1_extracted, S..."
5,S6,prepared,"{'OpenBigBox': 0, 'OpenDoor': 1, 'OpenDrawer':...","(31, 128, 33)","(31,)",33,31,"{'OpenBigBox': 10, 'OpenDoor': 7, 'OpenDrawer'...","S6_OpenBigBox_1_extracted, S6_OpenDoor_1_extra..."
6,S7,prepared,"{'Dryoffhands': 0, 'Openotherlid': 1, 'Opensma...","(30, 128, 33)","(30,)",33,30,"{'Dryoffhands': 10, 'Openotherlid': 7, 'Opensm...","S7_Dryoffhands_1_extracted, S7_Openotherlid_1_..."
7,S8,prepared,"{'PressByGrasp': 0, 'Pressfromtop': 1, 'PressS...","(29, 128, 33)","(29,)",33,29,"{'PressByGrasp': 7, 'Pressfromtop': 7, 'PressS...","S8_PressByGrasp_1_extracted, S8_PressSwitch_1_..."

In [7]:
print('All training-window labels and source metadata, grouped by subject:')
for subject, data in SUBJECT_TRAINING.items():
    metadata_view = data['metadata'].copy()
    metadata_view.insert(0, 'sample_index', np.arange(len(metadata_view)))
    print(f'\n{subject}: {len(metadata_view)} training windows')
    display(metadata_view)


def show_training_window(subject, sample_index=0):
    """Display one complete 128-timestep x feature-count training window."""
    data = SUBJECT_TRAINING[subject]
    if not 0 <= sample_index < len(data['X']):
        raise IndexError(f'{subject} sample_index must be between 0 and {len(data["X"]) - 1}.')
    row = data['metadata'].iloc[sample_index]
    label = int(data['y'][sample_index])
    window = pd.DataFrame(data['X'][sample_index], columns=data['feature_names'])
    window.index.name = 'timestep (20 ms each)'
    print(f'{subject} X_train[{sample_index}]: shape={window.shape}; label={label} ({row["activity"]})')
    print(f'Source: {row["original_folder"]} / {row["event"]} / window {row["window_id"]}')
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', None):
        display(window)


print('\nFull first training window for each available subject:')
for subject in SUBJECT_TRAINING:
    show_training_window(subject, sample_index=0)

All training-window labels and source metadata, grouped by subject:

S1: 38 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S1,Bending,train,1,Event_0,0,0,S1_Bending_1_extracted,train
1,1,S1,Bending,train,1,Event_1,0,0,S1_Bending_1_extracted,train
2,2,S1,Bending,train,1,Event_2,0,0,S1_Bending_1_extracted,train
3,3,S1,Bending,train,1,Event_3,0,0,S1_Bending_1_extracted,train
4,4,S1,Bending,train,1,Event_4,0,0,S1_Bending_1_extracted,train
5,5,S1,Bending,train,1,Event_5,0,0,S1_Bending_1_extracted,train
6,6,S1,Bending,train,1,Event_6,0,0,S1_Bending_1_extracted,train
7,7,S1,Bending,train,1,Event_7,0,0,S1_Bending_1_extracted,train
8,8,S1,Bending,train,1,Event_8,0,0,S1_Bending_1_extracted,train
9,9,S1,Bending,train,1,Event_9,0,0,S1_Bending_1_extracted,train
10,10,S1,Bring,train,1,Event_0,0,1,S1_Bring_1_extracted,train
11,11,S1,Bring,train,1,Event_1,0,1,S1_Bring_1_extracted,train
12,12,S1,Bring,train,1,Event_2,0,1,S1_Bring_1_extracted,train
13,13,S1,Bring,train,1,Event_3,0,1,S1_Bring_1_extracted,train
14,14,S1,Bring,train,1,Event_4,0,1,S1_Bring_1_extracted,train
15,15,S1,Bring,train,1,Event_5,0,1,S1_Bring_1_extracted,train
16,16,S1,Bring,train,1,Event_6,0,1,S1_Bring_1_extracted,train
17,17,S1,Bring,train,1,Event_7,0,1,S1_Bring_1_extracted,train
18,18,S1,Bring,train,1,Event_8,0,1,S1_Bring_1_extracted,train
19,19,S1,Bring,train,1,Event_9,0,1,S1_Bring_1_extracted,train
20,20,S1,CleanFloor,train,1,Event_0,0,2,S1_CleanFloor_1_extracted,train
21,21,S1,CleanFloor,train,1,Event_1,0,2,S1_CleanFloor_1_extracted,train
22,22,S1,CleanFloor,train,1,Event_2,0,2,S1_CleanFloor_1_extracted,train
23,23,S1,CleanFloor,train,1,Event_3,0,2,S1_CleanFloor_1_extracted,train
24,24,S1,CleanFloor,train,1,Event_4,0,2,S1_CleanFloor_1_extracted,train
25,25,S1,CleanFloor,train,1,Event_5,0,2,S1_CleanFloor_1_extracted,train
26,26,S1,CleanFloor,train,1,Event_6,0,2,S1_CleanFloor_1_extracted,train
27,27,S1,CleanFloor,train,1,Event_7,0,2,S1_CleanFloor_1_extracted,train
28,28,S1,CleanFloor,train,1,Event_8,0,2,S1_CleanFloor_1_extracted,train
29,29,S1,CleanFloor,train,1,Event_9,0,2,S1_CleanFloor_1_extracted,train
30,30,S1,CleanFloor,train,1,Event_10,0,2,S1_CleanFloor_1_extracted,train
31,31,S1,CleanSurface,train,1,Event_0,0,3,S1_CleanSurface_1_extracted,train
32,32,S1,CleanSurface,train,1,Event_1,0,3,S1_CleanSurface_1_extracted,train
33,33,S1,CleanSurface,train,1,Event_2,0,3,S1_CleanSurface_1_extracted,train
34,34,S1,CleanSurface,train,1,Event_3,0,3,S1_CleanSurface_1_extracted,train
35,35,S1,CleanSurface,train,1,Event_4,0,3,S1_CleanSurface_1_extracted,train
36,36,S1,CleanSurface,train,1,Event_5,0,3,S1_CleanSurface_1_extracted,train
37,37,S1,CleanSurface,train,1,Event_6,0,3,S1_CleanSurface_1_extracted,train

S2: 25 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S2,CloseBigBox,train,1,Event_0,0,0,S2_CloseBigBox_1_extracted,train
1,1,S2,CloseBigBox,train,1,Event_1,0,0,S2_CloseBigBox_1_extracted,train
2,2,S2,CloseBigBox,train,1,Event_2,0,0,S2_CloseBigBox_1_extracted,train
3,3,S2,CloseBigBox,train,1,Event_3,0,0,S2_CloseBigBox_1_extracted,train
4,4,S2,CloseBigBox,train,1,Event_4,0,0,S2_CloseBigBox_1_extracted,train
5,5,S2,CloseBigBox,train,1,Event_5,0,0,S2_CloseBigBox_1_extracted,train
6,6,S2,CloseBigBox,train,1,Event_6,0,0,S2_CloseBigBox_1_extracted,train
7,7,S2,CloseBigBox,train,1,Event_7,0,0,S2_CloseBigBox_1_extracted,train
8,8,S2,CloseBigBox,train,1,Event_8,0,0,S2_CloseBigBox_1_extracted,train
9,9,S2,CloseBigBox,train,1,Event_9,0,0,S2_CloseBigBox_1_extracted,train
10,10,S2,CloseDoor,train,1,Event_0,0,1,S2_CloseDoor_1_extracted,train
11,11,S2,CloseDoor,train,1,Event_1,0,1,S2_CloseDoor_1_extracted,train
12,12,S2,CloseDoor,train,1,Event_2,0,1,S2_CloseDoor_1_extracted,train
13,13,S2,CloseDoor,train,1,Event_3,0,1,S2_CloseDoor_1_extracted,train
14,14,S2,CloseDoor,train,1,Event_4,0,1,S2_CloseDoor_1_extracted,train
15,15,S2,CloseDrawer,train,1,Event_0,0,2,S2_CloseDrawer_1_extracted,train
16,16,S2,CloseDrawer,train,1,Event_1,0,2,S2_CloseDrawer_1_extracted,train
17,17,S2,CloseDrawer,train,1,Event_2,0,2,S2_CloseDrawer_1_extracted,train
18,18,S2,CloseDrawer,train,1,Event_3,0,2,S2_CloseDrawer_1_extracted,train
19,19,S2,CloseDrawer,train,1,Event_4,0,2,S2_CloseDrawer_1_extracted,train
20,20,S2,CloseLidByRotate,train,1,Event_0,0,3,S2_CloseLidByRotate_1_extracted,train
21,21,S2,CloseLidByRotate,train,1,Event_1,0,3,S2_CloseLidByRotate_1_extracted,train
22,22,S2,CloseLidByRotate,train,1,Event_2,0,3,S2_CloseLidByRotate_1_extracted,train
23,23,S2,CloseLidByRotate,train,1,Event_3,0,3,S2_CloseLidByRotate_1_extracted,train
24,24,S2,CloseLidByRotate,train,1,Event_4,0,3,S2_CloseLidByRotate_1_extracted,train

S3: 28 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S3,closeotherlid,train,1,Event_0,0,0,S3_closeotherlid_1_extracted,train
1,1,S3,closeotherlid,train,1,Event_1,0,0,S3_closeotherlid_1_extracted,train
2,2,S3,closeotherlid,train,1,Event_2,0,0,S3_closeotherlid_1_extracted,train
3,3,S3,closeotherlid,train,1,Event_3,0,0,S3_closeotherlid_1_extracted,train
4,4,S3,closeotherlid,train,1,Event_4,0,0,S3_closeotherlid_1_extracted,train
5,5,S3,closeotherlid,train,1,Event_5,0,0,S3_closeotherlid_1_extracted,train
6,6,S3,closeotherlid,train,1,Event_6,0,0,S3_closeotherlid_1_extracted,train
7,7,S3,closesmallbox,train,1,Event_0,0,1,S3_closesmallbox_1_extracted,train
8,8,S3,closesmallbox,train,1,Event_1,0,1,S3_closesmallbox_1_extracted,train
9,9,S3,closesmallbox,train,1,Event_2,0,1,S3_closesmallbox_1_extracted,train
10,10,S3,closesmallbox,train,1,Event_3,0,1,S3_closesmallbox_1_extracted,train
11,11,S3,closesmallbox,train,1,Event_4,0,1,S3_closesmallbox_1_extracted,train
12,12,S3,closesmallbox,train,1,Event_5,0,1,S3_closesmallbox_1_extracted,train
13,13,S3,closesmallbox,train,1,Event_6,0,1,S3_closesmallbox_1_extracted,train
14,14,S3,drink,train,1,Event_0,0,2,S3_drink_1_extracted,train
15,15,S3,drink,train,1,Event_1,0,2,S3_drink_1_extracted,train
16,16,S3,drink,train,1,Event_2,0,2,S3_drink_1_extracted,train
17,17,S3,drink,train,1,Event_3,0,2,S3_drink_1_extracted,train
18,18,S3,drink,train,1,Event_4,0,2,S3_drink_1_extracted,train
19,19,S3,drink,train,1,Event_5,0,2,S3_drink_1_extracted,train
20,20,S3,drink,train,1,Event_6,0,2,S3_drink_1_extracted,train
21,21,S3,dryoffhand,train,1,Event_0,0,3,S3_dryoffhand_1_extracted,train
22,22,S3,dryoffhand,train,1,Event_2,0,3,S3_dryoffhand_1_extracted,train
23,23,S3,dryoffhand,train,1,Event_3,0,3,S3_dryoffhand_1_extracted,train
24,24,S3,dryoffhand,train,1,Event_4,0,3,S3_dryoffhand_1_extracted,train
25,25,S3,dryoffhand,train,1,Event_6,0,3,S3_dryoffhand_1_extracted,train
26,26,S3,dryoffhand,train,1,Event_7,0,3,S3_dryoffhand_1_extracted,train
27,27,S3,dryoffhand,train,1,Event_8,0,3,S3_dryoffhand_1_extracted,train

S4: 36 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S4,DryOffHandByShake,train,1,Event_0,0,0,S4_DryOffHandByShake_1_extracted,train
1,1,S4,DryOffHandByShake,train,1,Event_1,0,0,S4_DryOffHandByShake_1_extracted,train
2,2,S4,DryOffHandByShake,train,1,Event_2,0,0,S4_DryOffHandByShake_1_extracted,train
3,3,S4,DryOffHandByShake,train,1,Event_3,0,0,S4_DryOffHandByShake_1_extracted,train
4,4,S4,DryOffHandByShake,train,1,Event_4,0,0,S4_DryOffHandByShake_1_extracted,train
5,5,S4,DryOffHandByShake,train,1,Event_5,0,0,S4_DryOffHandByShake_1_extracted,train
6,6,S4,DryOffHandByShake,train,1,Event_6,0,0,S4_DryOffHandByShake_1_extracted,train
7,7,S4,DryOffHandByShake,train,1,Event_7,0,0,S4_DryOffHandByShake_1_extracted,train
8,8,S4,DryOffHandByShake,train,1,Event_8,0,0,S4_DryOffHandByShake_1_extracted,train
9,9,S4,DryOffHandByShake,train,1,Event_9,0,0,S4_DryOffHandByShake_1_extracted,train
10,10,S4,eatsmallthing,train,1,Event_0,0,1,S4_eatsmallthing_1_extracted,train
11,11,S4,eatsmallthing,train,1,Event_1,0,1,S4_eatsmallthing_1_extracted,train
12,12,S4,eatsmallthing,train,1,Event_2,0,1,S4_eatsmallthing_1_extracted,train
13,13,S4,eatsmallthing,train,1,Event_3,0,1,S4_eatsmallthing_1_extracted,train
14,14,S4,eatsmallthing,train,1,Event_4,0,1,S4_eatsmallthing_1_extracted,train
15,15,S4,eatsmallthing,train,1,Event_5,0,1,S4_eatsmallthing_1_extracted,train
16,16,S4,eatsmallthing,train,1,Event_6,0,1,S4_eatsmallthing_1_extracted,train
17,17,S4,Gargle,train,1,Event_0,0,2,S4_Gargle_1_extracted,train
18,18,S4,Gargle,train,1,Event_1,0,2,S4_Gargle_1_extracted,train
19,19,S4,Gargle,train,1,Event_2,0,2,S4_Gargle_1_extracted,train
20,20,S4,Gargle,train,1,Event_3,0,2,S4_Gargle_1_extracted,train
21,21,S4,Gargle,train,1,Event_4,0,2,S4_Gargle_1_extracted,train
22,22,S4,Gargle,train,1,Event_5,0,2,S4_Gargle_1_extracted,train
23,23,S4,Gargle,train,1,Event_6,0,2,S4_Gargle_1_extracted,train
24,24,S4,Gargle,train,1,Event_7,0,2,S4_Gargle_1_extracted,train
25,25,S4,GetUp,train,1,Event_0,0,3,S4_GetUp_1_extracted,train
26,26,S4,GetUp,train,1,Event_1,0,3,S4_GetUp_1_extracted,train
27,27,S4,GetUp,train,1,Event_2,0,3,S4_GetUp_1_extracted,train
28,28,S4,GetUp,train,1,Event_3,0,3,S4_GetUp_1_extracted,train
29,29,S4,GetUp,train,1,Event_4,0,3,S4_GetUp_1_extracted,train
30,30,S4,GetUp,train,1,Event_5,0,3,S4_GetUp_1_extracted,train
31,31,S4,GetUp,train,1,Event_6,0,3,S4_GetUp_1_extracted,train
32,32,S4,GetUp,train,1,Event_7,0,3,S4_GetUp_1_extracted,train
33,33,S4,GetUp,train,1,Event_8,0,3,S4_GetUp_1_extracted,train
34,34,S4,GetUp,train,1,Event_9,0,3,S4_GetUp_1_extracted,train
35,35,S4,GetUp,train,1,Event_10,0,3,S4_GetUp_1_extracted,train

S5: 37 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S5,Hang,train,1,Event_0,0,0,S5_Hang_1_extracted,train
1,1,S5,Hang,train,1,Event_1,0,0,S5_Hang_1_extracted,train
2,2,S5,Hang,train,1,Event_2,0,0,S5_Hang_1_extracted,train
3,3,S5,Hang,train,1,Event_3,0,0,S5_Hang_1_extracted,train
4,4,S5,Hang,train,1,Event_4,0,0,S5_Hang_1_extracted,train
5,5,S5,Hang,train,1,Event_5,0,0,S5_Hang_1_extracted,train
6,6,S5,Hang,train,1,Event_6,0,0,S5_Hang_1_extracted,train
7,7,S5,Hang,train,1,Event_7,0,0,S5_Hang_1_extracted,train
8,8,S5,Hang,train,1,Event_8,0,0,S5_Hang_1_extracted,train
9,9,S5,Hang,train,1,Event_9,0,0,S5_Hang_1_extracted,train
10,10,S5,LieDown,train,1,Event_0,0,1,S5_LieDown_1_extracted,train
11,11,S5,LieDown,train,1,Event_1,0,1,S5_LieDown_1_extracted,train
12,12,S5,LieDown,train,1,Event_2,0,1,S5_LieDown_1_extracted,train
13,13,S5,LieDown,train,1,Event_3,0,1,S5_LieDown_1_extracted,train
14,14,S5,LieDown,train,1,Event_4,0,1,S5_LieDown_1_extracted,train
15,15,S5,LieDown,train,1,Event_5,0,1,S5_LieDown_1_extracted,train
16,16,S5,LieDown,train,1,Event_6,0,1,S5_LieDown_1_extracted,train
17,17,S5,LieDown,train,1,Event_7,0,1,S5_LieDown_1_extracted,train
18,18,S5,LieDown,train,1,Event_8,0,1,S5_LieDown_1_extracted,train
19,19,S5,LieDown,train,1,Event_9,0,1,S5_LieDown_1_extracted,train
20,20,S5,Lying,train,1,Event_3,0,2,S5_Lying_1_extracted,train
21,21,S5,Lying,train,1,Event_4,0,2,S5_Lying_1_extracted,train
22,22,S5,Lying,train,1,Event_5,0,2,S5_Lying_1_extracted,train
23,23,S5,Lying,train,1,Event_6,0,2,S5_Lying_1_extracted,train
24,24,S5,Lying,train,1,Event_7,0,2,S5_Lying_1_extracted,train
25,25,S5,Lying,train,1,Event_8,0,2,S5_Lying_1_extracted,train
26,26,S5,Lying,train,1,Event_9,0,2,S5_Lying_1_extracted,train
27,27,S5,OpenBag,train,1,Event_0,0,3,S5_OpenBag_1_extracted,train
28,28,S5,OpenBag,train,1,Event_1,0,3,S5_OpenBag_1_extracted,train
29,29,S5,OpenBag,train,1,Event_2,0,3,S5_OpenBag_1_extracted,train
30,30,S5,OpenBag,train,1,Event_3,0,3,S5_OpenBag_1_extracted,train
31,31,S5,OpenBag,train,1,Event_4,0,3,S5_OpenBag_1_extracted,train
32,32,S5,OpenBag,train,1,Event_5,0,3,S5_OpenBag_1_extracted,train
33,33,S5,OpenBag,train,1,Event_6,0,3,S5_OpenBag_1_extracted,train
34,34,S5,OpenBag,train,1,Event_7,0,3,S5_OpenBag_1_extracted,train
35,35,S5,OpenBag,train,1,Event_8,0,3,S5_OpenBag_1_extracted,train
36,36,S5,OpenBag,train,1,Event_9,0,3,S5_OpenBag_1_extracted,train

S6: 31 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S6,OpenBigBox,train,1,Event_0,0,0,S6_OpenBigBox_1_extracted,train
1,1,S6,OpenBigBox,train,1,Event_1,0,0,S6_OpenBigBox_1_extracted,train
2,2,S6,OpenBigBox,train,1,Event_2,0,0,S6_OpenBigBox_1_extracted,train
3,3,S6,OpenBigBox,train,1,Event_3,0,0,S6_OpenBigBox_1_extracted,train
4,4,S6,OpenBigBox,train,1,Event_4,0,0,S6_OpenBigBox_1_extracted,train
5,5,S6,OpenBigBox,train,1,Event_5,0,0,S6_OpenBigBox_1_extracted,train
6,6,S6,OpenBigBox,train,1,Event_6,0,0,S6_OpenBigBox_1_extracted,train
7,7,S6,OpenBigBox,train,1,Event_7,0,0,S6_OpenBigBox_1_extracted,train
8,8,S6,OpenBigBox,train,1,Event_8,0,0,S6_OpenBigBox_1_extracted,train
9,9,S6,OpenBigBox,train,1,Event_9,0,0,S6_OpenBigBox_1_extracted,train
10,10,S6,OpenDoor,train,1,Event_0,0,1,S6_OpenDoor_1_extracted,train
11,11,S6,OpenDoor,train,1,Event_1,0,1,S6_OpenDoor_1_extracted,train
12,12,S6,OpenDoor,train,1,Event_2,0,1,S6_OpenDoor_1_extracted,train
13,13,S6,OpenDoor,train,1,Event_3,0,1,S6_OpenDoor_1_extracted,train
14,14,S6,OpenDoor,train,1,Event_4,0,1,S6_OpenDoor_1_extracted,train
15,15,S6,OpenDoor,train,1,Event_5,0,1,S6_OpenDoor_1_extracted,train
16,16,S6,OpenDoor,train,1,Event_6,0,1,S6_OpenDoor_1_extracted,train
17,17,S6,OpenDrawer,train,1,Event_0,0,2,S6_OpenDrawer_1_extracted,train
18,18,S6,OpenDrawer,train,1,Event_1,0,2,S6_OpenDrawer_1_extracted,train
19,19,S6,OpenDrawer,train,1,Event_2,0,2,S6_OpenDrawer_1_extracted,train
20,20,S6,OpenDrawer,train,1,Event_3,0,2,S6_OpenDrawer_1_extracted,train
21,21,S6,OpenDrawer,train,1,Event_4,0,2,S6_OpenDrawer_1_extracted,train
22,22,S6,OpenDrawer,train,1,Event_5,0,2,S6_OpenDrawer_1_extracted,train
23,23,S6,OpenDrawer,train,1,Event_6,0,2,S6_OpenDrawer_1_extracted,train
24,24,S6,OpenLidByRotate,train,1,Event_0,0,3,S6_OpenLidByRotate_1_extracted,train
25,25,S6,OpenLidByRotate,train,1,Event_1,0,3,S6_OpenLidByRotate_1_extracted,train
26,26,S6,OpenLidByRotate,train,1,Event_2,0,3,S6_OpenLidByRotate_1_extracted,train
27,27,S6,OpenLidByRotate,train,1,Event_3,0,3,S6_OpenLidByRotate_1_extracted,train
28,28,S6,OpenLidByRotate,train,1,Event_4,0,3,S6_OpenLidByRotate_1_extracted,train
29,29,S6,OpenLidByRotate,train,1,Event_5,0,3,S6_OpenLidByRotate_1_extracted,train
30,30,S6,OpenLidByRotate,train,1,Event_6,0,3,S6_OpenLidByRotate_1_extracted,train

S7: 30 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S7,Dryoffhands,train,1,Event_0,0,0,S7_Dryoffhands_1_extracted,train
1,1,S7,Dryoffhands,train,1,Event_1,0,0,S7_Dryoffhands_1_extracted,train
2,2,S7,Dryoffhands,train,1,Event_2,0,0,S7_Dryoffhands_1_extracted,train
3,3,S7,Dryoffhands,train,1,Event_3,0,0,S7_Dryoffhands_1_extracted,train
4,4,S7,Dryoffhands,train,1,Event_4,0,0,S7_Dryoffhands_1_extracted,train
5,5,S7,Dryoffhands,train,1,Event_5,0,0,S7_Dryoffhands_1_extracted,train
6,6,S7,Dryoffhands,train,1,Event_6,0,0,S7_Dryoffhands_1_extracted,train
7,7,S7,Dryoffhands,train,1,Event_7,0,0,S7_Dryoffhands_1_extracted,train
8,8,S7,Dryoffhands,train,1,Event_8,0,0,S7_Dryoffhands_1_extracted,train
9,9,S7,Dryoffhands,train,1,Event_9,0,0,S7_Dryoffhands_1_extracted,train
10,10,S7,Openotherlid,train,1,Event_0,0,1,S7_Openotherlid_1_extracted,train
11,11,S7,Openotherlid,train,1,Event_1,0,1,S7_Openotherlid_1_extracted,train
12,12,S7,Openotherlid,train,1,Event_2,0,1,S7_Openotherlid_1_extracted,train
13,13,S7,Openotherlid,train,1,Event_3,0,1,S7_Openotherlid_1_extracted,train
14,14,S7,Openotherlid,train,1,Event_4,0,1,S7_Openotherlid_1_extracted,train
15,15,S7,Openotherlid,train,1,Event_5,0,1,S7_Openotherlid_1_extracted,train
16,16,S7,Openotherlid,train,1,Event_6,0,1,S7_Openotherlid_1_extracted,train
17,17,S7,Opensmallbox,train,1,Event_0,0,2,S7_Opensmallbox_1_extracted,train
18,18,S7,Opensmallbox,train,1,Event_1,0,2,S7_Opensmallbox_1_extracted,train
19,19,S7,Opensmallbox,train,1,Event_2,0,2,S7_Opensmallbox_1_extracted,train
20,20,S7,Opensmallbox,train,1,Event_3,0,2,S7_Opensmallbox_1_extracted,train
21,21,S7,Opensmallbox,train,1,Event_4,0,2,S7_Opensmallbox_1_extracted,train
22,22,S7,Opensmallbox,train,1,Event_5,0,2,S7_Opensmallbox_1_extracted,train
23,23,S7,Opensmallbox,train,1,Event_6,0,2,S7_Opensmallbox_1_extracted,train
24,24,S7,Plugin,train,1,Event_0,0,3,S7_Plugin_1_extracted,train
25,25,S7,Plugin,train,1,Event_1,0,3,S7_Plugin_1_extracted,train
26,26,S7,Plugin,train,1,Event_2,0,3,S7_Plugin_1_extracted,train
27,27,S7,Plugin,train,1,Event_4,0,3,S7_Plugin_1_extracted,train
28,28,S7,Plugin,train,1,Event_5,0,3,S7_Plugin_1_extracted,train
29,29,S7,Plugin,train,1,Event_6,0,3,S7_Plugin_1_extracted,train

S8: 29 training windows

,sample_index,subject,activity,train_or_test,activity_instance,event,window_id,label,original_folder,split
0,0,S8,PressByGrasp,train,1,Event_0,0,0,S8_PressByGrasp_1_extracted,train
1,1,S8,PressByGrasp,train,1,Event_1,0,0,S8_PressByGrasp_1_extracted,train
2,2,S8,PressByGrasp,train,1,Event_2,0,0,S8_PressByGrasp_1_extracted,train
3,3,S8,PressByGrasp,train,1,Event_3,0,0,S8_PressByGrasp_1_extracted,train
4,4,S8,PressByGrasp,train,1,Event_4,0,0,S8_PressByGrasp_1_extracted,train
5,5,S8,PressByGrasp,train,1,Event_5,0,0,S8_PressByGrasp_1_extracted,train
6,6,S8,PressByGrasp,train,1,Event_6,0,0,S8_PressByGrasp_1_extracted,train
7,7,S8,Pressfromtop,train,1,Event_0,0,1,S8_Pressfromtop_1_extracted,train
8,8,S8,Pressfromtop,train,1,Event_1,0,1,S8_Pressfromtop_1_extracted,train
9,9,S8,Pressfromtop,train,1,Event_2,0,1,S8_Pressfromtop_1_extracted,train
10,10,S8,Pressfromtop,train,1,Event_3,0,1,S8_Pressfromtop_1_extracted,train
11,11,S8,Pressfromtop,train,1,Event_4,0,1,S8_Pressfromtop_1_extracted,train
12,12,S8,Pressfromtop,train,1,Event_5,0,1,S8_Pressfromtop_1_extracted,train
13,13,S8,Pressfromtop,train,1,Event_6,0,1,S8_Pressfromtop_1_extracted,train
14,14,S8,PressSwitch,train,1,Event_0,0,2,S8_PressSwitch_1_extracted,train
15,15,S8,PressSwitch,train,1,Event_1,0,2,S8_PressSwitch_1_extracted,train
16,16,S8,PressSwitch,train,1,Event_2,0,2,S8_PressSwitch_1_extracted,train
17,17,S8,PressSwitch,train,1,Event_3,0,2,S8_PressSwitch_1_extracted,train
18,18,S8,PressSwitch,train,1,Event_4,0,2,S8_PressSwitch_1_extracted,train
19,19,S8,PressSwitch,train,1,Event_5,0,2,S8_PressSwitch_1_extracted,train
20,20,S8,PressSwitch,train,1,Event_6,0,2,S8_PressSwitch_1_extracted,train
21,21,S8,PressSwitch,train,1,Event_7,0,2,S8_PressSwitch_1_extracted,train
22,22,S8,PutFromBottle,train,1,Event_0,0,3,S8_PutFromBottle_1_extracted,train
23,23,S8,PutFromBottle,train,1,Event_1,0,3,S8_PutFromBottle_1_extracted,train
24,24,S8,PutFromBottle,train,1,Event_2,0,3,S8_PutFromBottle_1_extracted,train
25,25,S8,PutFromBottle,train,1,Event_3,0,3,S8_PutFromBottle_1_extracted,train
26,26,S8,PutFromBottle,train,1,Event_4,0,3,S8_PutFromBottle_1_extracted,train
27,27,S8,PutFromBottle,train,1,Event_5,0,3,S8_PutFromBottle_1_extracted,train
28,28,S8,PutFromBottle,train,1,Event_6,0,3,S8_PutFromBottle_1_extracted,train

Full first training window for each available subject:
S1 X_train[0]: shape=(128, 33); label=0 (Bending)
Source: S1_Bending_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,-0.983092,0.846939,-0.304455,0.031937,0.096782,0.255270,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.027881,1.368183,0.607517,-1.121737,0.321191,0.069640,-1.619237,0.298624,0.053753,-0.000157,-0.068372,0.114415,0.130073,0.028625,0.036250,0.378203,-0.662379,-0.451339
1,-1.025328,0.865048,-0.322492,-0.018140,0.078192,0.302241,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.027881,1.360469,0.607775,-1.017262,0.295311,0.079242,-1.614174,0.299376,0.054677,-0.054130,-0.059026,0.134895,0.268843,-0.088252,0.060959,0.380335,-0.668979,-0.444114
2,-1.024700,0.867587,-0.322492,-0.023417,0.084993,0.318109,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.027401,1.356480,0.608077,-0.982763,0.299408,0.085697,-1.605398,0.300784,0.056678,-0.100135,-0.052358,0.117834,0.305543,-0.071149,0.072106,0.387433,-0.668979,-0.452529
3,-1.040382,0.846262,-0.322492,-0.032530,0.122776,0.320013,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.026921,1.352490,0.608378,-0.988108,0.315131,0.089340,-1.596929,0.302429,0.059717,-0.093371,-0.064368,0.053025,0.289036,-0.002859,0.073359,0.397371,-0.667788,-0.440498
4,-1.046027,0.839154,-0.323033,-0.039246,0.152247,0.297163,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.026441,1.348500,0.608679,-0.990049,0.334295,0.072951,-1.590922,0.303793,0.062644,-0.069459,-0.062590,0.025757,0.279722,0.079630,0.016403,0.409449,-0.664180,-0.430078
5,-1.051045,0.834077,-0.326820,-0.033969,0.156025,0.264157,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.027881,1.346549,0.609153,-1.003174,0.329380,0.093808,-1.585853,0.304870,0.064839,-0.064549,-0.059472,-0.008349,0.256619,0.054280,0.072900,0.403059,-0.672581,-0.420864
6,-1.066100,0.835092,-0.326279,-0.034449,0.193808,0.229246,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.029321,1.344599,0.609626,-1.010947,0.331838,0.083381,-1.583108,0.305769,0.067251,-0.044933,-0.051025,-0.017417,0.242582,0.063324,0.035285,0.401643,-0.667770,-0.418059
7,-1.058572,0.829507,-0.313834,-0.028693,0.210432,0.207665,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.030761,1.342648,0.610100,-1.021151,0.340028,0.077586,-1.580364,0.306420,0.068713,-0.030209,-0.054582,-0.029936,0.225609,0.097562,0.014338,0.386732,-0.670169,-0.431284
8,-1.075927,0.827476,-0.310588,-0.030612,0.228568,0.185449,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.034362,1.341318,0.610681,-0.977414,0.340192,0.065004,-1.578371,0.306875,0.069708,-0.007536,-0.077278,-0.048104,0.285421,0.095997,-0.025619,0.375355,-0.671378,-0.438900
9,-1.075509,0.833569,-0.294355,-0.010945,0.215722,0.166407,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.037963,1.339988,0.611262,-0.957492,0.327579,0.085035,-1.576343,0.307234,0.070322,-0.017340,-0.085731,-0.059484,0.324208,0.053659,0.041251,0.388141,-0.667782,-0.448921
10,-1.047909,0.848801,-0.297061,-0.043083,0.279953,0.159425,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.038923,1.339545,0.611391,-0.939029,0.334132,0.090994,-1.574431,0.307776,0.071690,-0.012421,-0.083060,-0.061730,0.297139,0.121862,0.040514,0.381036,-0.678594,-0.448122
11,-1.022191,0.859971,-0.278123,-0.031571,0.273908,0.171485,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.039883,1.339102,0.611520,-0.965758,0.346416,0.089174,-1.572453,0.308354,0.073175,0.011895,-0.087510,-0.070847,0.265244,0.165169,0.008261,0.386002,-0.684596,-0.442516
12,-1.021564,0.843216,-0.251068,0.009201,0.256528,0.183545,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.040843,1.338658,0.611650,-0.987625,0.356735,0.079407,-1.572132,0.308392,0.073200,0.020487,-0.118370,-0.084478,0.247904,0.122982,-0.083566,0.387418,-0.681586,-0.442520
13,-1.007137,0.851339,-0.240247,0.039899,0.208165,0.198144,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.039403,1.339190,0.611736,-1.006477,0.336948,0.053318,-1.574674,0.308071,0.072930,0.015413,-0.112789,-0.088103,0.245179,0.002323,-0.064846,0.384578,-0.671976,-0.443723
14,-0.977029,0.852355,-0.219144,0.037501,0.146957,0.201318,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.037963,1.339722,0.611822,-0.986000,0.322448,0.050935,-1.576220,0.307817,0.072535,-0.001592,-0.101165,-0.087495,0.274720,0.007881,-0.073057,0.384585,-0.677373,-0.445721
15,-0.963856,0.848293,-0.203994,0.006323,0.134867,0.193066,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.036523,1.340254,0.611908,-0.984318,0.319127,0.049345,-1.577962,0.307596,0.072346,0.006593,-0.104251,-0.102664,0.266901,0.002887,-0.070943,0.382453,-0.676177,-0.450531
16,-0.940648,0.859463,-0.195336,-0.044522,0.104640,0.179102,-1.100309,1.094825,1.600019,-0.112842,-0.105407,4.027981,-0.084330,-0.142445,-0.092665,-0.025000,1.345574,0.612037,-0.996368,0.319827,0.056895,-1.581023,0.307277,0.072284,0.006589,-0.107101,-0.115160,0.225471,0.022518,-0.059151,0.374640,-0.668374,-0.454139
17,-0.914303,0.880787,-0.200206,-0.087212,0.043432,0.157521,-1.100309,1.094825,1.600019,-0.112842,-0.105407,2.600037,-0.084330,-0.142445,-0.092665,-0.019719,1.347702,0.612037,-1.032520,0.323976,0.053848,-1.586031,0.306737,0.072114,0.003524,-0.103537,-0.104936,0.156833,0.071290,-0.083713,0.363263,-0.677978,-0.452537
18,-0.889839,0.858448,-0.194254,-0.122228,0.054011,0.137209,-1.100309,1.094825,1.600019,-0.112842,-0.105407,1.172094,-0.084330,-0.142445,-0.092665,-0.014438,1.349830,0.612037,-1.074120,0.335770,0.051101,-1.590786,0.306239,0.072013,-0.002608,-0.093299,-0.085612,0.135843,0.095619,-0.094610,0.361116,-0.669583,-0.452541
19,-0.874785,0.852863,-0.209405,-0.104480,0.050233,0.128958,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.009157,1.351958,0.612037,-1.100843,0.340028,0.040008,-1.595098,0.305786,0.071921,-0.014265,-0.090621,-0.076528,0.110542,0.077812,-0.072153,0.372478,-0.661170,-0.448534
20,-0.878130,0.880957,-0.256118,-0.090090,0.047966,0.112455,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,-0.001956,1.353819,0.611843,-1.119789,0.331183,0.053252,-1.601022,0.305278,0.072237,-0.028988,-0.083506,-0.093573,0.092481,0.031289,-0.082157,0.377458,-0.671982,-0.450527
21,-0.884821,0.888403,-0.288944,-0.077139,0.029830,0.082622,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.005246,1.355681,0.611650,-1.133886,0.322666,0.051431,-1.607057,0.304803,0.072728,-0.022848,-0.073714,-0.091294,0.103096,-0.004545,-0.058806,0.393092,-0.665389,-0.452129
22,-0.872903,0.892465,-0.296519,-0.042603,0.026808,0.066119,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.008606,1.355327,0.611305,-1.127568,0.320208,0.054079,-1.611412,0.304383,0.072788,-0.000772,-0.067479,-0.100394,0.129098,0.068323,-0.076180,0.394516,-0.654582,-0.452129
23,-0.820213,0.902112,-0.309505,-0.016701,0.066102,0.060406,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.011967,1.354972,0.610961,-1.099384,0.334786,0.049280,-1.614541,0.303922,0.072215,0.014557,-0.061697,-0.109462,0.196009,0.080878,-0.069088,0.390967,-0.656994,-0.455738
24,-0.812686,0.917851,-0.333854,-0.015262,0.060057,0.068023,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.015328,1.354617,0.610616,-1.062451,0.333476,0.051431,-1.615750,0.303466,0.070917,0.015778,-0.079057,-0.096976,0.263793,0.050653,-0.123758,0.388828,-0.655187,-0.452533
25,-0.810177,0.952377,-0.342512,-0.001352,0.048722,0.086430,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.018929,1.353022,0.609842,-1.016778,0.323977,0.030738,-1.615293,0.303195,0.069691,0.017017,-0.098195,-0.034478,0.293157,0.013111,-0.118152,0.394516,-0.668386,-0.450923
26,-0.823977,0.953392,-0.339265,-0.023417,0.030586,0.096586,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.022529,1.351426,0.609067,-1.001229,0.320536,0.034712,-1.613385,0.303098,0.068581,0.009655,-0.117773,0.005309,0.274975,-0.031397,-0.124697,0.405184,-0.675590,-0.459745
27,-0.845931,0.955423,-0.353333,-0.046441,0.010183,0.109916,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.025410,1.350096,0.608507,-1.013864,0.301045,0.034215,-1.612952,0.303069,0.068300,0.013327,-0.120450,-0.000389,0.244412,-0.092004,-0.066611,0.403775,-0.656976,-0.458542
28,-0.859104,0.970655,-0.370648,-0.069944,0.007916,0.132766,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.028290,1.348766,0.607948,-1.049336,0.299899,0.054411,-1.613745,0.303063,0.068586,0.018229,-0.119111,-0.021975,0.183163,0.010909,-0.016585,0.426513,-0.653978,-0.466158
29,-0.864121,0.962531,-0.386340,-0.073782,0.038898,0.137209,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.031171,1.347436,0.607388,-1.082862,0.323484,0.072620,-1.617316,0.302984,0.069660,0.023755,-0.141367,-0.056065,0.124144,0.074578,0.036417,0.423666,-0.637769,-0.469371
30,-0.879803,0.964562,-0.403654,-0.066107,0.056278,0.164503,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.035972,1.345663,0.607087,-1.133880,0.328562,0.088016,-1.624464,0.302556,0.070776,0.036633,-0.132914,-0.059467,0.053174,0.060650,0.039547,0.426499,-0.632958,-0.458546
31,-0.914930,0.976240,-0.419887,-0.082416,0.090283,0.184180,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.040773,1.343889,0.606785,-1.179075,0.330364,0.079739,-1.630908,0.302144,0.071685,-0.002002,-0.125793,-0.010596,0.039102,0.078325,0.018617,0.437146,-0.646755,-0.460145
32,-0.937511,0.945269,-0.402031,-0.053156,0.110686,0.205126,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.045574,1.342116,0.606484,-1.201425,0.331019,0.082883,-1.635360,0.302149,0.073443,-0.060877,-0.114662,0.037120,0.051580,-0.018388,0.001279,0.425075,-0.645553,-0.462155
33,-0.941275,0.934099,-0.412312,-0.015742,0.180206,0.221629,-1.100309,1.026352,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.054936,1.338924,0.606549,-1.176647,0.299407,0.079572,-1.637328,0.302660,0.076199,-0.112399,-0.085285,0.079186,0.090373,-0.126129,0.031977,0.416554,-0.653960,-0.468967
34,-0.972638,0.937653,-0.443154,0.023591,0.227057,0.236863,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.064298,1.335732,0.606613,-1.138902,0.311200,0.088566,-1.633701,0.303952,0.079821,-0.121588,-0.076832,0.116678,0.137673,0.074335,0.025837,0.413005,-0.649765,-0.476583
35,-1.001492,0.948315,-0.446941,0.045176,0.224790,0.231150,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.071499,1.333871,0.606915,-1.092778,0.357522,0.093312,-1.626777,0.305612,0.083612,-0.102979,-0.109470,0.088260,0.185000,0.209954,0.024478,0.393829,-0.651579,-0.482192
36,-1.018428,0.947807,-0.430168,0.034143,0.233102,0.236863,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.078700,1.332009,0.607216,-1.095011,0.354441,0.096127,-1.624097,0.306737,0.086994,-0.071085,-0.126088,0.033712,0.171756,0.133068,0.019518,0.389565,-0.664790,-0.483391
37,-1.020310,0.936637,-0.410688,0.007282,0.200609,0.224168,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.085902,1.330147,0.607517,-1.096953,0.341666,0.096457,-1.624548,0.307321,0.089487,-0.047998,-0.120004,-0.007193,0.174631,0.101817,0.001831,0.378196,-0.662391,-0.473774
38,-1.007764,0.943238,-0.385257,-0.028213,0.261817,0.205761,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.093823,1.327753,0.608098,-1.080431,0.338554,0.087021,-1.624638,0.307784,0.091369,-0.041867,-0.110205,-0.008333,0.204170,0.048544,-0.023215,0.375355,-0.661786,-0.478584
39,-1.006510,0.953392,-0.371730,-0.016222,0.274663,0.219725,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.101745,1.325359,0.608679,-1.063913,0.328397,0.083380,-1.623761,0.308288,0.093031,-0.055360,-0.106648,0.000751,0.233408,0.004417,-0.042773,0.400219,-0.667782,-0.480191
40,-0.997101,0.932576,-0.347381,0.003445,0.286754,0.212743,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.105106,1.324295,0.608938,-1.041073,0.317097,0.085035,-1.621550,0.309037,0.095144,-0.085412,-0.100420,0.021198,0.262234,-0.013732,-0.007572,0.398094,-0.658777,-0.476179
41,-1.008392,0.886372,-0.324656,0.030306,0.318492,0.236228,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.108466,1.323231,0.609196,-1.030869,0.322829,0.109370,-1.618837,0.310116,0.098392,-0.105643,-0.100420,0.023494,0.243363,-0.011460,0.049157,0.420840,-0.653966,-0.476978
42,-0.959465,0.887896,-0.387422,0.055728,0.350229,0.241941,-1.100309,0.957879,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.111827,1.322167,0.609454,-1.042042,0.321191,0.110031,-1.616614,0.311195,0.101851,-0.106258,-0.103537,0.030315,0.222344,0.013379,0.011566,0.431501,-0.655175,-0.474169
43,-0.970756,0.896527,-0.386881,0.060045,0.317736,0.250192,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.116148,1.321369,0.609454,-1.061481,0.327252,0.110362,-1.614300,0.312220,0.105077,-0.103799,-0.097308,0.035980,0.195262,0.036610,0.009959,0.412318,-0.658184,-0.472167
44,-0.967620,0.897542,-0.398244,0.043737,0.278442,0.231785,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.116628,1.321281,0.609411,-1.056136,0.338717,0.105728,-1.610291,0.313346,0.108044,-0.103807,-0.082168,0.062125,0.225315,0.053605,-0.005491,0.432202,-0.656988,-0.471372
45,-0.952566,0.884849,-0.389045,0.123361,0.273152,0.213378,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.117108,1.321192,0.609368,-1.042046,0.330529,0.114667,-1.605279,0.314673,0.111444,-0.122826,-0.089289,0.079186,0.204073,0.008021,0.016981,0.428631,-0.667800,-0.473782
46,-0.923084,0.868602,-0.415558,0.185718,0.261062,0.224803,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.117588,1.321103,0.609325,-1.060023,0.329873,0.119300,-1.601142,0.316008,0.115257,-0.132630,-0.093299,0.083745,0.188177,0.024628,0.007408,0.418671,-0.669589,-0.479795
47,-0.908657,0.878249,-0.422592,0.194352,0.246704,0.214647,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.119028,1.321103,0.609153,-1.063426,0.335113,0.122778,-1.596450,0.317443,0.119283,-0.141204,-0.093299,0.103052,0.185626,0.073761,0.019022,0.417255,-0.656969,-0.487815
48,-0.914930,0.882818,-0.428544,0.200587,0.237636,0.215917,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.120469,1.321103,0.608981,-1.067799,0.350510,0.127247,-1.591648,0.318905,0.123408,-0.140606,-0.090181,0.089426,0.152316,0.078151,0.020137,0.386703,-0.654558,-0.498235
49,-0.913198,0.887340,-0.419990,0.198852,0.216406,0.181097,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.121909,1.321103,0.608809,-1.092091,0.344123,0.135689,-1.587401,0.320325,0.127619,-0.143672,-0.079057,0.105331,0.122536,0.051718,0.010117,0.377473,-0.641352,-0.503845
50,-0.911465,0.891861,-0.411436,0.197116,0.195175,0.146277,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.124790,1.320970,0.608615,-1.094522,0.348054,0.124763,-1.582067,0.321744,0.131402,-0.153485,-0.059032,0.122376,0.135443,0.085849,-0.001073,0.370141,-0.649155,-0.508252
51,-0.909733,0.896382,-0.402881,0.195380,0.173945,0.111457,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.127670,1.320837,0.608421,-1.094039,0.351985,0.140656,-1.576169,0.323424,0.136089,-0.175569,-0.069717,0.139421,0.107155,0.085115,0.045747,0.361846,-0.665370,-0.503437
52,-0.888585,0.914297,-0.365778,0.227928,0.116731,0.067388,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.131031,1.320660,0.608378,-1.082859,0.361649,0.157541,-1.569516,0.325273,0.141235,-0.180462,-0.051465,0.143963,0.147865,0.136214,0.054006,0.366118,-0.666579,-0.509047
53,-0.872276,0.926991,-0.390668,0.204425,0.155269,0.100395,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.134391,1.320483,0.608335,-1.058078,0.366890,0.163664,-1.562633,0.327151,0.146455,-0.187218,-0.044784,0.113260,0.160271,0.119687,0.076946,0.374640,-0.680383,-0.512643
54,-0.896739,0.917344,-0.411771,0.187636,0.140912,0.118802,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.137752,1.320305,0.608292,-1.059054,0.364106,0.171281,-1.558083,0.328782,0.151640,-0.175561,-0.044344,0.068963,0.151635,0.069509,0.086325,0.381745,-0.662983,-0.515044
55,-0.887958,0.937145,-0.427462,0.169409,0.143935,0.122610,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.144954,1.319241,0.608163,-1.058564,0.352149,0.183696,-1.557146,0.330011,0.156661,-0.163306,-0.048348,-0.001528,0.149281,0.050052,0.085489,0.401643,-0.661786,-0.515444
56,-0.883567,0.938668,-0.439366,0.141589,0.162826,0.122610,-1.100309,1.094825,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.152155,1.318177,0.608034,-1.059537,0.353787,0.179888,-1.557521,0.330957,0.161027,-0.145023,-0.038735,-0.027191,0.194126,0.043072,0.021946,0.401635,-0.668386,-0.512639
57,-0.885448,0.935114,-0.465879,0.104654,0.140156,0.116263,-1.100309,1.060588,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.152875,1.317246,0.607775,-1.016289,0.351493,0.164659,-1.556283,0.331876,0.164595,-0.140589,-0.051019,-0.004931,0.224947,0.031591,-0.003231,0.381029,-0.655779,-0.514245
58,-0.900503,0.949838,-0.498885,0.062444,0.115220,0.104838,-1.100309,1.026352,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.153595,1.316316,0.607517,-1.000257,0.351493,0.164990,-1.552967,0.333009,0.168246,-0.137549,-0.079943,0.048499,0.214770,0.028929,0.067568,0.375348,-0.644985,-0.516646
59,-0.899248,0.955931,-0.515659,0.026948,0.104640,0.100395,-1.100309,0.992116,1.600019,-0.112842,-0.105407,-0.255850,-0.084330,-0.142445,-0.092665,0.154315,1.315385,0.607259,-1.016583,0.353852,0.192502,-1.549216,0.334389,0.172845,-0.137541,-0.099087,0.071242,0.180088,0.057681,0.079116,0.363979,-0.637182,-0.519052

S2 X_train[0]: shape=(128, 33); label=0 (CloseBigBox)
Source: S2_CloseBigBox_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0.052467,-0.496097,0.432882,-0.144661,0.037028,0.215149,-0.556322,0.345859,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.356461,0.225433,-0.058352,0.717538,-0.844824,-0.903031,0.739102,-0.841016,-0.901058,-0.039990,0.190960,0.059931,-0.058506,-0.137988,-0.158975,-0.794112,1.305686,0.424129
1,0.017653,-0.483785,0.379434,-0.236631,-0.041143,0.232340,-0.556322,0.185025,0.095250,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.357588,0.220537,-0.058466,0.722305,-0.838376,-0.905310,0.739532,-0.841541,-0.900953,-0.096286,0.256073,0.140751,-0.034545,-0.012693,-0.157603,-0.795507,1.306369,0.428402
2,0.018253,-0.615937,0.287715,-0.314134,-0.076220,0.217605,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.358714,0.215641,-0.058579,0.735811,-0.836764,-0.889365,0.741446,-0.841777,-0.900234,-0.115588,0.303958,0.165992,0.054079,0.018879,0.017545,-0.790859,1.290595,0.421477
3,0.048265,-0.711972,0.254063,-0.294500,-0.069205,0.193045,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.363218,0.213005,-0.058919,0.737004,-0.830316,-0.873874,0.744009,-0.841912,-0.899248,-0.097875,0.304905,0.178612,0.044828,0.129684,0.179041,-0.797365,1.272104,0.408146
4,0.051266,-0.782563,0.264621,-0.179279,-0.066198,0.165211,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.367723,0.210368,-0.059259,0.752826,-0.832958,-0.883947,0.746223,-0.842112,-0.898404,-0.096286,0.283850,0.163497,0.154538,0.092346,0.062134,-0.803872,1.280315,0.400158
5,0.048265,-0.775175,0.292994,-0.055273,-0.084238,0.151294,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.370726,0.210620,-0.059410,0.766994,-0.834211,-0.881011,0.748368,-0.842352,-0.897591,-0.089859,0.263727,0.153372,0.269667,0.075716,0.058736,-0.793190,1.277568,0.393232
6,0.076476,-0.675856,0.300253,0.004146,-0.057178,0.143107,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.373730,0.210871,-0.059561,0.770767,-0.837166,-0.891187,0.750486,-0.842710,-0.896800,-0.094696,0.243618,0.113016,0.219818,-0.012501,-0.015379,-0.789478,1.285793,0.401232
7,0.072275,-0.597058,0.329946,-0.002054,-0.032123,0.160299,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.376733,0.211121,-0.059712,0.761830,-0.839692,-0.899539,0.751984,-0.842899,-0.896232,-0.173496,0.244565,0.115475,0.152896,-0.012785,-0.170245,-0.788088,1.285103,0.412425
8,0.050066,-0.581462,0.351061,-0.044940,-0.046154,0.172579,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.377859,0.211121,-0.060392,0.762029,-0.836226,-0.889972,0.753641,-0.842424,-0.895523,-0.251221,0.249379,0.123045,0.148151,0.037193,-0.019835,-0.785293,1.259070,0.418282
9,0.032058,-0.614295,0.359639,-0.071291,-0.075218,0.164392,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.378985,0.211121,-0.061072,0.752097,-0.847644,-0.912295,0.754783,-0.841526,-0.894967,-0.310181,0.239791,0.100359,0.085446,-0.149749,-0.231375,-0.797370,1.264562,0.415614
10,0.036260,-0.660261,0.339183,-0.072324,-0.090251,0.145563,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.372228,0.207355,-0.062092,0.726873,-0.829735,-0.922622,0.754683,-0.839897,-0.894813,-0.437237,0.241712,0.118006,-0.104827,0.026830,-0.377674,-0.800619,1.262513,0.416140
11,0.039261,-0.652053,0.355680,-0.066124,-0.090251,0.140651,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.365471,0.203589,-0.063111,0.721114,-0.819838,-0.887997,0.754605,-0.837754,-0.894588,-0.470983,0.204361,0.256865,-0.175940,0.243722,0.009329,-0.809452,1.265935,0.409215
12,0.039261,-0.615116,0.364917,-0.086791,-0.106286,0.134102,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.358714,0.199823,-0.064131,0.779110,-0.825077,-0.861573,0.756617,-0.835873,-0.893566,-0.382554,0.247459,0.221535,0.251406,0.122299,0.293570,-0.811783,1.285807,0.406552
13,0.053667,-0.579821,0.358319,-0.129160,-0.116308,0.139833,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.352707,0.196308,-0.065340,0.811681,-0.837302,-0.870836,0.760137,-0.834957,-0.892059,-0.284429,0.279063,0.125564,0.471797,-0.103561,0.175704,-0.803881,1.284441,0.425208
14,0.056668,-0.549451,0.341163,-0.165328,-0.123323,0.149656,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.346701,0.192793,-0.066548,0.809299,-0.852345,-0.890579,0.763538,-0.834809,-0.890690,-0.311770,0.298211,0.168487,0.424046,-0.364153,-0.052014,-0.811320,1.278955,0.420419
15,0.066272,-0.575717,0.331925,-0.183412,-0.111297,0.150475,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.340695,0.189279,-0.067757,0.796190,-0.876257,-0.853979,0.766952,-0.835220,-0.889379,-0.350376,0.269488,0.332586,0.299398,-0.764745,0.342829,-0.810383,1.287187,0.415625
16,0.052467,-0.627428,0.348421,-0.191679,-0.108290,0.134102,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.332811,0.191161,-0.067474,0.788048,-0.871017,-0.839400,0.769779,-0.835974,-0.888341,-0.339089,0.211068,0.491622,0.218871,-0.662135,0.484374,-0.814559,1.285821,0.430018
17,0.054267,-0.628249,0.322027,-0.200980,-0.111297,0.114454,-0.556322,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.324928,0.193045,-0.067191,0.746337,-0.844824,-0.844716,0.770207,-0.836115,-0.888187,-0.339089,0.123926,0.607808,-0.099471,-0.212417,0.410075,-0.806189,1.278962,0.414025
18,0.071074,-0.619220,0.278478,-0.218547,-0.099271,0.112817,-0.556322,-0.083030,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.314417,0.186266,-0.065755,0.712375,-0.821182,-0.850336,0.768688,-0.835830,-0.888760,-0.306956,0.080814,0.754187,-0.341558,0.184391,0.340744,-0.801536,1.283082,0.422013
19,0.076476,-0.646307,0.259342,-0.210797,-0.088246,0.116092,-0.556322,-0.190252,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.303906,0.179487,-0.064320,0.719723,-0.850331,-0.881163,0.767077,-0.836717,-0.889511,-0.324646,0.127739,0.865274,-0.269649,-0.300098,-0.001548,-0.795029,1.281709,0.439596
20,0.059669,-0.691452,0.246805,-0.173078,-0.102277,0.127553,-0.556322,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.293395,0.172708,-0.062885,0.742365,-0.880019,-0.928394,0.767018,-0.838350,-0.889731,-0.456517,0.265647,0.885416,-0.097334,-0.774471,-0.516861,-0.793176,1.300890,0.432133
21,0.057869,-0.733313,0.244166,-0.104875,-0.103279,0.134921,-0.348603,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.276127,0.159903,-0.061752,0.771960,-0.834615,-0.875848,0.770393,-0.837955,-0.888334,-0.477409,0.393968,0.860212,0.104797,-0.006158,0.065678,-0.806657,1.305686,0.437464
22,0.059069,-0.700481,0.240866,-0.061474,-0.094260,0.138195,-0.140884,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.258858,0.147098,-0.060619,0.749913,-0.806137,-0.880555,0.775324,-0.837043,-0.886246,-0.343389,0.497086,0.799642,-0.098399,0.460498,-0.009365,-0.802472,1.299517,0.433207
23,0.059669,-0.670111,0.259342,-0.054757,-0.080229,0.133283,0.066835,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.241590,0.134294,-0.059485,0.723099,-0.779136,-0.891794,0.780709,-0.836099,-0.883962,-0.273165,0.588349,0.905666,-0.339577,0.901154,-0.158272,-0.809911,1.305686,0.423619
24,0.051266,-0.651232,0.302232,-0.072324,-0.103279,0.143107,0.066835,-0.297475,-0.816732,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.160505,0.081569,-0.056539,0.733825,-0.778330,-0.916092,0.786984,-0.835863,-0.881392,-0.257110,0.658263,1.196003,-0.306469,0.906746,-0.448989,-0.824782,1.300207,0.415088
25,0.050666,-0.665186,0.290355,-0.095575,-0.124326,0.131646,0.378414,-0.297475,-0.634336,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.107574,0.061232,-0.057106,0.805128,-0.777255,-0.921407,0.794263,-0.835418,-0.878373,-0.287677,0.632421,1.062207,0.169950,0.918938,-0.524815,-0.824319,1.307742,0.401758
26,0.068673,-0.643024,0.271879,-0.106426,-0.107288,0.122641,0.689992,-0.297475,-0.451939,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.054643,0.040895,-0.057673,0.797382,-0.785047,-0.880860,0.800274,-0.833401,-0.875663,-0.424338,0.548158,0.504242,0.058594,0.758413,-0.090375,-0.839195,1.311840,0.398553
27,0.092683,-0.629070,0.248785,-0.096608,-0.067200,0.142288,0.689992,-0.297475,-0.573537,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.008094,0.023320,-0.058428,0.882588,-0.793644,-0.783818,0.805108,-0.830368,-0.873297,-0.379307,0.438973,-0.540884,0.661212,0.568738,0.963754,-0.856852,1.319361,0.385754
28,0.086080,-0.636457,0.232288,-0.060957,-0.013082,0.163573,0.689992,-0.297475,-0.695135,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.038455,0.005745,-0.059183,0.845050,-0.821316,-0.737955,0.804347,-0.826745,-0.873153,0.001794,0.101910,-1.851108,0.372278,0.042364,1.462091,-0.856857,1.328255,0.385754
29,0.083079,-0.634816,0.214473,-0.044423,0.038031,0.182402,0.689992,-0.297475,-0.816732,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.085004,-0.011830,-0.059939,0.816846,-0.877064,-0.732943,0.796307,-0.823688,-0.876063,0.362025,-0.319456,-2.747323,0.208721,-0.951215,1.537158,-0.860578,1.334423,0.393758
30,0.100486,-0.650411,0.242846,-0.038739,0.085134,0.215967,0.689992,-0.297475,-0.573537,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.103774,-0.024885,-0.060770,0.979315,-0.929989,-0.808876,0.784452,-0.820778,-0.880517,0.524416,-0.510983,-3.398620,1.521178,-1.893020,0.735835,-0.860578,1.341289,0.377765
31,0.093283,-0.722643,0.279137,-0.037189,0.077116,0.251988,0.689992,-0.297475,-0.330342,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.122544,-0.037941,-0.061601,1.124502,-0.901780,-0.862485,0.772186,-0.819223,-0.885262,0.892664,-0.526305,-3.731880,2.703302,-1.451573,0.192632,-0.843380,1.322804,0.390559
32,0.085480,-0.772713,0.321368,-0.034606,0.043042,0.260175,0.689992,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.141314,-0.050997,-0.062432,0.992025,-0.964108,-0.889819,0.753957,-0.820535,-0.892687,1.285074,-0.947643,-3.711702,1.820984,-2.493960,-0.034757,-0.831289,1.311164,0.394290
33,0.094483,-0.777638,0.323347,-0.044423,0.030013,0.222516,0.378414,-0.297475,-0.269543,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.151450,-0.050997,-0.061922,0.852598,-1.029663,-0.839551,0.727296,-0.821236,-0.903189,1.047062,-1.457098,-3.802575,0.952880,-3.582784,0.637828,-0.814091,1.289236,0.399610
34,0.077677,-0.720181,0.332585,-0.062507,0.027006,0.188133,0.066835,-0.297475,-0.451939,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.161585,-0.050997,-0.061412,0.734421,-1.014080,-0.791107,0.703298,-0.819577,-0.912156,0.762958,-1.379864,-4.178722,0.269775,-3.341508,1.291272,-0.802009,1.255654,0.407604
35,0.035060,-0.637278,0.315429,-0.094542,0.015982,0.168485,-0.140884,-0.083030,-0.330342,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.145068,-0.050495,-0.062658,0.621607,-0.910645,-0.900146,0.683802,-0.816784,-0.919107,0.657899,-1.015637,-4.234265,-0.411319,-1.642120,0.162480,-0.806667,1.237839,0.405473
36,0.024856,-0.650411,0.287056,-0.102809,0.031015,0.157843,-0.348603,0.131414,-0.208744,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.128550,-0.049993,-0.063905,0.521108,-0.830585,-1.016020,0.666208,-0.814096,-0.925254,0.555006,-0.690042,-3.446605,-1.039770,-0.331815,-1.060608,-0.795053,1.212482,0.431602
37,0.013451,-0.692273,0.283756,-0.068707,0.016984,0.157024,-0.556322,0.345859,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.112033,-0.049490,-0.065151,0.455565,-0.815271,-1.032878,0.652927,-0.812170,-0.929841,0.302505,-0.465018,-2.244974,-1.436970,-0.104331,-1.195212,-0.797843,1.196730,0.448137
38,0.017052,-0.723464,0.298933,-0.033056,-0.003060,0.148838,-0.348603,0.238637,0.034451,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.100020,-0.040452,-0.066284,0.432525,-0.806674,-1.013895,0.645462,-0.810564,-0.932324,-0.044850,-0.131769,-1.025623,-1.576573,-0.170785,-1.031155,-0.790873,1.194680,0.487065
39,-0.024964,-0.750551,0.283097,-0.012905,-0.012079,0.131646,-0.140884,0.131414,0.156049,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.088008,-0.031413,-0.067417,0.447620,-0.730778,-0.956944,0.644236,-0.807927,-0.932414,-0.419524,0.198627,-0.207660,-1.414609,1.029189,-0.402843,-0.764841,1.170013,0.510526
40,-0.054376,-0.745626,0.250764,0.003629,0.018989,0.120185,0.066835,0.024192,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.075995,-0.022375,-0.068550,0.512965,-0.696255,-0.954060,0.648166,-0.805166,-0.930626,-0.578713,0.460988,0.476471,-1.214569,1.748590,-0.342891,-0.774597,1.158373,0.509452
41,-0.053176,-0.660261,0.268580,0.027913,-0.028114,0.056330,0.066835,-0.136641,0.095250,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.081626,-0.029530,-0.067077,0.648619,-0.735210,-0.897870,0.655990,-0.803012,-0.927499,-0.705747,0.621886,1.125308,-0.196308,1.309291,0.072784,-0.779704,1.146036,0.505184
42,-0.142011,-0.652873,0.209854,0.010863,-0.158400,-0.053370,0.066835,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.087257,-0.036686,-0.065604,0.713368,-0.775241,-0.857321,0.664849,-0.801384,-0.924043,-0.728274,0.619019,1.324736,0.328349,0.540491,0.681378,-0.788069,1.142600,0.491849
43,-0.138410,-0.494456,0.135951,-0.014972,-0.303719,-0.020623,0.066835,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.085004,-0.042963,-0.065453,0.772555,-0.770137,-0.879797,0.672781,-0.800122,-0.920953,-0.606055,0.563480,1.047056,0.703510,0.326748,0.504900,-0.798756,1.165211,0.493980
44,0.075276,-0.198962,0.108238,-0.076974,-0.251605,0.100537,0.066835,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.082752,-0.049239,-0.065302,0.840879,-0.733195,-0.921256,0.680504,-0.798698,-0.917897,-0.503138,0.565387,0.691050,1.142258,0.983047,0.023391,-0.793639,1.166577,0.495580
45,0.197125,-0.099643,0.143869,-0.146211,-0.100273,0.158662,0.066835,-0.297475,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.080500,-0.055516,-0.065151,0.856569,-0.778330,-0.888301,0.686113,-0.797199,-0.915599,-0.431287,0.448565,0.409199,1.409310,0.643051,0.106598,-0.800151,1.169999,0.493448
46,0.175441,-0.223124,0.229113,-0.216529,-0.114685,0.229845,0.066835,0.024192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.074869,-0.044218,-0.066511,0.847036,-0.833272,-0.851093,0.687638,-0.795369,-0.914770,-0.356802,0.238831,-0.109230,1.247517,-0.561617,0.607936,-0.797356,1.157676,0.490254
47,0.153757,-0.346606,0.314357,-0.286848,-0.129098,0.301029,0.066835,0.345859,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.069238,-0.032920,-0.067870,0.836708,-0.865913,-0.851701,0.685927,-0.793323,-0.915118,-0.253862,0.051144,-0.669654,1.211574,-1.069696,0.691769,-0.804326,1.152881,0.478518
48,0.132074,-0.470088,0.399601,-0.357167,-0.143511,0.372213,-0.244743,0.506692,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.082752,-0.001285,-0.068210,0.846442,-0.882302,-0.874785,0.681232,-0.791505,-0.916606,-0.102735,-0.099192,-1.098813,1.261199,-1.560755,0.510228,-0.814095,1.143980,0.451858
49,0.110390,-0.593569,0.484844,-0.563695,-0.369864,0.253625,-0.556322,0.667525,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.096266,0.030350,-0.068550,0.808969,-0.889019,-0.893667,0.672647,-0.789695,-0.919524,0.032337,-0.303174,-1.586047,1.135185,-1.690375,0.259861,-0.815027,1.135072,0.456115
50,0.102287,-1.017316,0.321368,-0.658765,-0.242585,-0.002613,-0.556322,0.828359,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.093451,0.053135,-0.068720,0.737599,-0.870078,-0.921864,0.660281,-0.787865,-0.923797,0.161006,-0.524384,-1.949610,0.609361,-1.417256,-0.029377,-0.825255,1.134382,0.454510
51,0.285960,-0.652873,0.324667,-0.538894,-0.063191,0.006392,-0.556322,0.989192,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.090636,0.075920,-0.068890,0.664509,-0.874377,-0.936746,0.647230,-0.785739,-0.928226,0.152967,-0.553094,-2.093459,0.154938,-1.523252,-0.144577,-0.826191,1.115187,0.465709
52,0.349586,-0.652053,0.283097,-0.285716,0.132237,0.155387,-0.556322,1.150025,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.087820,0.098704,-0.069060,0.630147,-0.836226,-0.934165,0.634448,-0.783208,-0.932443,0.096672,-0.519597,-2.065724,-0.010027,-0.917455,-0.068160,-0.818280,1.100794,0.500905
53,0.253547,-1.026345,0.290355,-0.111592,0.321653,0.222516,-0.556322,1.310858,-0.087147,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.085004,0.121489,-0.069230,0.590225,-0.831928,-0.939784,0.622319,-0.780468,-0.936345,0.003406,-0.502355,-1.841019,-0.218574,-0.888255,-0.085634,-0.805721,1.087774,0.532371
54,0.215132,-1.223341,0.347761,-0.010838,0.385794,0.208599,-1.179478,1.310858,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,-0.008424,0.200577,-0.070023,0.594992,-0.829913,-0.923078,0.612335,-0.777445,-0.939405,-0.165457,-0.388396,-1.469898,-0.104363,-0.902232,0.136597,-0.794098,1.089830,0.548364
55,0.210330,-1.389147,0.361618,0.012413,0.382787,0.028496,-1.179478,1.203636,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.038125,0.216896,-0.070854,0.572350,-0.820511,-0.924293,0.604835,-0.775034,-0.941661,-0.242645,-0.306054,-1.081094,-0.209732,-0.788752,0.151360,-0.790381,1.090527,0.542507
56,0.288361,-1.367805,0.341163,-0.021689,0.427886,-0.226924,-1.179478,1.096414,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.084675,0.233216,-0.071685,0.521107,-0.763956,-0.912599,0.596191,-0.772648,-0.944293,-0.261947,-0.323283,-0.715072,-0.531919,0.128248,0.309473,-0.794571,1.079563,0.533971
57,0.373595,-1.041941,0.393951,-0.092992,0.389802,-0.378375,-1.179478,0.989192,0.277646,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.131224,0.249536,-0.072516,0.483966,-0.727286,-0.892098,0.587132,-0.770164,-0.947029,-0.289266,-0.310842,-0.457533,-0.749409,0.712750,0.563778,-0.803409,1.072035,0.521704
58,0.500246,-1.069849,0.407807,-0.130193,0.377776,-0.517546,-1.179478,0.828359,0.460043,-0.124362,-0.121314,-0.211751,-0.113068,-0.131642,-0.117793,0.198795,0.256691,-0.073026,0.475026,-0.724599,-0.881317,0.583155,-0.769248,-0.948249,-0.213691,-0.103992,-0.046093,-0.733747,0.845928,0.593422,-0.802487,1.065874,0.519046

S3 X_train[0]: shape=(128, 33); label=0 (closeotherlid)
Source: S3_closeotherlid_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0.421416,0.132456,-1.597413,-0.300437,-0.455572,0.711021,-0.065642,-0.426718,-0.464899,-0.13871,-0.140875,3.957002,-0.115554,-0.075805,-0.115969,0.256517,-0.387172,0.097949,0.914338,-0.686043,-0.703462,0.932890,-0.699745,-0.706574,0.235684,-0.634620,-0.857741,-0.123954,0.115751,-0.467209,-1.170755,0.813854,0.203561
1,0.661580,0.411804,-1.581357,-0.327727,-0.381273,0.924825,-0.065642,-0.426718,-0.464899,-0.13871,-0.140875,1.848155,-0.115554,-0.075805,-0.115969,0.255546,-0.377152,0.093841,0.924172,-0.679399,-0.699328,0.928465,-0.698589,-0.709941,0.162495,-0.500358,-0.817571,-0.002290,0.302274,-0.355352,-1.164569,0.823254,0.210938
2,0.736501,0.399307,-1.584763,-0.071496,-0.508642,0.135460,-0.065642,-0.426718,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.254574,-0.367132,0.089732,0.918692,-0.682041,-0.688792,0.925932,-0.697417,-0.712180,0.141577,-0.302243,-0.689546,-0.020180,0.226275,-0.220102,-1.171378,0.819837,0.218306
3,0.980683,0.584310,-1.636161,0.074230,-0.509428,-0.655662,-0.065642,-0.426718,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.242914,-0.339708,0.085167,0.932602,-0.689469,-0.693549,0.924954,-0.696535,-0.713309,0.071858,-0.121044,-0.533866,0.091458,0.001983,-0.246746,-1.171372,0.807015,0.221747
4,0.991189,0.511776,-1.614796,0.188364,-0.429233,-0.865077,-0.065642,-0.392378,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.234979,-0.328897,0.085000,0.926806,-0.679922,-0.687656,0.925222,-0.695554,-0.713758,-0.003053,-0.027205,-0.466078,0.061037,0.217786,-0.186273,-1.167655,0.795041,0.219290
5,0.981638,0.462061,-1.568353,0.319034,-0.370266,-1.032345,-0.065642,-0.358038,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.227044,-0.318085,0.084832,0.930354,-0.669408,-0.679987,0.925910,-0.694177,-0.714202,-0.058843,-0.015480,-0.425908,0.088383,0.442266,-0.114426,-1.173212,0.780933,0.231068
6,0.966357,0.529706,-1.520980,0.478338,-0.355327,-1.187760,-0.065642,-0.323699,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.219109,-0.307274,0.084665,0.931021,-0.657461,-0.674484,0.926717,-0.692572,-0.714712,-0.034430,-0.003717,-0.413321,0.089780,0.708521,-0.040508,-1.159586,0.788628,0.236472
7,1.023662,0.577790,-1.524231,0.576743,-0.308940,-1.258882,-0.065642,-0.289359,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.211174,-0.296463,0.084497,0.948055,-0.659521,-0.671316,0.928212,-0.691001,-0.714788,-0.015259,0.083587,-0.252679,0.184635,0.764837,0.016294,-1.134198,0.801880,0.239414
8,1.035123,0.687814,-1.532591,0.579163,-0.283781,-1.262394,-0.065642,-0.255019,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.203239,-0.285652,0.084330,0.953499,-0.665798,-0.679320,0.930333,-0.689963,-0.714162,-0.001330,0.146172,-0.016660,0.274795,0.528906,-0.082432,-1.129247,0.809150,0.240393
9,1.016021,0.685369,-1.516801,0.559805,-0.278277,-1.324735,-0.065642,-0.220679,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.195304,-0.274840,0.084163,0.950513,-0.675508,-0.664980,0.932416,-0.689513,-0.713195,0.010876,0.178733,0.136503,0.227613,0.238262,-0.021276,-1.121826,0.814706,0.231063
10,0.997875,0.747308,-1.484754,0.519071,-0.290070,-1.307613,-0.065642,-0.117660,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.160811,-0.264029,0.087221,0.943664,-0.680412,-0.659477,0.934329,-0.689589,-0.712007,0.000417,0.164413,0.196704,0.176670,0.045550,0.127354,-1.112547,0.806159,0.226637
11,0.950121,0.825547,-1.484290,0.629710,-0.356900,-1.232540,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.126318,-0.253218,0.090280,0.942436,-0.675901,-0.655976,0.935835,-0.689782,-0.710986,-0.018754,0.131832,0.186670,0.108375,0.143138,0.109121,-1.129889,0.795476,0.217801
12,0.980683,0.795393,-1.549775,0.771941,-0.273560,-1.164052,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.111258,-0.249526,0.092106,0.947702,-0.674821,-0.664480,0.936882,-0.689676,-0.710424,-0.039672,0.067960,0.154053,0.131923,0.209731,0.068912,-1.124314,0.790776,0.214859
13,0.934839,0.796208,-1.568353,0.817917,-0.277098,-1.115321,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.096198,-0.245835,0.093932,0.945947,-0.679530,-0.666815,0.937407,-0.689620,-0.710144,0.005659,0.017120,0.143983,0.185970,0.085308,-0.016692,-1.126173,0.786507,0.222721
14,0.880400,0.865482,-1.599934,0.838082,-0.284174,-1.013906,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.081138,-0.242143,0.095758,0.954376,-0.678354,-0.665646,0.937362,-0.689820,-0.710048,0.052687,-0.027186,0.106331,0.163653,0.070743,0.002959,-1.152795,0.783089,0.218306
15,0.863208,0.907046,-1.598077,0.776781,-0.238179,-0.911174,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.066077,-0.238451,0.097584,0.946474,-0.678354,-0.667147,0.936998,-0.689963,-0.710179,0.057905,-0.053269,0.053610,0.050923,0.154645,-0.012870,-1.158987,0.784789,0.230583
16,0.788712,0.873632,-1.576713,0.694910,-0.242897,-0.799223,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.005836,-0.235287,0.104341,0.938573,-0.678353,-0.668648,0.936533,-0.689917,-0.710486,0.052687,-0.066301,-0.001591,0.056964,0.195208,-0.034540,-1.164556,0.783076,0.213401
17,0.747644,0.804358,-1.554884,0.706203,-0.265304,-0.667516,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.019426,-0.229486,0.107262,0.936113,-0.675018,-0.667313,0.935832,-0.689884,-0.710926,0.061399,-0.075413,-0.031728,0.027036,0.047017,-0.127875,-1.171977,0.784781,0.215848
18,0.780116,0.884227,-1.508441,0.761859,-0.195723,-0.587174,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.044689,-0.223685,0.110184,0.932601,-0.678647,-0.673316,0.935142,-0.690035,-0.711246,0.084090,-0.080622,-0.034245,0.080551,-0.002572,-0.062530,-1.160209,0.803159,0.230089
19,0.746689,0.985286,-1.500081,0.683215,-0.211054,-0.376443,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.055377,-0.216565,0.111325,0.938046,-0.682178,-0.677987,0.934833,-0.690201,-0.711330,0.082342,-0.049348,-0.014142,0.189573,-0.033740,-0.167870,-1.152776,0.807867,0.227636
20,0.795398,0.841847,-1.509369,0.601345,-0.281815,-0.202589,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.066065,-0.209446,0.112466,0.946298,-0.682080,-0.678318,0.935031,-0.690407,-0.711085,0.066616,-0.003736,0.048612,0.203747,0.019726,-0.004310,-1.163309,0.807011,0.257091
21,0.836466,0.713078,-1.467106,0.496890,-0.156804,-0.130150,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.076753,-0.202326,0.113608,0.950162,-0.682865,-0.671650,0.935207,-0.690676,-0.710814,0.068364,0.011892,0.038542,0.087758,-0.121301,-0.119803,-1.153406,0.814276,0.252681
22,0.742868,0.669884,-1.368645,0.196430,-0.209875,-0.003711,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.087441,-0.195206,0.114749,0.940854,-0.685905,-0.678652,0.934952,-0.690997,-0.710770,0.063122,-0.028512,0.015994,0.025953,-0.108534,-0.068165,-1.158981,0.798028,0.244824
23,0.736183,0.629949,-1.332884,0.221569,-0.288498,0.134582,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,1.848155,-0.115554,-0.075805,-0.115969,-0.106873,-0.171474,0.115845,0.934356,-0.686789,-0.673150,0.934772,-0.691251,-0.710721,0.073606,-0.021977,-0.019213,0.093349,-0.041002,-0.033507,-1.161457,0.801450,0.254149
24,0.803993,0.502811,-1.342637,0.602151,-0.195723,0.282094,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,3.957002,-0.115554,-0.075805,-0.115969,-0.126306,-0.147742,0.116940,0.937166,-0.685513,-0.668815,0.935064,-0.691365,-0.710476,0.084090,0.018426,-0.019177,0.152890,0.081558,-0.132122,-1.157740,0.806585,0.236967
25,0.867029,0.421312,-1.368181,0.935681,-0.113169,0.426972,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,1.848155,-0.115554,-0.075805,-0.115969,-0.142824,-0.119792,0.116119,0.940504,-0.681001,-0.678319,0.935708,-0.691449,-0.710039,0.066616,0.056235,0.028509,0.134488,0.082428,-0.113781,-1.152788,0.789489,0.242361
26,0.888040,0.359372,-1.343566,1.303895,-0.060098,0.549460,0.629770,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.159341,-0.091840,0.115297,0.945246,-0.681590,-0.677653,0.936344,-0.691581,-0.709577,0.049193,0.065346,0.083747,0.050634,0.097668,-0.006097,-1.152782,0.792907,0.246287
27,0.902367,0.351222,-1.289691,1.837060,0.059015,0.781264,0.455917,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.162742,-0.080502,0.114293,0.938783,-0.680080,-0.669581,0.936712,-0.691722,-0.709270,0.019563,0.044510,0.093780,0.058638,0.022829,0.033815,-1.144738,0.791189,0.251692
28,0.866074,0.162144,-1.217239,2.492424,0.109727,0.952484,0.282064,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.166143,-0.069163,0.113288,0.937518,-0.683061,-0.663314,0.936700,-0.691826,-0.709213,0.002164,0.002780,0.118882,0.057984,0.082544,-0.013610,-1.121832,0.792046,0.272810
29,0.890906,-0.092133,-1.140607,3.191346,0.263042,1.077606,0.108211,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.169544,-0.057825,0.112284,0.935646,-0.683061,-0.668869,0.936549,-0.691856,-0.709285,0.000417,-0.006350,0.126470,0.068817,0.091543,-0.051346,-1.108206,0.811280,0.278215
30,0.955851,-0.312180,-1.101595,3.713218,0.489476,1.049948,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.172944,-0.046486,0.111279,0.939063,-0.679687,-0.669049,0.936396,-0.691804,-0.709408,-0.015284,0.002799,0.141466,0.085884,0.090390,-0.088914,-1.100162,0.820263,0.271337
31,1.113439,-0.361895,-1.137356,3.838645,0.997773,0.789167,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.163228,-0.022227,0.106349,0.939626,-0.680707,-0.674207,0.936483,-0.691721,-0.709407,-0.046661,0.021022,0.171674,0.186170,0.068986,-0.126375,-1.102631,0.815993,0.252676
32,1.125855,-0.370860,-1.032394,3.773713,1.475408,0.607411,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.154483,-0.016426,0.105345,0.946124,-0.681197,-0.675818,0.936534,-0.691632,-0.709432,-0.044889,0.024943,0.201738,0.117049,0.108270,-0.123475,-1.116868,0.815993,0.225658
33,1.153553,-0.224976,-0.820611,3.700715,1.914124,0.545508,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.145739,-0.010624,0.104341,0.945806,-0.680550,-0.678387,0.936399,-0.691665,-0.709492,-0.022223,0.017101,0.211808,0.006251,0.157469,0.015037,-1.131729,0.806163,0.220254
34,1.210858,-0.035083,-0.663167,3.307497,2.345764,0.334777,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.141366,-0.006933,0.104980,0.932075,-0.678452,-0.665313,0.936180,-0.691715,-0.709592,-0.022223,0.010603,0.196775,0.023722,0.123185,-0.044200,-1.132346,0.803598,0.226642
35,1.214678,0.084720,-0.464853,2.759007,2.724333,0.175411,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.136994,-0.003241,0.105619,0.933480,-0.679628,-0.670482,0.935985,-0.691613,-0.709772,-0.023971,-0.012866,0.141502,0.163141,0.160756,-0.083368,-1.122443,0.805311,0.228600
36,1.131586,-0.037528,-0.215916,2.259316,3.061625,-0.139370,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.132622,0.000451,0.106258,0.947175,-0.678255,-0.674151,0.935645,-0.691597,-0.709986,0.010901,-0.049367,0.116436,0.154330,-0.005428,-0.125293,-1.110071,0.799324,0.239899
37,0.898546,-0.085613,0.097579,1.985878,2.962560,-0.176248,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.128249,0.004142,0.106897,0.946124,-0.683944,-0.678319,0.934895,-0.691711,-0.710365,0.005659,-0.072799,0.078712,0.056627,-0.041593,-0.070561,-1.110077,0.801033,0.236467
38,0.780116,0.190669,0.297750,1.626133,2.927180,-0.236833,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.126630,0.006252,0.107780,0.935762,-0.685317,-0.673985,0.934004,-0.691839,-0.710819,0.014371,-0.074124,0.066197,0.021488,-0.040985,-0.080903,-1.108219,0.792054,0.234504
39,0.708485,0.446577,0.399462,0.941328,2.943691,-0.394882,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.125010,0.008361,0.108662,0.931617,-0.685336,-0.675585,0.933083,-0.691924,-0.711318,0.019563,-0.062399,0.043577,0.010117,-0.060638,-0.150677,-1.113164,0.796324,0.236967
40,0.657866,0.632395,0.463090,0.012525,2.697208,-0.552931,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.123391,0.010471,0.109545,0.929440,-0.685023,-0.681542,0.932553,-0.691924,-0.711634,0.012623,-0.035028,0.028545,0.042350,-0.029812,-0.109305,-1.127395,0.812567,0.240413
41,0.558538,0.378932,0.618676,-0.468614,2.256134,-0.494979,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.121772,0.012580,0.110427,0.936464,-0.688554,-0.678153,0.932531,-0.691943,-0.711635,-0.000748,0.016254,0.005074,0.082902,-0.119830,-0.077222,-1.136057,0.808719,0.223226
42,0.486907,-0.295881,0.988367,-0.229456,2.002574,-0.451516,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.120152,0.014690,0.111310,0.932321,-0.684787,-0.673184,0.932793,-0.691894,-0.711510,-0.008295,0.031477,-0.001627,0.039490,-0.007909,-0.044036,-1.137708,0.808861,0.221343
43,0.421006,-0.273876,1.117944,0.248859,1.728967,-0.415955,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.118533,0.016799,0.112193,0.935763,-0.683846,-0.669481,0.933172,-0.691742,-0.711376,-0.011814,0.039300,0.003443,0.071333,0.004775,-0.004611,-1.139360,0.809003,0.219460
44,0.423872,-0.017153,1.102153,0.500923,1.355115,-0.448882,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.105902,0.024446,0.115662,0.931899,-0.679334,-0.668481,0.933640,-0.691600,-0.711184,0.007406,0.028863,0.025956,0.028889,0.132408,0.002825,-1.141011,0.809146,0.217577
45,0.362746,0.158885,1.154634,0.673939,0.754828,-0.396199,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.093270,0.032093,0.119132,0.931432,-0.679007,-0.669761,0.933856,-0.691507,-0.711112,0.012648,0.017120,0.048612,0.016001,0.108048,-0.004463,-1.142663,0.809288,0.215694
46,0.454434,0.172739,1.169961,0.985691,0.554340,-0.315857,-0.065642,0.397437,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.036916,0.055825,0.126253,0.932425,-0.680805,-0.667481,0.933910,-0.691459,-0.711109,0.000417,0.005413,0.053646,0.057194,0.125753,-0.013978,-1.144315,0.809430,0.213810
47,0.472963,0.285208,1.192718,0.896247,0.480696,-0.290394,-0.065642,0.191398,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,-0.006795,0.061626,0.131275,0.934850,-0.681335,-0.669983,0.933928,-0.691413,-0.711127,0.016118,0.004087,0.071160,0.052365,0.034469,-0.009223,-1.145966,0.809572,0.211927
48,0.491491,0.397677,1.215476,0.806804,0.407053,-0.264931,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.023325,0.067427,0.136297,0.931021,-0.680511,-0.670817,0.933953,-0.691467,-0.711078,0.021310,0.028845,0.093780,0.020916,0.090251,-0.031433,-1.158975,0.802306,0.206523
49,0.510020,0.510146,1.238233,0.717361,0.333410,-0.239467,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.036928,0.068746,0.139492,0.935879,-0.681491,-0.675540,0.934183,-0.691549,-0.710891,0.021335,0.051007,0.088745,0.073621,0.066384,-0.079089,-1.159592,0.788202,0.194735
50,0.528548,0.622615,1.260990,-0.099190,-0.431592,-0.269760,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.050531,0.070065,0.142688,0.930634,-0.679530,-0.672250,0.934426,-0.691580,-0.710726,0.005659,0.045798,0.086264,-0.005868,0.133058,-0.051762,-1.153406,0.793337,0.205044
51,0.572864,0.384637,1.357129,-0.086688,-0.474048,-0.238150,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.064134,0.071383,0.145883,0.937518,-0.679235,-0.670315,0.934817,-0.691539,-0.710517,0.017866,0.044510,0.086264,0.079085,0.128454,-0.034367,-1.152788,0.791628,0.203571
52,0.634944,0.249349,1.274459,0.072617,-0.450461,-0.246053,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.077737,0.072701,0.149079,0.935411,-0.677961,-0.669648,0.935183,-0.691489,-0.710329,0.023083,0.045798,0.081193,0.055308,0.163548,-0.030640,-1.145361,0.789063,0.195225
53,0.704665,0.305583,1.112835,0.224258,-0.328989,-0.344833,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.087453,0.075865,0.154648,0.945772,-0.681394,-0.675485,0.935635,-0.691506,-0.710048,0.030022,0.021022,0.053610,0.145930,0.072603,-0.118728,-1.134217,0.783933,0.207497
54,0.787757,0.373227,0.976756,0.341215,-0.106093,-0.359321,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.097169,0.079030,0.160218,0.949283,-0.681296,-0.680154,0.935966,-0.691433,-0.709894,0.028275,0.009297,0.013477,0.222100,0.072214,-0.113188,-1.131735,0.784359,0.214859
55,0.825960,0.471841,0.896408,0.344442,0.265401,-0.375126,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.097169,0.081667,0.161816,0.951918,-0.681884,-0.678319,0.936309,-0.691387,-0.709717,0.054410,-0.011540,-0.004109,0.187437,0.022957,-0.151012,-1.115634,0.781802,0.229589
56,0.761015,0.656029,0.856467,0.239583,0.417536,-0.398833,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.097169,0.084304,0.163413,0.948405,-0.683846,-0.675819,0.936340,-0.691412,-0.709683,0.044001,-0.028493,0.000890,0.147291,-0.007786,-0.085852,-1.106348,0.793772,0.240388
57,0.673147,0.649509,0.875509,0.160939,0.478862,-0.456784,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.097169,0.086941,0.165011,0.939976,-0.683061,-0.666981,0.936299,-0.691468,-0.709673,0.030022,-0.015480,0.010995,0.097539,0.042433,0.005588,-1.100773,0.804885,0.237931
58,0.652136,0.515036,0.946103,0.203286,0.603872,-0.533175,-0.065642,-0.014641,-0.464899,-0.13871,-0.140875,-0.260693,-0.115554,-0.075805,-0.115969,0.097169,0.089577,0.166609,0.939978,-0.680216,-0.672151,0.936313,-0.691409,-0.709701,0.024805,-0.007657,0.013477,0.070615,0.109754,-0.060652,-1.105731,0.801033,0.234504

S4 X_train[0]: shape=(128, 33); label=0 (DryOffHandByShake)
Source: S4_DryOffHandByShake_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,-0.426638,-0.266091,-0.657827,0.029620,-0.195188,-0.237747,0.541978,-0.146894,-0.749161,3.056437,3.153650,-0.212656,-0.089229,-0.095939,-0.109451,-0.662184,-0.265198,-0.825025,-0.380836,0.838796,0.463821,-0.195983,0.846665,0.442287,0.584464,-0.437297,-0.112394,-1.364893,0.050465,0.237913,0.727532,-0.710720,-0.125310
1,-0.382373,-0.229743,-0.658185,0.017072,-0.221616,-0.203442,0.267935,-0.146894,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.625400,-0.155481,-0.820586,-0.292597,0.826093,0.446594,-0.201936,0.844272,0.431758,0.603541,-0.324993,-0.172893,-0.851770,-0.054688,0.186408,0.733000,-0.717560,-0.109895
2,-0.358939,-0.222287,-0.669287,0.000503,-0.249555,-0.152716,0.267935,-0.092568,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.626763,-0.132640,-0.819649,-0.203207,0.817252,0.438908,-0.206877,0.841601,0.419504,0.674550,-0.132285,-0.182042,-0.209121,-0.121408,0.193407,0.731506,-0.712293,-0.112177
3,-0.341828,-0.225083,-0.691850,-0.013975,-0.263902,-0.102284,0.267935,-0.038243,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.628125,-0.109800,-0.818711,-0.182300,0.811523,0.456797,-0.211479,0.838699,0.406238,0.721106,-0.099779,-0.186274,0.075141,-0.142267,0.395814,0.733501,-0.703344,-0.110470
4,-0.338853,-0.234403,-0.705101,-0.023145,-0.277871,-0.057716,0.267935,0.016083,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.629487,-0.086959,-0.817773,-0.203398,0.801311,0.442486,-0.216557,0.835667,0.392973,0.731234,-0.199803,-0.181337,-0.026063,-0.244710,0.461654,0.722560,-0.702825,-0.099620
5,-0.347780,-0.243102,-0.731246,-0.031831,-0.284289,-0.015787,0.404957,0.097571,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.645836,-0.055757,-0.816059,-0.229869,0.801934,0.413862,-0.221633,0.832616,0.380040,0.713345,-0.209006,-0.169376,-0.110525,-0.192512,0.355918,0.722565,-0.693356,-0.082497
6,-0.345920,-0.249626,-0.756316,-0.031188,-0.266167,0.016759,0.541978,0.179059,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.662184,-0.024555,-0.814345,-0.258068,0.816130,0.403923,-0.225928,0.829572,0.367168,0.698422,-0.126782,-0.144759,-0.290400,-0.110608,0.275393,0.735511,-0.691777,-0.059089
7,-0.358567,-0.250868,-0.759897,-0.016549,-0.265789,0.050479,0.541978,0.233385,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.679350,-0.006881,-0.812939,-0.256916,0.833442,0.361782,-0.229065,0.826429,0.353669,0.731234,-0.073382,-0.111708,-0.316786,0.155647,0.264862,0.752928,-0.687564,-0.033968
8,-0.371958,-0.260809,-0.741990,-0.002393,-0.274473,0.077747,0.541978,0.287710,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.696516,0.010794,-0.811532,-0.233899,0.818870,0.287307,-0.232615,0.823042,0.339638,0.746148,-0.130457,-0.128566,-0.164362,0.122263,-0.246406,0.766852,-0.675468,-0.019697
9,-0.375306,-0.274479,-0.757390,-0.004645,-0.293350,0.110293,0.541978,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.713682,0.028468,-0.810126,-0.214332,0.801436,0.247817,-0.236009,0.819261,0.324216,0.809396,-0.066016,-0.136325,-0.015528,-0.074443,-0.633489,0.782284,-0.658623,-0.007122
10,-0.355219,-0.274168,-0.814693,-0.027166,-0.317890,0.147824,0.633326,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.729213,0.040704,-0.808836,-0.163884,0.794462,0.217735,-0.238048,0.814815,0.305848,0.965738,0.040135,-0.110993,0.277634,-0.072489,-0.471961,0.784269,-0.656520,0.010006
11,-0.332901,-0.283488,-0.863042,-0.069152,-0.335258,0.177732,0.724674,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.744744,0.052940,-0.807547,-0.183450,0.787986,0.144984,-0.241057,0.810172,0.287720,0.933516,-0.201033,-0.099738,0.305686,-0.148833,-1.098377,0.774816,-0.651253,0.013433
12,-0.310955,-0.287527,-0.907093,-0.112104,-0.359043,0.202948,0.816022,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.760275,0.065176,-0.806258,-0.193618,0.816131,0.162210,-0.245132,0.805761,0.271577,0.884003,-0.394339,-0.075816,0.169284,0.133152,-0.798404,0.766356,-0.645456,0.032270
13,-0.261110,-0.289390,-0.950428,-0.146208,-0.349604,0.219368,0.816022,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.777850,0.078636,-0.805555,-0.182107,0.806043,0.104564,-0.249004,0.801501,0.256436,0.816567,-0.372865,-0.069498,0.318400,0.201133,-1.069774,0.763368,-0.643877,0.052245
14,-0.229492,-0.284109,-0.979438,-0.185942,-0.322043,0.224939,0.816022,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.795425,0.092095,-0.804851,-0.206277,0.777651,0.090518,-0.252082,0.797927,0.243988,0.639952,-0.246435,-0.063865,0.206129,-0.057573,-1.186181,0.762366,-0.618629,0.063089
15,-0.222425,-0.285041,-1.015610,-0.211359,-0.271075,0.217902,0.816022,0.342036,-0.478065,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.803871,0.102972,-0.805262,-0.213182,0.768808,0.121924,-0.253932,0.795392,0.235202,0.430499,-0.099770,-0.052610,0.151599,-0.157829,-0.907827,0.762366,-0.614432,0.075646
16,-0.226703,-0.284653,-1.021734,-0.217371,-0.246346,0.212367,0.816022,0.342036,-0.613613,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.812318,0.113848,-0.805672,-0.242722,0.753739,0.133320,-0.254299,0.793872,0.229707,0.237781,0.061012,-0.032205,-0.004155,-0.267979,-0.702351,0.758391,-0.607603,0.083069
17,-0.230980,-0.284265,-1.027858,-0.223383,-0.221616,0.206833,0.816022,0.342036,-0.749161,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.820765,0.124725,-0.806082,-0.275907,0.731572,0.153728,-0.253299,0.793292,0.227180,0.061746,0.223016,-0.015327,-0.249696,-0.513194,-0.517526,0.766356,-0.618131,0.086502
18,-0.235258,-0.283876,-1.033983,-0.229396,-0.196887,0.201299,0.816022,0.260548,-0.545839,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.820356,0.149809,-0.807489,-0.325973,0.707663,0.178907,-0.250723,0.793709,0.227710,-0.130390,0.425534,-0.003366,-0.577891,-0.750238,-0.315893,0.775322,-0.623393,0.087077
19,-0.239536,-0.283488,-1.040107,-0.235408,-0.172158,0.195764,0.816022,0.179059,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.819947,0.174893,-0.808895,-0.374695,0.725595,0.185533,-0.247504,0.795337,0.232470,-0.389348,0.599193,-0.029404,-0.905240,-0.577410,-0.284365,0.782289,-0.611291,0.102504
20,-0.282685,-0.358979,-1.051424,-0.183689,-0.037752,0.177145,0.724674,0.233385,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.807414,0.195422,-0.810038,-0.390042,0.771049,0.219457,-0.245052,0.798019,0.241546,-0.611921,0.659952,-0.087787,-1.020864,-0.141309,-0.076473,0.796714,-0.619710,0.115648
21,-0.322486,-0.400297,-1.022415,-0.115804,0.038889,0.158380,0.633326,0.287710,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.794880,0.215952,-0.811180,-0.388699,0.791348,0.264249,-0.243575,0.801275,0.253368,-0.741997,0.715805,-0.142653,-1.023927,0.032593,0.187809,0.785256,-0.606040,0.117356
22,-0.355591,-0.405889,-1.002000,-0.085883,0.098164,0.133750,0.541978,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.782346,0.236481,-0.812323,-0.383329,0.777525,0.333821,-0.241511,0.804666,0.265747,-0.765271,0.856940,-0.145465,-0.999545,-0.139391,0.629958,0.775302,-0.605515,0.099658
23,-0.381133,-0.384350,-0.964993,-0.096661,0.141959,0.115571,0.541978,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.762455,0.261361,-0.813525,-0.359923,0.791722,0.322292,-0.238080,0.807919,0.277299,-0.737220,0.944087,-0.117331,-0.869662,-0.028439,0.450580,0.763859,-0.616033,0.075675
24,-0.397624,-0.362707,-0.908884,-0.109530,0.171408,0.096219,0.541978,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.742564,0.286241,-0.814726,-0.289911,0.828211,0.272200,-0.234807,0.811109,0.288934,-0.740801,0.813376,-0.105370,-0.448914,0.306029,-0.021476,0.751419,-0.607603,0.060260
25,-0.393533,-0.386628,-0.876651,-0.102291,0.191795,0.075988,0.541978,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.722674,0.311121,-0.815927,-0.222390,0.868684,0.290355,-0.232737,0.814014,0.300151,-0.663474,0.682170,-0.141378,-0.039327,0.680158,0.030616,0.735496,-0.618640,0.061404
26,-0.396508,-0.400297,-0.860893,-0.072370,0.220111,0.051651,0.404957,0.342036,-0.139196,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.689568,0.353335,-0.817861,-0.203015,0.941909,0.303341,-0.232159,0.816100,0.308759,-0.483821,0.577107,-0.175707,0.075875,1.387060,0.055006,0.724043,-0.624945,0.057972
27,-0.400228,-0.410860,-0.852536,-0.024914,0.213693,0.036991,0.267935,0.342036,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.656462,0.395550,-0.819795,-0.219128,0.930576,0.311028,-0.232556,0.817271,0.313968,-0.324903,0.543973,-0.188370,-0.025134,1.250997,0.063281,0.713588,-0.623896,0.064820
28,-0.395021,-0.385385,-0.835107,0.017072,0.219734,0.027901,0.130913,0.423524,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.625809,0.438172,-0.821729,-0.240230,0.845272,0.308774,-0.233451,0.817692,0.316184,-0.189459,0.621292,-0.220736,-0.153862,0.382178,0.019427,0.719066,-0.628638,0.047679
29,-0.392541,-0.385385,-0.867578,0.010959,0.260131,-0.002593,-0.006109,0.505012,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.595155,0.480794,-0.823663,-0.241572,0.767439,0.305726,-0.234820,0.817791,0.317218,-0.142920,0.580171,-0.227769,-0.155254,-0.401849,-0.014307,0.724048,-0.622322,0.028262
30,-0.399484,-0.422044,-0.866981,-0.033923,0.277120,-0.048333,-0.006109,0.586501,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.566137,0.515259,-0.826344,-0.240805,0.743901,0.297378,-0.235795,0.818036,0.318715,-0.164399,0.479532,-0.174303,-0.142858,-0.637183,-0.088146,0.730519,-0.630742,0.016279
31,-0.399484,-0.463983,-0.797860,-0.106956,0.278631,-0.109028,-0.006109,0.667989,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.537118,0.549724,-0.829025,-0.231981,0.770676,0.290885,-0.236689,0.818343,0.320456,-0.157826,0.395454,-0.157425,-0.082648,-0.368339,-0.151490,0.728028,-0.640730,0.005435
32,-0.396880,-0.492253,-0.727306,-0.161329,0.270702,-0.182037,-0.097457,0.667989,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.522132,0.564135,-0.831164,-0.215101,0.821361,0.290089,-0.238768,0.818536,0.322232,-0.141245,0.235415,-0.185843,0.032385,0.139545,-0.170524,0.728524,-0.643352,0.021420
33,-0.395021,-0.548794,-0.772074,-0.196398,0.316385,-0.297562,-0.188804,0.667989,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.507146,0.578547,-0.833303,-0.190549,0.826716,0.283994,-0.242076,0.818880,0.325245,-0.211741,0.137724,-0.210411,0.205249,0.190537,-0.234039,0.728023,-0.645980,0.023708
34,-0.417339,-0.638265,-0.909242,-0.205406,0.450413,-0.442701,-0.280152,0.667989,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.492160,0.592958,-0.835442,-0.148539,0.811771,0.272597,-0.245181,0.819683,0.330239,-0.325984,0.169144,-0.199345,0.491816,0.034534,-0.352017,0.723051,-0.636512,0.040262
35,-0.509960,-0.673681,-1.036740,-0.141221,0.458342,-0.552949,-0.280152,0.776640,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.483713,0.604514,-0.837112,-0.136454,0.823976,0.237878,-0.247322,0.821068,0.337474,-0.405861,0.188450,-0.155084,0.584487,0.146780,-0.663369,0.729521,-0.629147,0.051112
36,-0.524467,-0.650381,-1.019907,-0.076070,0.425873,-0.685773,-0.280152,0.885291,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.475266,0.616071,-0.838782,-0.160049,0.840166,0.232842,-0.247725,0.822399,0.343740,-0.345081,0.239339,-0.098065,0.443976,0.295397,-0.751341,0.725547,-0.636512,0.045414
37,-0.405064,-0.728668,-1.199336,-0.065935,0.584064,-0.846452,-0.280152,0.993942,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.466820,0.627627,-0.840452,-0.213566,0.836181,0.253250,-0.246309,0.823243,0.346954,-0.216903,0.313845,-0.023066,0.104907,0.242977,-0.630452,0.734007,-0.644412,0.049398
38,-0.392045,-0.755696,-1.353695,-0.070761,0.761133,-0.965789,-0.280152,0.912454,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.459054,0.651895,-0.841683,-0.260371,0.818994,0.291813,-0.244204,0.823860,0.348809,-0.165587,0.305248,0.023367,-0.201626,0.061365,-0.354362,0.742468,-0.654411,0.042550
39,-0.433706,-0.686107,-1.309644,-0.051940,0.801530,-1.035280,-0.280152,0.830965,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.451289,0.676163,-0.842914,-0.209538,0.798820,0.299631,-0.241600,0.824745,0.351689,-0.207963,0.223622,0.025483,0.103412,-0.148660,-0.310982,0.753419,-0.663879,0.027693
40,-0.387209,-0.548173,-1.118396,-0.017836,0.737348,-1.068706,-0.280152,0.722314,0.199673,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.442024,0.689895,-0.843295,-0.132425,0.811150,0.373047,-0.238934,0.825683,0.354815,-0.143510,0.184356,0.022661,0.575362,-0.032824,0.229972,0.747941,-0.662306,0.023697
41,-0.190807,-0.450314,-1.042112,0.016750,0.772837,-1.058150,-0.280152,0.613663,0.335221,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.432760,0.703627,-0.843675,-0.115355,0.802057,0.435463,-0.235850,0.826093,0.355275,-0.030741,0.205840,0.096532,0.520285,-0.389520,0.684700,0.739982,-0.674402,0.008293
42,-0.044994,-0.340961,-1.089029,0.027207,0.808704,-1.011236,-0.280152,0.505012,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.423496,0.717358,-0.844056,-0.123411,0.793838,0.438378,-0.234514,0.826276,0.355502,-0.052813,0.180379,0.119385,0.117785,-0.685377,0.153207,0.719572,-0.685969,0.014578
43,0.009687,-0.203958,-0.989824,0.063402,0.682981,-0.907147,-0.280152,0.423524,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.403469,0.719805,-0.844276,-0.131467,0.785619,0.441294,-0.233178,0.826459,0.355730,-0.074886,0.154918,0.142239,-0.118919,-0.333078,-0.104578,0.692687,-0.700180,0.019155
44,0.053951,-0.057015,-0.753092,0.108605,0.530453,-0.790742,-0.280152,0.342036,-0.342518,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.383442,0.722253,-0.844496,-0.176544,0.752619,0.397827,-0.231951,0.827177,0.358550,-0.184690,-0.107145,0.113400,-0.355623,0.019221,-0.362363,0.699153,-0.690712,0.019712
45,0.148805,0.054203,-0.680032,0.120509,0.415302,-0.652347,-0.280152,0.505012,-0.206970,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.374451,0.731634,-0.843939,-0.271496,0.817252,0.299763,-0.235846,0.828104,0.364855,-0.302826,-0.482092,-0.088482,-0.436175,0.722670,-0.828127,0.698657,-0.687040,0.017424
46,0.228779,0.151440,-0.720502,0.116327,0.371884,-0.504862,-0.280152,0.667989,-0.071422,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.365459,0.741015,-0.843382,-0.284924,0.888485,0.244106,-0.243383,0.828687,0.371391,-0.312373,-0.480870,-0.234107,0.167488,0.160572,-1.422390,0.704631,-0.690203,0.002572
47,0.219852,0.193069,-0.759181,0.120027,0.232570,-0.333041,-0.280152,0.830965,0.064126,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.356467,0.750396,-0.842826,-0.195726,0.833690,0.173474,-0.250066,0.829053,0.376567,-0.263450,-0.207784,-0.243952,0.343362,-0.320097,-1.240885,0.730519,-0.671261,-0.001430
48,0.183026,0.236562,-0.608762,0.129357,0.064563,-0.161513,-0.371500,0.830965,0.199673,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.353742,0.776227,-0.842181,-0.175394,0.786368,0.202893,-0.252882,0.829519,0.380324,-0.206168,0.037692,-0.110298,-0.045571,-0.222583,-0.493973,0.735163,-0.690028,-0.010172
49,0.228035,0.299316,-0.547161,0.125335,-0.073996,0.092701,-0.462848,0.830965,0.335221,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.351018,0.802059,-0.841536,-0.241763,0.796330,0.304137,-0.253133,0.830287,0.384298,-0.208553,0.053039,-0.009694,-0.441370,0.062041,0.133099,0.738979,-0.686515,-0.016259
50,0.273416,0.502800,-0.479114,0.014337,-0.279381,0.458921,-0.554196,0.830965,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.348293,0.827891,-0.840892,-0.305448,0.825221,0.389214,-0.253884,0.831046,0.388521,-0.179903,-0.101001,-0.002661,-0.692632,0.265532,0.619175,0.738478,-0.674938,-0.027678
51,0.301686,0.792959,-0.273541,-0.147334,-0.527805,0.872054,-0.554196,0.830965,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.338893,0.856238,-0.841595,-0.345538,0.846268,0.456400,-0.254993,0.831805,0.392982,-0.191245,-0.172184,-0.003366,-0.533198,0.329970,0.491764,0.727532,-0.675998,-0.030530
52,0.332559,0.886158,-0.176843,0.023829,-0.847208,1.187842,-0.554196,0.830965,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.329492,0.884584,-0.842298,-0.321370,0.853490,0.444076,-0.255374,0.832617,0.397366,-0.204373,-0.099761,0.010701,-0.299769,0.157477,0.230230,0.724048,-0.680724,-0.030530
53,0.328096,0.387544,-0.072266,0.930312,-1.202478,1.453490,-0.554196,0.830965,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.324179,0.909260,-0.843880,-0.285306,0.837177,0.414524,-0.255054,0.833327,0.400880,-0.172151,-0.019383,0.010711,-0.110127,-0.029458,0.024951,0.720565,-0.680194,-0.034526
54,0.340743,-0.443790,0.054516,2.070696,-1.040889,1.721191,-0.554196,0.830965,0.470769,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.318866,0.933936,-0.845463,-0.255191,0.819368,0.391864,-0.255164,0.833629,0.402517,-0.071313,0.008842,-0.022350,-0.001428,-0.129137,-0.000507,0.736984,-0.684401,-0.035670
55,0.435968,-0.849205,-0.287151,1.879587,-0.784158,2.117905,-0.554196,0.912454,0.572430,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.320501,0.945459,-0.845990,-0.237736,0.809904,0.391201,-0.256220,0.833534,0.402600,-0.001510,0.031556,-0.066677,-0.068242,-0.028747,-0.030180,0.735982,-0.698612,-0.028822
56,0.145457,-0.167921,-0.555040,1.535493,0.203499,2.434279,-0.554196,0.993942,0.674091,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.322135,0.956981,-0.846518,-0.248860,0.819867,0.388021,-0.258048,0.833330,0.402535,0.005661,0.020507,-0.097632,-0.107374,0.319597,0.089946,0.747095,-0.700901,-0.040247
57,-0.088886,0.098627,-2.259434,1.893099,-0.007171,1.820883,-0.554196,1.075430,0.775751,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.323770,0.968503,-0.847045,-0.256534,0.854362,0.403525,-0.259884,0.833084,0.402264,0.024157,0.028488,-0.099032,0.031197,0.423276,0.217437,0.759368,-0.701262,-0.042536
58,-1.729289,-2.766306,-1.455407,3.511097,0.211805,1.218336,-0.554196,1.156918,0.877412,-0.197297,-0.188241,-0.212656,-0.089229,-0.095939,-0.109451,-0.325405,0.980026,-0.847572,-0.236585,0.864575,0.419958,-0.260821,0.832878,0.401705,0.030729,0.065917,-0.063865,0.133512,0.145873,0.336292,0.771312,-0.680215,-0.036826

S5 X_train[0]: shape=(128, 33); label=0 (Hang)
Source: S5_Hang_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0.927134,-1.115420,-0.275478,-0.777966,-0.137850,0.185948,-0.799585,-0.051972,-0.517928,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.623643,-0.110805,-0.367857,1.733290,1.127610,1.299755,1.750544,1.204419,1.078418,-2.381997,2.612400,0.946620,0.165939,-0.773887,1.582962,-1.155289,-1.002862,-0.636967
1,0.828662,-1.650393,-0.231787,-1.187745,-0.205283,0.141111,-0.658231,-0.114680,-0.517928,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.615185,-0.103082,-0.366566,2.311355,1.179912,1.341554,1.813724,1.208596,1.127456,-2.361831,2.953731,1.139307,1.533855,-0.254861,1.556776,-1.195490,-1.019711,-0.696142
2,0.757046,-2.017503,-0.554694,-1.301121,-0.151170,-0.020087,-0.516877,-0.177388,-0.517928,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.606727,-0.095360,-0.365276,3.003247,1.192879,1.421866,1.896252,1.211709,1.177503,-2.378623,2.505747,1.409351,3.153717,-0.146339,1.740620,-1.198795,-1.019711,-0.757597
3,0.828214,-2.099246,-0.887158,-1.438900,-0.349307,-0.321132,-0.516877,-0.177388,-0.612668,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.611828,-0.096671,-0.364308,2.917028,1.165324,1.339225,1.981685,1.213781,1.227929,-2.440839,2.117165,1.426943,2.710286,-0.462566,1.011673,-1.197691,-1.012555,-0.796866
4,0.924000,-2.075161,-1.412820,-1.361621,-0.629031,-0.463114,-0.516877,-0.177388,-0.707408,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.616930,-0.097981,-0.363340,2.405646,1.065150,1.321133,2.056202,1.215061,1.279732,-2.495196,1.685169,1.286706,1.171352,-1.545228,0.636182,-1.222466,-1.019202,-0.837269
5,0.998749,-2.327686,-1.886598,-1.595999,-0.643184,-0.390522,-0.516877,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.622031,-0.099291,-0.362372,2.009792,1.033705,1.298795,2.109462,1.215686,1.329376,-2.378069,1.320225,1.055161,-0.008255,-1.879428,0.248430,-1.249449,-1.016146,-0.895309
6,1.048880,-2.707932,-2.124171,-1.889352,-0.593233,-0.504748,-0.658231,-0.177388,-0.660038,-0.108062,-0.11012,1.427404,-0.034151,-0.100872,-0.119457,0.645794,-0.103363,-0.361834,1.965623,1.149655,1.412958,2.148321,1.215726,1.377961,-2.387605,1.419275,0.952313,-0.222478,-0.629883,0.629626,-1.269821,-1.030449,-0.948788
7,0.991140,-2.638598,-2.319417,-1.652432,-0.416741,-0.280565,-0.799585,-0.177388,-0.517928,-0.108062,-0.11012,3.102237,-0.034151,-0.100872,-0.119457,0.669557,-0.107435,-0.361296,1.993226,1.195797,1.635117,2.184186,1.215021,1.429117,-2.449243,1.734683,0.976507,-0.239868,-0.125957,1.601103,-1.278089,-1.036582,-1.011366
8,0.859546,-2.582400,-2.225207,-1.389076,-0.005480,-0.141786,-0.799585,-0.219193,-0.423188,-0.108062,-0.11012,1.985682,-0.034151,-0.100872,-0.119457,0.681103,-0.108464,-0.361583,1.678074,1.206386,1.645531,2.216582,1.213513,1.481183,-2.393208,2.194115,0.917106,-1.154201,0.004481,1.384107,-1.273686,-1.045782,-1.072816
9,0.822843,-2.750993,-2.008115,-1.055558,0.315869,-0.110827,-0.799585,-0.260998,-0.328449,-0.108062,-0.11012,0.869126,-0.034151,-0.100872,-0.119457,0.692649,-0.109494,-0.361870,1.175189,1.153329,1.487650,2.232609,1.211534,1.532582,-2.398811,2.079841,0.688871,-2.523103,-0.540794,0.229939,-1.273131,-1.040673,-1.124031
10,0.861337,-2.444460,-2.080479,-0.496815,0.649705,-0.091612,-0.799585,-0.302803,-0.233709,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.704195,-0.110524,-0.362157,1.309690,1.143207,1.349914,2.224272,1.209946,1.572142,-2.033440,1.566311,0.281874,-1.977397,-0.516988,-0.829367,-1.290754,-1.030460,-1.158183
11,0.917286,-1.664260,-2.249101,-0.218206,0.915276,0.031155,-0.799585,-0.302803,-0.423188,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.709028,-0.111741,-0.362623,1.808726,1.240577,1.330179,2.199912,1.208660,1.604484,-1.772866,1.925930,0.136666,-0.577349,0.588046,-1.048080,-1.302320,-1.040168,-1.193469
12,0.863575,-1.476691,-2.133728,-0.337174,1.090104,0.010872,-0.799585,-0.302803,-0.612668,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.713861,-0.112957,-0.363089,2.080440,1.381231,1.360512,2.168844,1.207099,1.637902,-1.608117,2.847828,0.290666,0.035363,1.966924,-1.043888,-1.312784,-1.058557,-1.237287
13,0.842985,-1.692724,-2.056586,-0.383439,1.195000,0.045033,-0.799585,-0.302803,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.718694,-0.114174,-0.363555,1.893838,1.359834,1.439134,2.149416,1.205034,1.669775,-1.582343,3.324012,0.631117,-0.535034,1.650529,-0.505660,-1.319388,-1.080011,-1.285076
14,0.787931,-1.883942,-2.024499,-0.248710,1.343187,0.112288,-0.799585,-0.302803,-0.944257,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.724735,-0.115017,-0.365061,1.844572,1.364048,1.666364,2.146415,1.202276,1.701809,-1.446169,3.040580,0.744419,-0.550827,1.870621,0.406574,-1.314431,-1.091763,-1.335713
15,0.655441,-1.944519,-1.808773,0.083790,1.294069,0.080262,-0.799585,-0.302803,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.730777,-0.115859,-0.366566,1.902335,1.375070,1.604006,2.144436,1.199703,1.728655,-1.205775,2.338881,0.584920,-0.247823,1.930418,-0.476607,-1.327645,-1.085630,-1.386355
16,0.607996,-1.271606,-1.628546,0.219028,1.043483,-0.025424,-0.799585,-0.302803,-1.181107,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.729434,-0.116046,-0.367785,2.147407,1.341571,1.423375,2.131019,1.197772,1.749645,-1.158698,2.331264,0.341826,0.616217,1.381222,-1.397071,-1.355176,-1.085640,-1.435285
17,0.649175,-0.948286,-1.627864,-0.076867,0.762927,-0.265620,-0.799585,-0.302803,-1.275846,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.728092,-0.116233,-0.369004,2.659637,1.305804,1.461063,2.099733,1.196002,1.770984,-1.259562,2.367835,0.037670,1.999192,1.316683,-1.060933,-1.368938,-1.092277,-1.476822
18,0.766446,-1.151182,-1.833350,-0.395641,0.551469,-0.482330,-0.799585,-0.302803,-1.370586,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.726749,-0.116421,-0.370223,2.801924,1.305696,1.570428,2.049529,1.194196,1.793954,-1.246679,1.986881,-0.206518,2.207830,1.144469,-0.618521,-1.381054,-1.091768,-1.521769
19,0.801806,-1.420493,-1.961693,-0.391065,0.533154,-0.517558,-0.516877,-0.302803,-1.370586,-0.108062,-0.11012,3.102237,-0.034151,-0.100872,-0.119457,0.707417,-0.119510,-0.370761,2.751383,1.292079,1.568236,1.988599,1.192674,1.814135,-1.024763,1.829182,-0.287379,2.212089,1.148617,-0.975733,-1.381609,-1.105047,-1.567289
20,0.830005,-1.354808,-2.081845,-0.010266,0.508179,-0.215446,-0.516877,-0.260998,-1.275846,-0.108062,-0.11012,1.985682,-0.034151,-0.100872,-0.119457,0.705806,-0.121101,-0.370797,2.683000,1.316177,1.485868,1.924724,1.191773,1.828109,-0.745142,1.794118,-0.296722,2.279459,1.541812,-1.348383,-1.377206,-1.106061,-1.608832
21,0.827319,-1.020541,-2.154891,0.091417,0.591430,-0.057450,-0.516877,-0.219193,-1.181107,-0.108062,-0.11012,0.869126,-0.034151,-0.100872,-0.119457,0.704195,-0.122692,-0.370833,2.524997,1.394954,1.498477,1.859670,1.191886,1.833325,-0.232400,1.580783,-0.314330,1.843362,2.434394,-1.296821,-1.381620,-1.107604,-1.636153
22,0.709153,-1.089875,-1.932338,-0.037211,0.732124,0.129368,-0.516877,-0.177388,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.702584,-0.124283,-0.370869,2.348307,1.517963,1.523147,1.799724,1.193539,1.825673,0.339748,0.938508,-0.125122,1.797165,4.372172,-1.286679,-1.366759,-1.123950,-1.679972
23,0.637985,-1.263578,-1.765082,-0.077884,0.651370,0.074924,-0.516877,-0.240096,-1.228477,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.712250,-0.128074,-0.371944,2.355527,1.646089,1.400623,1.768486,1.196034,1.808678,0.634315,0.321621,0.161230,1.346648,4.492419,-1.717003,-1.360150,-1.138773,-1.708421
24,0.718105,-1.445308,-1.785562,-0.069241,0.451568,-0.004074,-0.516877,-0.302803,-1.370586,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.721916,-0.131865,-0.373020,1.852219,1.519441,1.643339,1.748951,1.199075,1.785293,1.187593,0.029553,-0.023921,0.167498,3.080382,0.210201,-1.350790,-1.155644,-1.722070
25,0.787483,-1.324154,-1.881137,0.064979,0.315036,-0.061721,-0.446199,-0.271450,-1.228477,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.731180,-0.134884,-0.374553,1.451266,1.385337,1.791491,1.701471,1.204206,1.742504,2.214193,-0.001670,-0.519467,-0.570252,1.375886,0.850536,-1.339777,-1.155644,-1.723778
26,0.801806,-1.157751,-1.844273,0.101076,0.216800,-0.124705,-0.375522,-0.240096,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.740443,-0.137903,-0.376085,1.164147,1.184883,1.839595,1.620787,1.210652,1.678790,2.985269,-0.442823,-0.932513,-1.202709,-0.781993,1.794697,-1.329846,-1.158201,-1.667445
27,0.817615,-1.219875,-1.843945,0.057394,0.163053,-0.162838,-0.304845,-0.208742,-0.944257,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.749707,-0.140921,-0.377618,0.833701,1.083304,1.950606,1.513468,1.216629,1.598214,3.816313,-0.610430,-1.235567,-1.647699,-1.562756,2.477652,-1.316627,-1.162801,-1.619651
28,0.833424,-1.281999,-1.843617,0.013711,0.109306,-0.200970,-0.234168,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.758970,-0.143940,-0.379150,0.662111,1.094651,1.827947,1.386925,1.220645,1.500032,4.435522,-0.262992,-1.356558,-1.883945,-1.109032,2.219803,-1.290742,-1.157681,-1.536008
29,0.849234,-1.344123,-1.843289,-0.029972,0.055559,-0.239102,-0.092814,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.772261,-0.148012,-0.383560,0.002922,1.206387,1.680617,1.255300,1.221033,1.390377,4.681527,0.261179,-1.242704,-3.813146,0.155148,1.999257,-1.263766,-1.167899,-1.433010
30,0.865043,-1.406247,-1.842962,-0.073654,0.001812,-0.277235,0.048541,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.785552,-0.152083,-0.387970,-0.979915,1.394846,1.495462,1.132236,1.217071,1.277544,4.568325,0.925553,-1.022158,-5.827489,2.308467,1.435069,-1.244508,-1.162790,-1.347660
31,0.880852,-1.468371,-1.842634,-0.117337,-0.051935,-0.315367,0.048541,-0.177388,-0.944257,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.782330,-0.156576,-0.392541,-1.213516,1.382311,1.232188,1.026503,1.209208,1.168953,4.135714,1.276026,-0.815910,-5.413925,1.577959,0.559596,-1.216428,-1.149495,-1.227024
32,0.831795,-1.840882,-1.840176,0.076673,-0.148672,-0.369171,0.048541,-0.177388,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.779108,-0.161069,-0.397112,-0.776890,1.360591,1.108431,0.935626,1.198764,1.072047,3.499135,0.985741,-0.790070,-4.060546,1.684657,0.625712,-1.188348,-1.137235,-1.135990
33,0.855965,-1.828475,-1.928242,0.341046,-0.358187,-0.403332,0.048541,-0.177388,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.779377,-0.162754,-0.400662,-0.085846,1.287108,1.167226,0.851123,1.187526,0.992842,2.663058,0.176611,-0.664667,-1.963803,0.845387,1.522641,-1.167421,-1.103514,-1.034138
34,0.774503,-1.983930,-1.745967,0.419342,-0.392598,-0.307254,0.048541,-0.177388,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.779645,-0.164439,-0.404211,0.800574,1.184559,1.406654,0.767577,1.177028,0.933352,2.258645,-1.147308,-0.716555,0.282074,-0.092531,2.999782,-1.132726,-1.083593,-0.957314
35,0.765103,-2.426214,-1.353427,0.499162,-0.273549,-0.229324,0.048541,-0.177388,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.779914,-0.166124,-0.407761,0.855506,1.100703,1.268598,0.662576,1.165333,0.879158,2.445637,-1.952898,-0.864872,0.394886,-0.925544,1.680148,-1.093073,-1.058567,-0.885619
36,0.812101,-2.489710,-1.314514,0.823020,-0.119534,-0.214378,0.048541,-0.177388,-0.991627,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.789311,-0.167060,-0.410736,0.447536,1.008461,0.896223,0.542268,1.151278,0.822682,2.454033,-2.313269,-0.901718,-0.285450,-1.720861,0.606487,-1.052878,-1.030969,-0.796843
37,0.728848,-2.753183,-1.128143,1.183991,0.121894,0.010872,0.048541,-0.177388,-0.896887,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.798709,-0.167996,-0.413712,-0.037005,0.962096,0.802261,0.422030,1.135810,0.767403,2.368861,-1.559754,-0.892367,-1.282404,-1.843188,0.518079,-1.000011,-1.023298,-0.725148
38,0.674688,-3.024684,-0.883744,1.591228,0.230120,0.443224,0.048541,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.808107,-0.168932,-0.416688,-0.259563,1.000746,0.871883,0.315899,1.119987,0.715162,2.177775,-1.255761,-0.726274,-1.403901,-1.199457,1.247092,-0.965876,-0.996204,-0.631833
39,0.717658,-2.748804,-0.739699,2.177426,0.275076,0.860630,0.048541,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.830661,-0.171740,-0.419914,-0.149131,1.023762,0.990706,0.215280,1.105367,0.672620,1.770930,-1.808143,-0.587659,-0.920147,-0.879304,2.228460,-0.921832,-0.953798,-0.553308
40,0.912810,-2.086108,-1.097423,2.656857,0.262588,1.296185,0.048541,-0.177388,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.853216,-0.174548,-0.423141,-0.209447,1.003015,1.079239,0.116513,1.092725,0.641536,1.411740,-2.359749,-0.375369,-0.826615,-1.092184,2.646543,-0.875027,-0.913441,-0.485016
41,0.961599,-1.691994,-1.315880,2.624319,0.467386,1.360237,0.048541,-0.219193,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.873623,-0.178573,-0.425328,-0.118979,0.972001,1.030587,0.024775,1.082393,0.620486,1.008828,-2.767365,-0.152625,-0.348502,-1.165326,2.446290,-0.823264,-0.877163,-0.436649
42,0.910573,-2.006556,-1.166373,1.952709,0.644710,1.226795,0.048541,-0.260998,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.894029,-0.182598,-0.427515,-0.161026,0.977187,1.002628,-0.052968,1.075033,0.609223,0.612643,-2.631755,0.131175,-0.414329,-1.044987,2.322060,-0.773153,-0.857241,-0.386573
43,1.023815,-2.397020,-1.040760,1.624275,0.466553,1.080542,0.048541,-0.302803,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,0.914436,-0.186623,-0.429702,-0.591706,0.956764,0.900526,-0.098459,1.070648,0.602844,0.285953,-1.723564,0.517271,-1.672635,-1.265238,1.711775,-0.739561,-0.856212,-0.340474
44,1.084241,-2.515985,-1.498155,1.455483,0.461558,0.964181,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,3.102237,-0.034151,-0.100872,-0.119457,0.974850,-0.202067,-0.436586,-0.874153,0.943148,0.820626,-0.098954,1.069487,0.598754,0.014166,-0.621093,0.958907,-1.960376,-1.297696,1.412974,-0.723586,-0.846509,-0.299516
45,0.980845,-2.580940,-1.440127,1.151453,0.489863,0.683419,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,1.985682,-0.034151,-0.100872,-0.119457,0.987201,-0.207215,-0.438558,-0.724652,0.953738,0.802124,-0.053596,1.070290,0.592195,0.011365,0.746519,1.237200,-1.654583,-1.169798,1.192484,-0.707622,-0.823012,-0.267078
46,0.801358,-2.789675,-1.033251,1.016724,0.632223,0.213704,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,0.869126,-0.034151,-0.100872,-0.119457,0.999552,-0.212363,-0.440529,-0.685147,0.960871,0.570373,0.025358,1.070794,0.578376,0.160422,1.602129,1.432450,-2.046851,-1.113214,-0.230817,-0.698257,-0.805122,-0.246587
47,0.650518,-2.510146,-0.921292,1.011640,0.680508,-0.337145,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.011904,-0.217512,-0.442501,-0.709103,0.977945,0.109992,0.128927,1.071172,0.560779,0.113353,1.592220,1.756947,-2.088185,-0.952073,-2.727474,-0.707622,-0.787753,-0.226680
48,0.729743,-1.978092,-1.275602,0.924193,0.532321,-0.942438,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.024389,-0.226497,-0.445782,-0.252769,0.904895,-0.269883,0.224071,1.073498,0.552761,-0.586549,0.189576,1.975847,-1.314253,-1.641759,-4.550826,-0.724141,-0.780092,-0.218716
49,0.822396,-1.635796,-1.524096,0.873352,0.473213,-1.264833,0.048541,-0.428219,-0.802148,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.036875,-0.235483,-0.449062,0.198726,0.845570,0.186905,0.303031,1.080140,0.563275,-1.351469,-1.479006,2.077041,-0.746411,-2.320006,-3.215064,-0.772599,-0.786734,-0.214733
50,0.680955,-1.468663,-1.074212,0.748283,0.569784,-1.443112,0.048541,-0.428219,-0.896887,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.048421,-0.245124,-0.450962,0.702458,0.838654,0.715372,0.376797,1.091144,0.591152,-1.498848,-2.822215,2.204090,0.377160,-2.700629,-0.268418,-0.812800,-0.782145,-0.212464
51,0.492068,-1.368675,-0.962252,0.469166,0.455730,-1.875463,0.048541,-0.428219,-0.991627,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.059966,-0.254765,-0.452863,0.427234,0.964545,0.798561,0.442554,1.102494,0.623471,-1.427675,-3.228313,2.297044,0.856158,-2.259998,1.246075,-0.846386,-0.792877,-0.240341
52,0.591882,-1.073819,-1.255121,0.419850,-0.031288,-2.065485,0.048541,-0.428219,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.071512,-0.264407,-0.454763,-0.305435,1.141225,0.643832,0.520379,1.113524,0.655134,-1.568898,-2.054229,2.520891,-1.415299,-0.506246,0.706472,-0.856844,-0.804623,-0.261961
53,0.689011,-0.936609,-1.294034,0.241398,-0.321834,-2.080430,0.048541,-0.470025,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.089234,-0.275264,-0.456484,-0.121526,1.288189,0.447986,0.635626,1.125064,0.686549,-1.775668,-0.269867,2.496138,-2.087564,1.113481,-0.619678,-0.854632,-0.824550,-0.279598
54,0.645594,-0.881141,-0.730142,0.293764,-0.251071,-2.028121,0.048541,-0.511830,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.106955,-0.286122,-0.458205,-0.059088,1.343193,0.473341,0.762319,1.135621,0.716022,-1.471389,-0.064903,2.143595,-2.029164,2.201459,-1.244693,-0.886571,-0.848058,-0.316592
55,0.582035,-0.745391,-0.550597,0.285121,-0.098722,-1.984352,0.048541,-0.553635,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,-0.119457,1.124677,-0.296980,-0.459926,-0.444325,1.260850,0.472518,0.855056,1.142152,0.734731,-0.731136,-1.047763,1.655202,-2.686979,1.833406,-1.104783,-0.915754,-0.853676,-0.325129
56,0.620529,-0.862895,-0.541040,0.038542,-0.211111,-1.879734,0.048541,-0.490927,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,3.892931,1.151662,-0.314671,-0.461646,-0.675801,1.274898,0.579143,0.894054,1.144319,0.740547,-0.221749,-3.014215,1.251514,-3.832871,1.152376,-1.107990,-0.967529,-0.848567,-0.352439
57,0.789273,-0.708169,-0.736969,0.166661,-0.233588,-1.585094,0.048541,-0.428219,-1.086367,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,7.905318,1.178647,-0.332362,-0.463367,-0.688972,1.576065,0.768410,0.879487,1.144098,0.741015,0.133524,-4.733827,0.973206,-4.234973,3.430230,0.317838,-1.018754,-0.837325,-0.361544
58,0.787483,-0.570959,-0.505541,0.329353,0.078603,-1.366249,0.048541,-0.511830,-1.181107,-0.108062,-0.11012,-0.247429,-0.034151,-0.100872,5.230393,1.181332,-0.345934,-0.461646,0.256486,1.831414,0.576403,0.831518,1.142432,0.738508,0.108866,-4.881638,0.687768,-2.137710,7.451180,-0.392253,-1.016547,-0.829150,-0.352422

S6 X_train[0]: shape=(128, 33); label=0 (OpenBigBox)
Source: S6_OpenBigBox_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,-1.487892,1.177012,0.191513,0.940159,2.361619,-1.087862,-0.730492,-0.342205,0.126286,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.011260,0.343963,0.390597,0.796706,1.690345,1.779439,0.716480,1.571402,1.729540,0.148991,0.182824,-1.284208,2.405558,1.250982,0.899722,-0.248717,-1.268001,-1.710220
1,-1.470775,1.308904,0.145471,1.290554,2.572993,-1.530317,-1.138256,0.265910,0.126286,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.007857,0.472305,0.394408,0.496212,1.628748,1.594522,0.705971,1.570816,1.722314,0.267613,-0.654028,-0.877003,-0.015484,0.914837,0.165442,-0.217645,-1.272433,-1.699837
2,-1.400232,1.612589,0.081011,1.421130,2.692230,-2.143342,-1.002334,0.367262,0.126286,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.018067,0.515329,0.395316,0.752866,1.644362,1.255818,0.700288,1.570547,1.713883,0.437480,-1.644793,-0.497165,-1.553287,0.392020,-1.372045,-0.221094,-1.275389,-1.705427
3,-1.362367,1.837582,0.037135,1.382615,2.789788,-2.806384,-0.866413,0.468615,0.126286,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.028276,0.558353,0.396224,1.081141,1.636913,1.416763,0.692643,1.570104,1.705979,0.449554,-2.456508,-0.899231,1.333508,0.615076,-3.228840,-0.193472,-1.269483,-1.702640
4,-1.389339,2.033757,-0.001865,1.267069,2.813273,-3.409150,-0.730492,0.569968,0.126286,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.038485,0.601377,0.397131,1.044951,1.637341,1.722001,0.679309,1.569208,1.700058,0.249104,-1.456629,-1.255126,2.494730,0.539929,-1.283889,-0.184494,-1.256174,-1.695856
5,-1.468700,2.159000,-0.012699,1.168432,2.804240,-3.808001,-0.628551,0.645982,0.338648,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.054934,0.631275,0.397539,0.965686,1.523745,1.821621,0.669619,1.568550,1.693126,0.172612,0.623072,-0.835954,2.364646,0.306209,0.546507,-0.178270,-1.246566,-1.683076
6,-1.564659,2.197791,0.019260,1.102674,2.695843,-3.968311,-0.526610,0.721996,0.551010,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.071382,0.661173,0.397948,0.582613,1.481345,1.744573,0.665949,1.568314,1.684342,0.059898,2.542796,-0.296989,1.640707,-0.761495,0.997318,-0.177582,-1.259131,-1.677478
7,-1.568809,2.250992,0.062594,1.072614,2.565767,-3.900339,-0.424669,0.798011,0.763372,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.087831,0.691070,0.398356,0.124863,1.553971,1.569928,0.664198,1.568191,1.675111,-0.075361,3.487210,0.009254,-1.606709,-1.001783,0.258474,-0.169292,-1.265782,-1.672685
8,-1.473887,2.253208,0.088595,1.092341,2.498922,-3.632301,-0.322728,0.874025,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.104279,0.720968,0.398765,0.231400,1.631469,1.353412,0.664844,1.568222,1.667581,-0.180014,2.940008,0.217982,-3.571746,0.070518,-0.920054,-0.157539,-1.269476,-1.674285
9,-1.355624,2.212200,0.103220,1.162796,2.479049,-3.216778,-0.322728,1.178083,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.183685,0.818683,0.399962,0.370560,1.572022,1.146548,0.655051,1.567458,1.661355,-0.092267,0.939378,-0.813701,-2.728145,0.354516,-2.677005,-0.141656,-1.273170,-1.663110
10,-1.269520,2.182275,0.096720,1.245463,2.428464,-2.725588,-0.220787,1.102068,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.200701,0.840195,0.400507,0.645056,1.687766,1.439801,0.638452,1.566183,1.661081,-0.158276,-1.759316,-1.275639,-1.182218,-0.053054,-3.228537,-0.120946,-1.265037,-1.649538
11,-1.220244,2.234366,0.081011,1.337524,2.314647,-2.257483,-0.118846,1.026054,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.217716,0.861707,0.401052,0.630271,1.983005,1.838743,0.623457,1.565016,1.664127,-0.017390,-3.182760,-1.169547,0.225226,1.829892,-0.736033,-0.102997,-1.278339,-1.639150
12,-1.135770,2.513826,0.021427,1.390130,2.161084,-1.950971,-0.016905,0.950040,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.234732,0.883219,0.401596,0.688639,1.753374,1.648844,0.616836,1.564413,1.654336,0.929402,-2.916437,-0.428741,-0.024943,4.010518,1.455247,-0.101620,-1.283154,-1.634751
13,-1.056854,2.722035,-0.046283,1.305047,1.539608,-1.190277,0.085036,0.874025,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.251748,0.904731,0.402140,0.640979,1.390381,1.498948,0.619919,1.564229,1.624014,1.843178,-1.430276,0.286431,0.614578,0.710815,-0.516645,-0.114041,-1.288699,-1.633150
14,-1.074490,2.786319,-0.067950,0.914795,0.699531,-0.267075,0.492801,-0.342205,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.283510,0.947026,0.405517,0.257990,1.293831,1.771190,0.624862,1.563352,1.578374,2.496883,0.730330,0.377108,-0.447687,-2.488910,-0.155566,-0.118867,-1.271695,-1.623966
15,-1.137771,2.770802,-0.102617,0.707188,0.276783,0.258742,0.628722,-0.747616,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.295988,0.954804,0.408348,0.061094,1.400637,1.732462,0.631632,1.561051,1.517789,3.105544,3.380850,0.378799,-3.159137,-2.449896,1.712243,-0.112657,-1.304227,-1.618774
16,-1.229580,2.756394,-0.163827,0.502400,-0.218231,0.810208,0.764643,-1.153026,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.308466,0.962582,0.411179,0.116962,1.522839,1.909826,0.637268,1.557289,1.456319,2.864824,4.808851,-0.131002,-3.810605,-1.318643,1.926443,-0.098171,-1.337497,-1.594814
17,-1.293899,2.698760,-0.240203,0.290096,-0.747570,1.369369,0.900565,-1.558436,0.975735,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.320945,0.970361,0.414011,0.148567,1.589881,2.112799,0.632815,1.551517,1.396547,2.937280,4.680683,-1.249980,-3.267047,-0.068327,4.179061,-0.069874,-1.372993,-1.554086
18,-1.363923,2.644452,-0.287329,0.057126,-1.215483,1.891338,0.900565,-1.659788,1.258884,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.341363,0.985917,0.417242,0.180423,1.620440,2.245468,0.606702,1.540452,1.319853,3.799788,3.306619,-2.965473,-2.933413,0.609199,6.197554,-0.054679,-1.404051,-1.510566
19,-1.386227,2.657752,-0.364248,-0.211542,-1.643652,2.283777,0.900565,-1.761141,1.542033,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.361782,1.001474,0.420472,0.036169,1.628031,2.001090,0.562319,1.525434,1.241970,3.698094,0.465804,-3.352705,-3.699147,0.615050,4.938071,-0.024289,-1.429195,-1.444676
20,-1.386227,2.604551,-0.417332,-0.490543,-1.941744,2.545403,0.900565,-1.862493,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.382201,1.017030,0.423703,0.366226,1.450689,1.915947,0.523588,1.512943,1.189258,3.151453,-2.243814,-2.214954,0.279826,-1.421210,5.060418,0.005412,-1.442512,-1.384773
21,-1.363923,2.521426,-0.422749,-0.723513,-2.133245,2.708278,0.900565,-1.862493,2.462269,-0.168854,-0.167354,5.351928,-0.086365,-0.065985,4.778812,-0.414530,1.051304,0.426807,0.874696,1.228366,1.740681,0.494989,1.503084,1.151353,2.701392,-2.741019,-1.167831,2.362502,-3.210901,3.406816,0.026136,-1.458041,-1.338849
22,-1.294418,2.413917,-0.396207,-0.848453,-2.113372,2.796769,0.900565,-1.862493,3.099355,-0.168854,-0.167354,10.889062,-0.086365,-0.065985,9.663492,-0.446860,1.085577,0.429911,0.679720,1.146141,1.379407,0.483269,1.495705,1.120404,1.828682,-1.193027,0.833924,1.090194,-3.706117,2.100861,0.058585,-1.472102,-1.296511
23,-1.224912,2.311950,-0.313330,-0.807119,-1.876705,2.837809,0.764643,-1.558436,3.382505,-0.168854,-0.167354,7.197639,-0.086365,-0.065985,6.407039,-0.471816,1.112072,0.430709,0.618295,1.078813,1.527900,0.507537,1.491660,1.089840,1.196680,1.158438,2.467849,0.529998,-4.308302,3.053353,0.068932,-1.468401,-1.268957
24,-1.180823,2.250992,-0.225578,-0.571331,-1.388919,2.858328,0.628722,-1.254378,3.665654,-0.168854,-0.167354,3.506216,-0.086365,-0.065985,3.150586,-0.496773,1.138567,0.431508,0.510738,1.133104,1.449140,0.553213,1.490755,1.065983,1.115368,1.685642,3.010220,-0.456650,-2.980067,2.537225,0.079294,-1.477279,-1.255377
25,-1.179785,2.193358,-0.171410,-0.256633,-0.772862,2.862175,0.492801,-0.950321,3.948803,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.521729,1.165061,0.432306,0.341505,1.504550,1.262199,0.589057,1.487698,1.038934,2.352794,-0.683713,2.689697,-1.480571,1.533029,1.355916,0.065483,-1.474329,-1.235402
26,-1.163187,2.104691,-0.169244,-0.169269,-0.185712,2.796769,0.492801,-0.342205,3.736441,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.569940,1.231420,0.433994,0.552282,2.041593,1.099385,0.592327,1.472583,0.977533,5.817251,-5.785299,0.793565,-0.072858,7.512290,-0.664042,0.033035,-1.487646,-1.217036
27,-1.045442,1.977232,-0.127535,-0.377815,0.302075,2.655696,0.492801,0.265910,3.524079,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.618151,1.297779,0.435682,0.544892,2.367343,0.443612,0.536131,1.437247,0.871828,7.968019,-6.601673,-2.949527,-2.226086,7.658908,-5.982040,0.001275,-1.508359,-1.185091
28,-0.951039,1.467396,0.160638,-0.443573,0.759149,2.513341,0.288919,0.874025,3.736441,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.678840,1.394400,0.439058,-0.573482,1.779303,-0.335751,0.437138,1.388163,0.755392,6.858876,-2.243801,-6.464884,-10.674873,-1.616230,-9.159443,-0.036709,-1.529071,-1.131184
29,-1.045442,0.926528,0.479144,-0.078147,1.250549,2.464607,0.085036,1.482140,3.948803,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.739528,1.491022,0.442434,-1.281774,0.788733,-0.622154,0.358605,1.343391,0.662267,4.068434,2.260107,-6.801958,-9.047967,-8.487896,-7.264423,-0.027732,-1.526107,-1.062905
30,-1.027807,0.802394,0.589104,0.348339,1.342687,2.254280,-0.118846,2.090256,3.524079,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.788307,1.599310,0.446845,-0.683846,0.396086,0.072063,0.317699,1.314369,0.605427,1.980040,3.310881,-5.238173,-3.159424,-8.852448,-0.494593,0.021296,-1.506139,-0.989422
31,-0.882053,0.695993,0.560396,0.756037,1.037368,2.027281,-0.322728,2.698371,3.099355,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.837085,1.707599,0.451255,0.566811,0.616546,0.742936,0.306998,1.293083,0.560641,2.268260,2.873659,-3.570011,5.452099,-4.645667,1.680302,0.103481,-1.488399,-0.923933
32,-0.671980,0.436642,0.543604,1.267069,0.356274,1.958027,-0.458649,2.901076,2.816206,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.860150,1.785625,0.455648,1.719850,1.220917,0.777958,0.296792,1.266420,0.506749,3.523384,0.583061,-3.137139,10.536489,0.962648,1.793151,0.176689,-1.445499,-0.864433
33,-0.464501,0.512009,0.525187,1.607131,-0.335661,1.945203,-0.594570,3.103781,2.533056,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.883216,1.863651,0.460040,1.868440,1.526754,0.604869,0.254561,1.230473,0.447213,4.421061,-2.513769,-3.263743,8.497448,2.662226,-0.116084,0.239527,-1.417405,-0.810522
34,-0.329120,0.973078,0.455310,1.640009,-0.743956,1.760525,-0.730492,3.306486,2.249907,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.906281,1.941677,0.464432,1.003661,1.325489,0.120317,0.181000,1.190344,0.393888,4.190005,-4.755268,-2.545141,4.693627,0.519810,-2.706916,0.287185,-1.405556,-0.760210
35,-0.180773,1.328854,0.374600,1.494403,-1.040241,1.387324,-0.730492,3.306486,2.108332,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.903635,2.003661,0.468171,0.999583,1.094284,-0.250763,0.112842,1.155239,0.352602,3.321320,-3.703609,-1.756423,5.920477,-1.256780,-3.794033,0.297533,-1.404074,-0.714680
36,-0.031388,1.559389,0.355100,1.226675,-1.202837,0.867920,-0.730492,3.306486,1.966758,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.900988,2.065645,0.471911,0.630019,0.874825,0.458711,0.067905,1.125807,0.316898,3.062875,-2.328340,-1.243118,1.905054,-3.599570,2.583411,0.338270,-1.386318,-0.675942
37,0.100880,1.655814,0.280890,0.940159,-1.141412,0.404945,-0.730492,3.306486,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.898341,2.127628,0.475649,-0.313771,0.470145,0.697640,0.016117,1.092891,0.280136,3.312463,-3.070957,-1.766667,-3.561889,-6.625302,1.458345,0.370044,-1.380397,-0.634007
38,0.130446,1.795465,0.251098,0.679946,-0.930038,0.080477,-0.934374,3.458515,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.880758,2.218780,0.479461,-0.913484,0.611391,-0.014947,-0.054830,1.056168,0.246538,3.142596,-3.232769,-3.167944,-5.613096,-3.732563,-1.662902,0.372103,-1.350092,-0.601260
39,0.100880,2.137941,0.154138,0.327672,-0.810801,-0.200386,-1.138256,3.610544,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.863175,2.309932,0.483273,-0.419797,0.893591,0.325470,-0.143005,1.016034,0.217242,3.479101,-4.213535,-4.069567,-0.132310,-0.614531,0.902262,0.393508,-1.316077,-0.562925
40,0.037599,2.330792,0.097261,0.134156,-0.825254,-0.381215,-1.274177,3.711897,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.849563,2.376048,0.486431,0.293080,1.183815,0.063659,-0.230882,0.974382,0.189496,3.134524,-3.271829,-4.076429,3.042933,2.273496,-1.456538,0.431485,-1.277624,-0.525385
41,-0.230049,2.202225,0.192597,0.029883,-0.704211,-0.473554,-1.410098,3.813249,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.835950,2.442163,0.489589,-0.039785,1.095000,-0.094330,-0.303812,0.937752,0.166607,2.599945,-3.100955,-3.407479,1.412013,0.673049,-1.538286,0.463252,-1.246559,-0.504618
42,-0.717107,1.723423,0.208847,0.272248,-0.543422,-0.342741,-1.546020,3.914602,1.825183,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.822338,2.508279,0.492747,-0.158978,0.908776,0.008038,-0.378859,0.903293,0.150148,2.417208,-3.284563,-3.650419,1.493835,-0.084258,-0.881768,0.521960,-1.211047,-0.479054
43,-1.007059,1.994965,0.072886,0.497703,-1.327494,-0.437645,-1.546020,3.914602,1.966758,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.808347,2.577797,0.495578,-0.549780,1.036698,-0.025065,-0.446568,0.873227,0.138693,2.232569,-2.998536,-3.773037,-0.184016,1.352359,-1.034277,0.564777,-1.165920,-0.463881
44,-0.947927,2.437192,-0.123743,0.440400,-2.328360,-0.826236,-1.546020,3.914602,2.108332,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.794357,2.647316,0.498410,-0.867351,1.088268,-0.141960,-0.503588,0.846328,0.128617,1.859276,-2.349249,-3.202132,-2.162388,2.427029,-1.772531,0.569624,-1.167388,-0.441921
45,-0.986830,2.376234,-0.174661,-0.171148,-2.602966,-1.405917,-1.546020,3.914602,2.249907,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.780366,2.716835,0.501241,-0.920110,0.948169,-0.091373,-0.553479,0.821846,0.119774,1.318251,-1.915660,-2.302200,-2.187197,1.247683,-1.355417,0.615203,-1.135578,-0.425948
46,-1.205202,2.498151,-0.205536,-0.790210,-2.312100,-1.673955,-1.546020,3.762573,2.674631,-0.168854,-0.167354,5.351928,-0.086365,-0.065985,4.778812,-0.765052,2.801059,0.503746,-0.596678,0.839061,-0.103307,-0.589549,0.804160,0.114095,0.957563,-1.449364,-1.446749,0.082868,0.416036,-1.495897,0.632456,-1.144456,-0.403585
47,-1.407494,2.958111,-0.217453,-1.398939,-1.883932,-1.971490,-1.546020,3.610544,3.099355,-0.168854,-0.167354,10.889062,-0.086365,-0.065985,9.663492,-0.749738,2.885284,0.506251,-0.573231,0.945563,-0.123563,-0.615851,0.790784,0.109752,0.740208,-1.320297,-0.948834,0.575784,1.665266,-1.441528,0.654550,-1.147420,-0.376428
48,-1.580739,2.876094,-0.336080,-1.994517,-1.594873,-2.231834,-1.546020,3.509191,3.099355,-0.168854,-0.167354,7.197639,-0.086365,-0.065985,6.407039,-0.740285,2.916154,0.507667,-0.574591,0.998737,-0.068855,-0.631875,0.781533,0.105957,0.508333,-0.824016,-0.457831,0.549411,1.954012,-1.082297,0.708403,-1.118582,-0.372033
49,-1.703670,2.839519,-0.456874,-2.263184,-1.457570,-2.467810,-1.546020,3.407839,3.099355,-0.168854,-0.167354,3.506216,-0.086365,-0.065985,3.150586,-0.730832,2.947024,0.509082,-0.508592,0.888033,0.002953,-0.637213,0.776472,0.102395,0.245599,-0.488570,-0.052309,1.026761,0.911310,-0.487044,0.722207,-1.121546,-0.375632
50,-1.860317,2.773019,-0.417332,-2.193669,-1.540674,-2.517826,-1.546020,3.306486,3.099355,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.721379,2.977895,0.510498,-0.425744,0.894833,0.005651,-0.636809,0.774015,0.099332,0.157321,-0.353163,0.178648,1.515911,1.066380,-0.463736,0.749141,-1.087524,-0.382022
51,-2.056904,2.673268,-0.382665,-2.045244,-1.273295,-2.077936,-1.342138,3.306486,3.311718,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.705497,3.008886,0.513057,-0.464399,0.881129,0.064125,-0.636551,0.772984,0.098011,0.061187,-0.538046,0.351434,1.297310,0.992164,-0.101161,0.769865,-1.072733,-0.386413
52,-2.095806,3.022395,-0.372914,-1.645061,-0.930038,-1.536730,-1.138256,3.306486,3.524079,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.689616,3.039878,0.515617,-0.523275,0.824545,0.126076,-0.638732,0.772673,0.098626,0.025537,-0.697063,0.408494,0.926959,0.431985,0.329578,0.764336,-1.058679,-0.384817
53,-2.135227,3.112170,-0.440082,-1.413030,-0.267009,-1.304601,-1.138256,2.850400,3.736441,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.667496,3.052275,0.517686,-0.584444,0.769107,0.176507,-0.643583,0.771780,0.099765,0.072779,-0.791284,0.339465,0.558068,-0.109217,0.674493,0.751909,-1.048334,-0.374832
54,-2.279425,2.841736,-0.418957,-1.689213,0.648946,-1.049387,-1.138256,2.394313,3.948803,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.645375,3.064671,0.519755,-0.582150,0.701637,0.139619,-0.649246,0.769957,0.100192,0.100156,-0.739465,0.216267,0.608741,-0.759753,0.410538,0.740873,-1.061643,-0.373235
55,-2.362417,2.623393,-0.459583,-1.721152,1.071694,-1.007066,-1.138256,2.090256,4.161166,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.615882,3.042430,0.519591,-0.543921,0.715962,0.093233,-0.655918,0.767355,0.100180,0.150886,-0.793094,0.142720,0.901167,-0.588441,0.083020,0.740191,-1.046852,-0.378829
56,-2.377460,2.669943,-0.481250,-1.967275,1.319201,-1.107099,-1.138256,1.786198,4.373528,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.586388,3.020189,0.519428,-0.537293,0.818815,0.030972,-0.663021,0.764120,0.099642,0.240236,-0.850368,-0.007828,0.999815,0.473052,-0.349736,0.756770,-1.037244,-0.383224
57,-2.316772,2.296433,-0.448208,-2.176760,1.653425,-1.298189,-1.274177,1.988903,4.090378,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.559541,3.017515,0.520045,-0.573994,0.874825,0.002644,-0.671032,0.760288,0.098848,0.279676,-0.842179,-0.079683,0.820706,1.071318,-0.539835,0.776117,-1.052773,-0.378825
58,-2.111886,2.104691,-0.522417,-2.126033,2.444724,-1.361030,-1.410098,2.191608,3.807229,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.532694,3.014841,0.520662,-0.664217,0.921238,0.002486,-0.676667,0.757035,0.097658,0.133968,-0.550402,0.115321,0.259681,1.555113,-0.529175,0.785095,-1.051298,-0.370440
59,-2.034600,1.972799,-0.611794,-1.865819,3.261314,-1.289211,-1.546020,2.394313,3.524079,-0.168854,-0.167354,-0.185207,-0.086365,-0.065985,-0.105868,-0.505848,3.012167,0.521279,-0.758266,0.948886,0.002175,-0.674569,0.756847,0.096480,-0.092267,-0.228614,0.478102,-0.375737,1.817389,-0.520663,0.794059,-1.043902,-0.363254

S7 X_train[0]: shape=(128, 33); label=0 (Dryoffhands)
Source: S7_Dryoffhands_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,-0.193974,-0.739190,-0.208380,-0.110357,-0.350862,-0.043824,-1.056696,-0.470916,-0.328287,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.378683,-0.305279,-1.119933,0.250685,-1.279138,-0.450162,0.268194,-0.949070,-0.537828,-0.045227,-1.699269,-1.744656,0.018173,-2.356718,-0.193671,0.773286,-0.261321,0.075579
1,-0.128987,-0.762604,-0.240084,-0.060584,-0.346152,-0.065252,-1.056696,-0.598604,-0.328287,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.395032,-0.318037,-1.119795,0.207594,-1.319019,-0.630244,0.225061,-0.949555,-0.561715,-0.312748,-1.598247,-1.589829,-0.049190,-2.609550,-0.730282,0.784458,-0.243649,0.061496
2,-0.065476,-0.825961,-0.335590,0.039234,-0.316006,-0.038954,-1.056696,-0.726292,-0.328287,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.411381,-0.330795,-1.119658,0.171417,-1.275568,-0.832666,0.179577,-0.937327,-0.582587,-0.780574,-1.470430,-1.405809,-0.137088,-2.047638,-0.788637,0.817922,-0.214929,0.075563
3,0.037174,-0.941657,-0.437437,0.028083,-0.288686,-0.075966,-1.056696,-0.853981,-0.328287,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.427730,-0.343553,-1.119520,0.027399,-1.187470,-0.720505,0.136715,-0.919398,-0.599820,-1.079177,-1.392051,-1.276143,-0.543829,-1.707668,-0.462143,0.832788,-0.128838,0.041111
4,0.142040,-1.030495,-0.414848,-0.037193,-0.307527,-0.235700,-1.056696,-0.853981,-0.527557,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.443863,-0.364253,-1.118970,-0.069064,-1.145809,-0.631534,0.095780,-0.899574,-0.614974,-1.158403,-1.324037,-1.161514,-0.523160,-1.586216,-0.447007,0.861284,-0.186255,0.097411
5,0.088869,-0.899648,-0.358575,-0.131300,-0.246294,-0.197714,-1.056696,-0.853981,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.459997,-0.384952,-1.118421,-0.038248,-1.077954,-0.738559,0.057090,-0.879033,-0.628291,-1.251958,-1.241523,-1.122325,-0.207908,-1.344888,-0.832780,0.871195,-0.281193,0.095836
6,0.023143,-0.735057,-0.366501,-0.169650,-0.226511,-0.145119,-1.056696,-0.853981,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.467741,-0.406824,-1.117664,-0.024852,-1.041047,-0.968059,0.021887,-0.855982,-0.638599,-1.489428,-1.101361,-1.134380,-0.219015,-1.319393,-1.072650,0.887296,-0.323138,0.103665
7,0.023143,-0.659993,-0.395430,-0.125316,-0.209554,-0.187974,-1.056696,-0.853981,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.475485,-0.428695,-1.116908,-0.074422,-1.016047,-0.886836,-0.009952,-0.829431,-0.645666,-1.694578,-1.000330,-1.131355,-0.386583,-1.000853,-0.635260,0.915805,-0.347412,0.164690
8,0.105854,-0.796349,-0.406922,-0.135924,-0.243468,-0.418810,-1.056696,-1.045513,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.483230,-0.454472,-1.115877,-0.219784,-0.894024,-0.728238,-0.040104,-0.801944,-0.651188,-1.665816,-0.928182,-1.049909,-0.910923,-0.398970,-0.568591,0.936874,-0.307645,0.217903
9,0.133178,-0.914799,-0.373634,-0.203920,-0.259483,-0.440237,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.490974,-0.480249,-1.114846,-0.383637,-0.796765,-0.727971,-0.068229,-0.774478,-0.655341,-1.708960,-0.820949,-0.983543,-1.170614,-0.060041,-0.459669,0.950517,-0.292173,0.238239
10,0.020189,-0.825961,-0.327664,-0.184065,-0.330137,-0.371084,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.499578,-0.492226,-1.114480,-0.419404,-0.710102,-0.586403,-0.093755,-0.745844,-0.657469,-1.798958,-0.754973,-0.902097,-1.048423,0.283784,-0.167300,0.918289,-0.309823,0.230378
11,-0.075815,-0.750897,-0.312605,-0.103013,-0.437531,-0.313619,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.508183,-0.504203,-1.114113,-0.331659,-0.615457,-0.559318,-0.118387,-0.717218,-0.658818,-1.716124,-0.769444,-0.850810,-0.680706,0.818886,-0.167719,0.934390,-0.406984,0.253850
12,-0.021167,-0.739189,-0.362538,-0.072279,-0.531736,-0.286347,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.516788,-0.516180,-1.113746,-0.310885,-0.516051,-0.598006,-0.143131,-0.690477,-0.660571,-1.536282,-0.771482,-0.832706,-0.537557,1.136404,-0.292457,0.974071,-0.490897,0.236648
13,0.145733,-0.801169,-0.425548,-0.134836,-0.433762,-0.338943,-1.056696,-1.237046,-0.859674,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.524962,-0.527116,-1.113792,-0.311551,-0.517837,-0.685679,-0.165822,-0.666927,-0.662265,-1.291545,-0.662182,-0.841736,-0.557056,0.996521,-0.422124,0.997599,-0.501922,0.161540
14,0.228444,-0.736435,-0.471518,-0.172369,-0.296223,-0.330177,-1.056696,-1.237046,-0.992520,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.533137,-0.538051,-1.113838,-0.391936,-0.466055,-0.685687,-0.185982,-0.646797,-0.663856,-1.054075,-0.594198,-0.820608,-0.774083,1.188082,-0.414919,1.044719,-0.501922,0.185011
15,0.200381,-0.670323,-0.525810,-0.035561,-0.234989,-0.422706,-1.056696,-1.237046,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.541311,-0.548987,-1.113884,-0.489073,-0.460699,-0.666343,-0.206181,-0.629905,-0.666527,-0.823718,-0.579727,-0.850810,-1.067894,1.128524,-0.371328,1.067036,-0.493052,0.178757
16,0.200381,-0.807367,-0.537699,0.030803,-0.161509,-0.495755,-1.056696,-1.237046,-1.125367,2.550098,4.902397,-0.175064,-0.122574,-0.082490,-0.093299,1.547119,-0.563438,-1.113815,-0.532615,-0.455934,-0.662473,-0.224872,-0.615719,-0.669419,-0.650989,-0.495204,-0.896048,-1.120973,1.049036,-0.344184,1.068272,-0.534975,0.131814
17,0.255768,-0.885186,-0.576932,0.003060,-0.044695,-0.461665,-1.056696,-1.237046,-1.125367,5.281942,9.987006,-0.175064,-0.122574,-0.082490,-0.093299,1.552927,-0.577888,-1.113746,-0.575486,-0.472008,-0.666351,-0.241178,-0.603896,-0.672056,-0.474601,-0.390039,-0.908146,-1.147923,0.863975,-0.438323,1.064552,-0.643116,0.186570
18,0.300078,-0.847310,-0.585650,-0.087238,-0.039985,-0.560038,-1.056696,-1.332812,-1.125367,3.916020,7.444701,-0.175064,-0.122574,-0.082490,-0.093299,1.554541,-0.587262,-1.113746,-0.604291,-0.439265,-0.775941,-0.254350,-0.594182,-0.674051,-0.377541,-0.291075,-0.817583,-1.241364,1.115710,-0.593165,1.069482,-0.713781,0.181876
19,0.265368,-0.763293,-0.524225,-0.051336,-0.037158,-0.530818,-1.056696,-1.428578,-1.125367,2.550098,4.902397,-0.175064,-0.122574,-0.082490,-0.093299,1.556154,-0.596635,-1.113746,-0.603616,-0.387484,-0.805598,-0.271445,-0.582221,-0.676805,-0.377489,-0.216859,-0.630625,-1.181594,1.396407,-0.485152,1.045929,-0.724851,0.145865
20,0.246906,-0.717152,-0.444570,0.021555,-0.100276,-0.633087,-1.056696,-1.524345,-1.125367,1.184176,2.360092,-0.175064,-0.122574,-0.082490,-0.093299,1.557767,-0.606009,-1.113746,-0.588209,-0.289273,-0.560616,-0.289058,-0.567336,-0.678504,-0.280377,-0.167363,-0.425476,-1.004603,1.909746,-0.088832,1.052120,-0.665234,0.205316
21,0.271276,-0.768113,-0.433474,-0.018154,-0.094624,-0.525948,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.559381,-0.615382,-1.113746,-0.537298,-0.297603,-0.568349,-0.303222,-0.554187,-0.679298,-0.104040,-0.163258,-0.241499,-0.795806,1.697849,-0.165197,1.027343,-0.632159,0.195927
22,0.321494,-0.794971,-0.486577,-0.123412,-0.068246,-0.518157,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.563253,-0.632957,-1.113128,-0.512516,-0.325577,-0.693420,-0.316121,-0.545475,-0.681286,0.050751,-0.190044,-0.057478,-0.651796,1.295109,-0.398336,1.031101,-0.601239,0.211569
23,0.384266,-0.774311,-0.486181,-0.150339,-0.020201,-0.566856,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.567125,-0.650532,-1.112509,-0.491750,-0.397601,-0.623793,-0.328077,-0.541561,-0.684795,0.176728,-0.241637,0.141578,-0.614972,0.944883,-0.136365,1.014999,-0.563672,0.245989
24,0.380573,-0.739648,-0.498994,-0.111717,0.028785,-0.522052,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.567986,-0.658864,-1.112051,-0.501130,-0.400579,-0.523226,-0.340041,-0.541546,-0.689880,0.396208,-0.260125,0.343702,-0.579504,0.954478,-0.013368,1.010057,-0.587968,0.224077
25,0.353987,-0.784641,-0.499259,-0.052968,-0.000418,-0.614581,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.568846,-0.667196,-1.111593,-0.420070,-0.427961,-0.643137,-0.350148,-0.544508,-0.695377,0.496980,-0.266326,0.482442,-0.120980,0.543562,-0.309262,1.038565,-0.583544,0.211553
26,0.374665,-0.803235,-0.464781,-0.055416,0.009944,-0.612633,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.569706,-0.675528,-1.111135,-0.273367,-0.583314,-0.645725,-0.355125,-0.551675,-0.700410,0.439352,-0.256020,0.497521,0.314669,-0.429455,-0.114310,1.033597,-0.623311,0.161508
27,0.410851,-0.789462,-0.439418,-0.087782,-0.012665,-0.611659,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.569061,-0.677090,-1.110653,-0.220454,-0.652360,-0.432965,-0.355914,-0.561323,-0.704674,0.417806,-0.218927,0.518693,0.445608,-0.643101,0.313090,1.073252,-0.636560,0.148984
28,0.443345,-0.814943,-0.385523,-0.063848,-0.088971,-0.612633,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.568416,-0.678653,-1.110172,-0.205717,-0.630335,-0.349154,-0.352502,-0.570840,-0.707093,0.460949,-0.066332,0.494540,0.506233,-0.402856,0.294158,1.068272,-0.616687,0.152119
29,0.447530,-0.657468,-0.421321,-0.065480,-0.103102,-0.451925,-1.056696,-1.428578,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.561962,-0.675137,-1.108935,-0.186958,-0.635699,-0.586403,-0.345151,-0.579900,-0.707633,0.432187,0.038805,0.364788,0.527188,-0.372197,-0.214349,1.074476,-0.585767,0.250683
30,0.498732,-0.505044,-0.502429,-0.187873,-0.122885,-0.343813,-1.056696,-1.237046,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.555509,-0.671622,-1.107698,-0.242556,-0.601766,-0.735970,-0.340133,-0.587159,-0.708413,0.345797,-0.041613,0.183835,0.141767,-0.128110,-0.433567,1.044706,-0.550401,0.274154
31,0.546734,-0.469922,-0.502825,-0.292586,-0.149263,-0.269789,-1.056696,-1.237046,-1.075549,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.549539,-0.668986,-1.105825,-0.466293,-0.637478,-0.778529,-0.344694,-0.592046,-0.712292,0.205490,-0.142644,0.078279,-0.622210,-0.392485,-0.350435,1.037267,-0.537198,0.253866
32,0.532703,-0.571155,-0.456459,-0.205280,-0.201075,-0.135379,-1.056696,-1.237046,-1.025732,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.543570,-0.666350,-1.103952,-0.604287,-0.666647,-0.532249,-0.354632,-0.596270,-0.718161,0.155079,-0.074571,0.156701,-0.916785,-0.573295,0.109704,1.028617,-0.510702,0.233529
33,0.436699,-0.782346,-0.488427,-0.190864,-0.411153,-0.042850,-1.056696,-1.237046,-0.975914,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.537600,-0.663714,-1.102079,-0.528589,-0.681529,-0.573510,-0.360413,-0.601042,-0.722479,0.111884,0.082070,0.256251,-0.447154,-0.464157,-0.149419,1.024885,-0.446683,0.116204
34,0.475100,-0.868658,-0.509562,-0.364118,-0.410211,0.128572,-1.056696,-1.237046,-0.926097,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.531631,-0.661077,-1.100205,-0.322275,-0.581531,-0.852019,-0.356076,-0.602353,-0.721177,-0.078835,0.242905,0.244196,0.245997,0.151020,-0.653086,1.050922,-0.367217,0.069277
35,0.678924,-0.604211,-0.529377,-0.221327,-0.273614,0.086690,-0.929341,-1.237046,-0.859674,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.521090,-0.656260,-1.096058,-0.170880,-0.594031,-0.699863,-0.344482,-0.600481,-0.715547,-0.130669,0.288284,0.146400,0.621980,-0.083746,-0.159089,1.048451,-0.429012,0.078650
36,0.833515,-0.707052,-0.486313,0.015300,-0.115349,-0.373032,-0.801986,-1.237046,-0.793250,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.510549,-0.651443,-1.091911,-0.066383,-0.653551,-0.423934,-0.326669,-0.600861,-0.708129,0.079461,0.434660,0.096340,0.986568,-0.399858,0.323044,1.024885,-0.417964,0.048909
37,0.441868,-0.708888,-0.660549,0.215752,-0.001360,-0.135379,-0.674630,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.500009,-0.646627,-1.087764,0.086344,-0.620218,-0.394285,-0.300782,-0.603808,-0.698174,0.223428,0.529489,-0.084613,1.360805,-0.062127,0.520285,1.043483,-0.490829,0.102121
38,0.503163,-0.476120,-0.813122,-0.084791,0.050453,-0.002916,-0.674630,-1.237046,-0.826462,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.495169,-0.647994,-1.086012,0.099071,-0.531532,0.036364,-0.272585,-0.605563,-0.686588,0.619297,0.488261,-0.383262,1.222763,0.615748,1.164526,1.042235,-0.521772,0.124033
39,0.644954,-0.390725,-0.896343,-0.565659,0.165383,-0.057460,-0.674630,-1.237046,-0.926097,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.490328,-0.649361,-1.084259,0.123188,-0.414865,-0.124799,-0.250451,-0.610553,-0.678800,1.090680,0.296536,-0.766382,1.412511,1.453523,0.453896,1.027331,-0.409207,0.130271
40,0.657877,-0.413796,-0.782706,-0.933109,0.235330,-0.090819,-0.674630,-1.237046,-1.025732,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.485488,-0.650727,-1.082506,0.222998,-0.449387,-1.085389,-0.245067,-0.621806,-0.680822,1.065475,-0.041613,-1.245985,1.451725,0.917417,-1.650651,1.009981,-0.429079,0.120914
41,0.670801,-0.436866,-0.669070,-1.300560,0.305278,-0.124178,-0.674630,-1.237046,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.480648,-0.652095,-1.080753,-0.089829,-0.670812,-1.381960,-0.253349,-0.629784,-0.687594,0.676873,-0.381799,-1.426980,0.131590,-0.817925,-1.371655,0.946772,-0.400405,0.130271
42,0.531226,-0.661370,-0.534528,-1.101740,0.503580,-0.039928,-1.056696,-1.620111,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.480648,-0.638815,-1.072367,-0.600269,-0.850573,-0.480676,-0.267286,-0.634386,-0.695525,0.586927,-0.177669,-1.128331,-1.542895,-1.479032,0.467430,0.949269,-0.415853,0.161540
43,0.503163,-0.752963,-0.581291,-0.333384,0.460245,-0.038954,-1.056696,-1.492423,-0.992520,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.487962,-0.631525,-1.069801,-0.947933,-0.786883,-0.133822,-0.274660,-0.640804,-0.701232,0.759655,0.044977,-0.579381,-2.557165,-0.756769,0.753933,0.967867,-0.484273,0.183436
44,0.619845,-0.529147,-0.647868,0.013396,0.359446,-0.532766,-1.056696,-1.364734,-0.859674,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.495276,-0.624235,-1.067235,-0.986112,-0.616052,-0.485837,-0.277095,-0.649742,-0.705725,0.684090,0.071793,-0.048491,-2.249691,0.386767,-0.140309,1.013713,-0.464423,0.206907
45,0.654554,-0.080138,-0.829766,-0.244173,0.549740,-0.862949,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.502590,-0.616944,-1.064669,-0.708788,-0.560697,-0.868774,-0.278771,-0.657800,-0.709530,0.500536,-0.082840,0.277336,-1.354202,0.572308,-0.877314,1.054591,-0.464400,0.178757
46,0.614675,-0.013337,-1.046537,-0.670373,0.738151,-0.123691,-1.056696,-1.045513,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.519369,-0.606399,-1.061301,-0.572801,-0.616648,-1.093130,-0.283951,-0.663875,-0.714092,0.227088,-0.251885,0.585059,-0.973247,0.213073,-1.050181,1.070705,-0.437904,0.169353
47,0.584397,-0.328057,-1.118266,-0.410628,0.809747,0.389601,-1.056696,-0.853981,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.536148,-0.595854,-1.057933,-0.574808,-0.683907,-0.752734,-0.289658,-0.668213,-0.718213,0.133430,-0.117895,1.004257,-1.121447,-0.323396,-0.238862,1.071966,-0.433480,0.149016
48,0.681878,-0.261256,-0.994623,0.318834,1.208235,0.313630,-1.184052,-0.981669,-0.859674,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.548625,-0.593511,-1.055688,-0.649169,-0.786287,-0.524508,-0.288506,-0.673280,-0.719618,0.018380,0.125394,1.453787,-1.236664,-0.939870,0.100544,1.068272,-0.464378,0.100530
49,0.670062,0.067925,-1.057634,-0.002923,1.366500,0.091560,-1.311407,-1.109357,-0.992520,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.561102,-0.591168,-1.053442,-0.467633,-0.837478,-0.667642,-0.280799,-0.677325,-0.717779,-0.312748,0.172794,1.646838,-0.367738,-1.191568,-0.448256,1.094322,-0.398159,0.084903
50,0.283092,0.370248,-0.918139,-0.777534,1.220482,0.971072,-1.438762,-1.237046,-1.125367,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.573578,-0.588824,-1.051197,-0.131360,-0.851172,-0.777231,-0.273055,-0.676360,-0.714033,-0.701349,0.007884,1.511080,0.659952,-1.163589,-0.428829,1.070756,-0.411385,0.106831
51,0.273492,0.231138,-0.702556,-1.048159,1.064101,1.759029,-1.438762,-1.237046,-0.992520,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.588206,-0.589345,-1.049868,0.036104,-0.807122,-0.663763,-0.268442,-0.670442,-0.709789,-0.816450,-0.029239,1.230491,1.136785,-0.980187,-0.255014,1.104220,-0.417987,0.099002
52,0.664893,-0.029865,-0.495296,-0.540908,0.785253,1.664552,-1.438762,-1.237046,-0.859674,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.602834,-0.589866,-1.048539,0.109125,-0.774979,-0.634106,-0.263249,-0.662726,-0.704590,-0.820110,0.086204,0.950032,1.279864,-0.651761,-0.104832,1.100500,-0.448884,0.159996
53,0.881271,-0.176551,-0.288431,-0.094038,-0.060710,1.526246,-1.438762,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,-0.122574,-0.082490,-0.093299,1.617462,-0.590386,-1.047210,0.085008,-0.641647,-0.543853,-0.255464,-0.654372,-0.697986,-0.625732,0.179025,0.591065,1.084395,0.258054,-0.034647,1.050910,-0.550424,0.174063
54,0.637569,-0.002319,-0.248802,0.574227,-0.886890,2.128171,-1.247729,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,8.051380,13.024929,-0.093299,1.629724,-0.589996,-1.044048,-0.042936,-0.535701,-0.438126,-0.247691,-0.647855,-0.692055,-0.287542,0.172824,0.213994,0.539931,0.691709,0.307247,1.080666,-0.576943,0.103649
55,0.381312,-0.223380,-0.196492,0.969964,-1.314581,1.456119,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,16.225334,26.132347,-0.093299,1.641985,-0.589605,-1.040887,-0.168208,-0.642243,-0.394277,-0.242084,-0.645227,-0.688558,0.014772,0.158353,-0.057478,0.168311,-0.299780,0.204706,1.054629,-0.570364,0.092717
56,0.545257,-1.462976,-0.483803,0.220376,-1.400308,0.518167,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,10.776031,17.394068,-0.093299,1.640265,-0.592729,-1.038366,-0.199689,-0.764862,-0.533539,-0.237367,-0.644866,-0.686319,-0.064402,0.191400,-0.205291,0.112501,-0.910457,-0.032986,1.104207,-0.497521,0.113037
57,0.485439,-2.482198,-0.629242,-0.080439,-1.877929,-0.058434,-1.056696,-1.237046,-0.726827,-0.181746,-0.182212,-0.175064,5.326729,8.655788,-0.093299,1.638544,-0.595854,-1.035846,-0.191650,-0.790457,-0.555456,-0.231207,-0.642123,-0.682514,-0.323521,0.329494,-0.208315,0.090823,-1.060928,-0.145431,1.119086,-0.451152,0.134933

S8 X_train[0]: shape=(128, 33); label=0 (PressByGrasp)
Source: S8_PressByGrasp_1_extracted / Event_0 / window 0

,android.sensor.accelerometer_value_1,android.sensor.accelerometer_value_2,android.sensor.accelerometer_value_3,android.sensor.gyroscope_value_1,android.sensor.gyroscope_value_2,android.sensor.gyroscope_value_3,JinsAccelerometer_value_1,JinsAccelerometer_value_2,JinsAccelerometer_value_3,JinsBlinkSpeed_value_1,JinsBlinkStrength_value_1,JinsEyeMovement_value_1,JinsEyeMovement_value_2,JinsEyeMovement_value_3,JinsEyeMovement_value_4,JinsGyroscope_value_1,JinsGyroscope_value_2,JinsGyroscope_value_3,PhoneAccelerometer_value_1,PhoneAccelerometer_value_2,PhoneAccelerometer_value_3,PhoneGravity_value_1,PhoneGravity_value_2,PhoneGravity_value_3,PhoneGyroscope_value_1,PhoneGyroscope_value_2,PhoneGyroscope_value_3,PhoneLinearAccelerometer_value_1,PhoneLinearAccelerometer_value_2,PhoneLinearAccelerometer_value_3,PhoneMagnetometer_value_1,PhoneMagnetometer_value_2,PhoneMagnetometer_value_3
timestep (20 ms each),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,-0.531968,-1.031155,-0.561594,0.298488,-0.503932,-0.203238,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.652555,1.269178,-1.187978,0.793629,-0.385811,-0.688597,0.817109,-0.397510,-0.710077,0.048021,-0.038823,0.007500,-0.024895,0.018713,0.062572,-0.337714,0.083553,0.245762
1,-0.516841,-0.990434,-0.514840,0.228304,-0.684524,-0.211068,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.642510,1.273482,-1.186920,0.789737,-0.385046,-0.691467,0.816620,-0.397670,-0.710657,0.078595,-0.033717,0.026968,-0.034740,0.027122,-0.032223,-0.342103,0.087253,0.238732
2,-0.507764,-0.996357,-0.402767,0.444139,-0.703079,-0.156256,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.632465,1.277787,-1.185863,0.783179,-0.380457,-0.704998,0.816114,-0.398081,-0.711488,0.095276,-0.027989,0.041972,-0.091376,-0.003109,0.060562,-0.349904,0.054079,0.261834
3,-0.490822,-1.035598,-0.492838,0.447912,-0.637521,-0.172700,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.622421,1.282092,-1.184806,0.770475,-0.392440,-0.697822,0.815990,-0.398671,-0.712160,0.127243,-0.012679,0.098895,-0.078073,0.043039,0.054011,-0.360135,-0.003681,0.278918
4,-0.473274,-0.951194,-0.575346,0.358862,-0.643706,-0.225162,-1.036704,1.186448,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.595112,1.287831,-1.183952,0.769042,-0.380966,-0.688392,0.816538,-0.399843,-0.712802,0.134170,0.007729,0.157364,-0.079397,0.072102,0.029521,-0.358672,-0.039292,0.273891
5,-0.458147,-0.883819,-0.584284,0.132462,-0.500221,-0.261965,-1.036704,1.038647,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.567803,1.293571,-1.183098,0.773345,-0.373828,-0.702744,0.818024,-0.401783,-0.713359,0.114723,0.005180,0.181318,0.012106,0.012217,-0.014430,-0.357204,-0.062616,0.303031
6,-0.456937,-0.840137,-0.578096,0.122651,-0.327049,-0.271361,-1.036704,1.038647,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.556503,1.298593,-1.182854,0.786458,-0.389635,-0.703152,0.819870,-0.404033,-0.713896,0.113349,-0.008212,0.154359,0.072937,-0.038846,0.030408,-0.352815,-0.063828,0.290985
7,-0.445441,-0.951194,-0.571220,0.156611,-0.309732,-0.355145,-1.036704,1.038647,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.545203,1.303615,-1.182610,0.800186,-0.405187,-0.703563,0.821793,-0.406262,-0.714342,0.104989,-0.009491,0.133367,0.151277,-0.018328,-0.008242,-0.354283,-0.017143,0.253824
8,-0.453307,-0.928983,-0.530654,0.479608,-0.273861,-0.186011,-1.036704,1.038647,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.533903,1.308637,-1.182366,0.820468,-0.400343,-0.703563,0.823940,-0.408678,-0.714766,0.121690,-0.005033,0.103424,0.172925,-0.090025,0.046603,-0.353306,-0.001194,0.235749
9,-0.460568,-0.829031,-0.565720,0.386784,-0.088320,-0.213417,-1.036704,1.137181,0.453139,1.999177,1.837346,-0.192201,-0.116476,-0.132778,-0.110129,-0.537670,1.313659,-1.182000,0.828868,-0.420996,-0.699667,0.826078,-0.411114,-0.715215,0.107776,-0.001844,0.076444,0.167717,-0.142358,0.089912,-0.352334,-0.014743,0.220678
10,-0.474485,-0.837916,-0.538217,0.300752,-0.082136,-0.174266,-1.036704,1.235715,0.453139,4.178667,3.852786,-0.192201,-0.116476,-0.132778,-0.110129,-0.541436,1.318681,-1.181634,0.828870,-0.439608,-0.692902,0.828045,-0.413373,-0.715639,0.111976,-0.019695,0.022482,0.228355,-0.105166,0.045674,-0.351843,0.012268,0.231723
11,-0.491427,-0.843839,-0.476336,0.241134,-0.166247,-0.162520,-1.036704,1.334249,0.453139,6.358157,5.868226,-0.192201,-0.116476,-0.132778,-0.110129,-0.545203,1.323703,-1.181268,0.839320,-0.439353,-0.696798,0.829236,-0.415042,-0.716179,0.103596,-0.024162,-0.014973,0.235345,-0.048214,-0.016290,-0.355741,0.012281,0.258840
12,-0.452097,-0.863089,-0.391765,0.299998,-0.176143,-0.161737,-1.036704,1.334249,0.453139,3.088922,2.845066,-0.192201,-0.116476,-0.132778,-0.110129,-0.558387,1.331236,-1.180109,0.843008,-0.422525,-0.707868,0.829797,-0.416253,-0.716836,0.096669,-0.027989,-0.050947,0.167627,0.020008,-0.077408,-0.349403,0.035630,0.271888
13,-0.457542,-0.871233,-0.364263,0.261510,-0.282520,-0.118671,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.571570,1.338769,-1.178950,0.842803,-0.407994,-0.717297,0.829520,-0.416528,-0.717337,0.092489,-0.028629,-0.043456,0.058182,0.029389,0.071958,-0.341598,0.081103,0.296993
14,-0.423658,-0.819406,-0.365638,0.120387,-0.328286,-0.125718,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.577220,1.346900,-1.177689,0.817190,-0.397028,-0.702948,0.829157,-0.416476,-0.717605,0.086955,-0.034356,-0.020961,-0.009639,0.013406,0.151249,-0.336237,0.092165,0.302020
15,-0.426078,-0.806820,-0.353949,0.086427,-0.461876,-0.123369,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.582870,1.355031,-1.176428,0.799776,-0.406971,-0.687573,0.828954,-0.416469,-0.717776,0.092489,-0.043930,-0.010465,0.055904,0.007383,0.130203,-0.332334,0.098302,0.277906
16,-0.423052,-0.797195,-0.297569,0.078880,-0.578148,-0.056812,-1.036704,1.334249,0.453139,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.588520,1.363162,-1.175168,0.806538,-0.406463,-0.682242,0.828885,-0.417038,-0.718374,0.092489,-0.056052,-0.016475,0.143104,0.030760,0.050223,-0.329408,0.108139,0.279919
17,-0.406110,-0.776464,-0.277630,-0.129408,-0.659786,-0.052897,-1.036704,1.334249,0.719087,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.591659,1.377989,-1.173338,0.823612,-0.404932,-0.702469,0.828754,-0.417583,-0.719003,0.085562,-0.059880,-0.020961,0.152787,0.031038,0.016445,-0.339654,0.074953,0.263847
18,-0.390630,-0.766407,-0.290521,-0.185159,-0.651282,-0.058280,-1.036704,1.334249,0.985035,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.594798,1.392816,-1.171508,0.817908,-0.407608,-0.704178,0.828386,-0.418111,-0.719823,0.077202,-0.056052,-0.022464,0.045395,-0.020751,0.044170,-0.341598,0.062679,0.238732
19,-0.375150,-0.756350,-0.303413,-0.240910,-0.642778,-0.063663,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.597937,1.407643,-1.169678,0.801415,-0.422524,-0.715247,0.827627,-0.418620,-0.720964,0.070699,-0.052651,-0.012504,0.002853,-0.032044,-0.014249,-0.340135,0.044255,0.238732
20,-0.359670,-0.746294,-0.316305,-0.296661,-0.634274,-0.069047,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.606412,1.426656,-1.167116,0.805921,-0.431448,-0.724883,0.827002,-0.419593,-0.722425,0.079968,-0.052855,-0.016454,0.044705,-0.072623,-0.059259,-0.353787,-0.004906,0.216642
21,-0.344190,-0.736237,-0.329197,-0.352412,-0.625770,-0.074430,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.614887,1.445668,-1.164554,0.819651,-0.449296,-0.730007,0.826806,-0.421212,-0.724119,0.096649,-0.043291,-0.029955,0.097458,-0.121808,-0.097650,-0.361097,-0.002431,0.205607
22,-0.323213,-0.820147,-0.331260,-0.312792,-0.552172,-0.033321,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.624304,1.457386,-1.163700,0.824978,-0.457200,-0.729802,0.826729,-0.422539,-0.725433,0.081382,-0.036275,-0.083916,0.144983,-0.163482,-0.080088,-0.372320,-0.020880,0.219687
23,-0.323818,-0.820887,-0.327134,-0.272794,-0.449506,-0.017660,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.633721,1.469104,-1.162846,0.830303,-0.445473,-0.732671,0.826267,-0.423096,-0.726357,0.038307,-0.040112,-0.107891,0.159685,-0.116432,-0.101718,-0.374760,-0.030705,0.237772
24,-0.338341,-0.866790,-0.306507,-0.230533,-0.354262,0.031670,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.643138,1.480822,-1.161991,0.831944,-0.412072,-0.735338,0.825223,-0.422321,-0.726534,-0.010341,-0.035005,-0.170803,0.179567,0.008982,-0.112083,-0.367450,-0.008581,0.244801
25,-0.346207,-0.839397,-0.289318,-0.165632,-0.297363,0.072388,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.671388,1.506650,-1.160894,0.824362,-0.393970,-0.723448,0.823824,-0.420497,-0.726034,-0.027002,-0.032438,-0.202270,0.145283,0.067651,-0.037535,-0.352825,-0.025780,0.267893
26,-0.344593,-0.836435,-0.229271,-0.083373,-0.272624,0.088831,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.683944,1.512150,-1.160324,0.820468,-0.384789,-0.697618,0.822304,-0.418001,-0.725002,-0.026982,-0.029889,-0.221781,0.131956,0.091682,0.118825,-0.352825,-0.015930,0.287971
27,-0.340156,-0.799416,-0.237751,-0.066770,-0.376527,0.084916,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.696500,1.517651,-1.159755,0.812069,-0.383260,-0.694952,0.820744,-0.415436,-0.723936,-0.020075,-0.027989,-0.224764,0.096063,0.087209,0.129498,-0.348922,-0.022068,0.305054
28,-0.307481,-0.815704,-0.219187,-0.044130,-0.465586,0.073171,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.709055,1.523151,-1.159186,0.798136,-0.402383,-0.689212,0.818790,-0.413002,-0.723332,-0.006161,-0.039472,-0.230774,0.034886,0.008368,0.160161,-0.357204,-0.038042,0.322138
29,-0.289329,-0.825329,-0.139429,-0.072808,-0.710500,0.097444,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.727889,1.530325,-1.158759,0.782154,-0.411817,-0.686752,0.816473,-0.410759,-0.723217,0.007733,-0.051585,-0.232255,-0.032976,-0.032340,0.171202,-0.368417,-0.009793,0.306066
30,-0.252418,-0.776464,-0.046608,-0.015453,-1.195380,0.111539,-1.036704,1.334249,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.746723,1.537500,-1.158332,0.780514,-0.391929,-0.698641,0.814094,-0.408703,-0.723327,0.025807,-0.049027,-0.218776,-0.028436,0.035763,0.096043,-0.364514,-0.029455,0.303052
31,-0.230030,-0.793493,-0.040419,0.183779,-1.474928,-0.011396,-1.036704,1.432783,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.759906,1.542761,-1.158372,0.766788,-0.388615,-0.704384,0.811620,-0.406894,-0.723749,0.048041,-0.044569,-0.190314,-0.085000,0.042137,0.061315,-0.364033,-0.035605,0.277937
32,-0.131704,-0.853834,0.020086,0.319619,-1.481113,-0.064642,-1.036704,1.531317,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.773090,1.548022,-1.158413,0.780925,-0.410288,-0.712789,0.809677,-0.405872,-0.724455,0.063308,-0.039472,-0.182823,-0.001978,-0.040872,0.011286,-0.354283,-0.022080,0.279940
33,0.051940,-0.784608,-0.045920,0.054731,-0.956651,-0.195407,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.786273,1.553283,-1.158454,0.799365,-0.416152,-0.729597,0.808105,-0.405443,-0.725399,0.068861,-0.036275,-0.197805,0.099674,-0.064261,-0.088095,-0.351838,-0.009793,0.291996
34,0.102767,-0.857166,-0.074110,0.082654,-0.856459,-0.330088,-1.036704,1.629851,1.250983,2.144476,1.495747,-0.192201,-0.116476,-0.132778,-0.110129,-0.800712,1.560697,-1.158860,0.796087,-0.414877,-0.730212,0.806431,-0.404812,-0.726239,0.032753,-0.045209,-0.206756,0.090417,-0.061855,-0.084957,-0.352324,-0.004893,0.280941
35,0.093690,-0.861608,-0.162806,0.060768,-0.670918,-0.447542,-1.036704,1.629851,1.250983,4.469265,3.169586,-0.192201,-0.116476,-0.132778,-0.110129,-0.815151,1.568111,-1.159267,0.799161,-0.411053,-0.724883,0.805053,-0.403634,-0.726307,-0.020055,-0.043291,-0.191795,0.113039,-0.051851,-0.050115,-0.352805,0.004944,0.280941
36,0.090665,-0.839397,-0.122240,0.127934,-0.386422,-0.435014,-1.036704,1.629851,1.250983,6.794055,4.843426,-0.192201,-0.116476,-0.132778,-0.110129,-0.829591,1.575524,-1.159674,0.789735,-0.409267,-0.710533,0.803803,-0.401886,-0.725724,-0.075654,-0.039728,-0.167511,0.071729,-0.050456,0.035939,-0.354764,-0.008581,0.277937
37,0.087640,-0.870493,-0.096800,0.227550,-0.346840,-0.503137,-1.036704,1.629851,1.250983,3.306871,2.332666,-0.192201,-0.116476,-0.132778,-0.110129,-0.841832,1.584851,-1.159857,0.793423,-0.411052,-0.708278,0.802649,-0.400010,-0.724936,-0.092311,-0.040751,-0.166303,0.096835,-0.062826,0.044021,-0.346968,-0.008581,0.268894
38,0.050729,-0.770541,-0.199247,0.387539,-0.395081,-0.532109,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.854074,1.594177,-1.160040,0.788916,-0.393612,-0.706514,0.801300,-0.397722,-0.723921,-0.106244,-0.042669,-0.170825,0.074430,-0.014379,0.056924,-0.339654,0.001244,0.256858
39,0.068277,-0.764618,-0.109176,0.523379,-0.364157,-0.513316,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.859254,1.599558,-1.159582,0.787276,-0.379947,-0.710123,0.799676,-0.395358,-0.723067,-0.089544,-0.040112,-0.184304,0.087786,0.032745,0.018533,-0.342579,0.018443,0.274943
40,0.062831,-0.741666,-0.132553,0.367918,-0.361684,-0.551685,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.864433,1.604939,-1.159125,0.762198,-0.377703,-0.697822,0.797462,-0.392577,-0.722316,-0.064555,-0.042783,-0.201081,-0.037768,0.040141,0.081169,-0.338672,0.011093,0.264889
41,0.070092,-0.689839,-0.246002,-0.106013,-0.386422,-0.549336,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.869612,1.610320,-1.158667,0.754904,-0.387596,-0.699052,0.795237,-0.390035,-0.721797,-0.040915,-0.035635,-0.199286,-0.065833,0.002552,0.103423,-0.335260,-0.020855,0.264889
42,0.018055,-0.575821,-0.239813,-0.173933,-0.698131,-0.491392,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.874791,1.615700,-1.158210,0.768427,-0.397622,-0.710398,0.793198,-0.387941,-0.721542,-0.047862,-0.036923,-0.220278,0.015199,-0.049687,0.011974,-0.343551,-0.014705,0.285978
43,-0.032772,-0.513628,-0.119490,-0.143746,-1.144666,-0.429532,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.895508,1.633636,-1.154916,0.796292,-0.379692,-0.715042,0.791372,-0.385863,-0.721117,-0.058969,-0.053495,-0.238265,0.168186,0.006624,-0.025154,-0.348421,-0.045429,0.292987
44,0.000507,-0.489936,-0.025293,-0.467498,-2.010522,-0.390381,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.895508,1.637941,-1.153777,0.812684,-0.354959,-0.717297,0.790718,-0.385005,-0.720855,-0.064523,-0.053504,-0.262262,0.239297,0.097574,-0.020841,-0.358176,-0.042992,0.312053
45,-0.004939,-0.412196,-0.001228,-0.641072,-2.381604,-0.313644,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.895508,1.642246,-1.152638,0.807150,-0.367453,-0.719964,0.790063,-0.384146,-0.720593,-0.058950,-0.048388,-0.274196,0.275038,0.076619,-0.058565,-0.355736,-0.030705,0.286949
46,0.099136,-0.506225,-0.129803,-0.581453,-2.099582,-0.290154,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.895508,1.646550,-1.151500,0.784613,-0.378927,-0.714836,0.789062,-0.382879,-0.720235,-0.040915,-0.044579,-0.284714,0.252044,0.033977,-0.055911,-0.355731,-0.058941,0.272890
47,0.227414,-0.591369,-0.194434,-0.454669,-1.795295,-0.246304,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.887975,1.654083,-1.150615,0.777850,-0.393203,-0.704587,0.786965,-0.380476,-0.719721,-0.056203,-0.040751,-0.319186,0.155776,-0.012205,-0.022304,-0.358176,-0.057691,0.239754
48,0.099741,-0.654301,-0.332635,-0.290906,-1.487298,-0.172700,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.880441,1.661617,-1.149731,0.784203,-0.361844,-0.693929,0.783983,-0.377167,-0.719088,-0.106224,-0.055413,-0.350631,0.105068,-0.074887,0.013305,-0.354273,-0.078565,0.226696
49,0.128180,-0.646157,-0.330572,-0.040357,-1.200328,-0.139813,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.872908,1.669150,-1.148846,0.772935,-0.344507,-0.699053,0.780882,-0.373367,-0.718076,-0.154872,-0.077100,-0.362608,0.158412,0.015435,0.092434,-0.367440,-0.085952,0.239754
50,0.186268,-0.670589,-0.287943,0.180006,-0.894804,-0.094397,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.865375,1.676683,-1.147961,0.763714,-0.353940,-0.691469,0.777461,-0.369029,-0.716807,-0.153479,-0.079648,-0.380595,0.117579,0.062717,0.054474,-0.373778,-0.057716,0.231713
51,0.185058,-0.812002,-0.598723,0.555075,-0.983864,-0.086567,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.857841,1.687205,-1.147758,0.742407,-0.349353,-0.694133,0.773821,-0.364565,-0.715588,-0.143745,-0.074542,-0.380616,0.088251,0.011955,0.094621,-0.365481,-0.050354,0.261834
52,0.119104,-0.831992,-0.460522,0.339240,-0.975205,-0.178181,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.850308,1.697727,-1.147555,0.743022,-0.335838,-0.708891,0.770248,-0.360398,-0.714585,-0.120098,-0.071363,-0.371601,-0.001258,0.014678,0.071866,-0.365481,-0.035630,0.248776
53,0.103372,-0.727599,-0.611099,-0.045640,-0.994996,-0.157039,-1.036704,1.629851,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.842774,1.708250,-1.147352,0.734004,-0.343485,-0.676502,0.766287,-0.356231,-0.713896,-0.122885,-0.073912,-0.359624,0.021381,0.050140,-0.023692,-0.358657,-0.050379,0.257819
54,0.070697,-0.549907,-0.510714,-0.403352,-1.143429,-0.156256,-1.036704,1.777652,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.844657,1.711837,-1.148144,0.721916,-0.338388,-0.682243,0.762202,-0.351962,-0.713199,-0.128458,-0.081567,-0.373104,-0.004178,0.006788,0.171761,-0.343056,-0.065116,0.292977
55,0.019870,-0.404793,-0.399329,-0.341469,-1.202802,-0.069340,-1.036704,1.925452,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.846541,1.715425,-1.148938,0.708188,-0.320541,-0.687366,0.758495,-0.347472,-0.711954,-0.120098,-0.063708,-0.355138,-0.045794,0.012474,0.125798,-0.348426,-0.055291,0.291976
56,0.077958,-0.543244,-0.210936,-1.136133,-1.270833,0.049680,-1.036704,1.925452,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.849052,1.716142,-1.149182,0.712696,-0.306009,-0.689621,0.754865,-0.343189,-0.710834,-0.121511,-0.050306,-0.323650,-0.096448,0.064916,0.085683,-0.341112,-0.062653,0.316079
57,0.017450,-0.520292,-0.144242,-0.987464,-0.951703,0.154605,-1.036704,1.925452,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.851563,1.716859,-1.149426,0.707984,-0.311615,-0.690238,0.751324,-0.339126,-0.709838,-0.090937,-0.047109,-0.286216,-0.056525,0.104711,0.065751,-0.330390,-0.028242,0.322087
58,0.102162,-0.917136,-0.237751,-1.100664,-0.632573,0.236823,-1.036704,1.925452,1.250983,-0.180313,-0.178093,-0.192201,-0.116476,-0.132778,-0.110129,-0.854074,1.717577,-1.149670,0.713312,-0.330992,-0.682448,0.747925,-0.335482,-0.709121,-0.060383,-0.051585,-0.283211,-0.063557,0.072081,0.057825,-0.326988,-0.009793,0.297984

In [8]:
from datetime import datetime

# Export every training timestep and all sensor features without changing the source arrays.
EXPORT_ROOT = DATA_PREP_DIR / 'all_subject_training_data_exports' / f'run_{datetime.now().strftime("%Y%m%d_%H%M%S")}'
EXPORT_ROOT.mkdir(parents=True, exist_ok=False)
export_rows = []

for subject, data in SUBJECT_TRAINING.items():
    X = data['X']
    metadata = data['metadata'].reset_index(drop=True)
    sample_count, timestep_count, feature_count = X.shape
    repeated_metadata = metadata.iloc[np.repeat(np.arange(sample_count), timestep_count)].reset_index(drop=True)
    export_frame = repeated_metadata[['subject', 'activity', 'label', 'original_folder', 'split', 'event', 'window_id']].copy()
    export_frame.insert(1, 'sample_index', np.repeat(np.arange(sample_count), timestep_count))
    export_frame.insert(7, 'timestep_index', np.tile(np.arange(timestep_count), sample_count))
    export_frame.insert(8, 'relative_time_ms', export_frame['timestep_index'] * 20)
    values = X.reshape(sample_count * timestep_count, feature_count)
    for feature_index, feature_name in enumerate(data['feature_names']):
        export_frame[feature_name] = values[:, feature_index]

    output_path = EXPORT_ROOT / f'{subject}_all_training_timesteps.csv'
    export_frame.to_csv(output_path, index=False)
    export_rows.append({
        'subject': subject,
        'windows': sample_count,
        'timesteps_per_window': timestep_count,
        'features': feature_count,
        'export_rows': len(export_frame),
        'csv_path': str(output_path),
    })

export_summary = pd.DataFrame(export_rows)
print(f'Complete training-data CSVs saved to: {EXPORT_ROOT.resolve()}')
display(export_summary)
print('Each CSV row is one 20 ms timestep. Columns include subject/activity/label, source folder, Event, window, timestep, and every sensor feature.')

Complete training-data CSVs saved to: D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\DATA_PREP\all_subject_training_data_exports\run_20261003_203214

,subject,windows,timesteps_per_window,features,export_rows,csv_path
0,S1,38,128,33,4864,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
1,S2,25,128,33,3200,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
2,S3,28,128,33,3584,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
3,S4,36,128,33,4608,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
4,S5,37,128,33,4736,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
5,S6,31,128,33,3968,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
6,S7,30,128,33,3840,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...
7,S8,29,128,33,3712,D:\7th sem\ML\DATASETS\Annonmazed_CogActivity\...

Each CSV row is one 20 ms timestep. Columns include subject/activity/label, source folder, Event, window, timestep, and every sensor feature.